### ISSUE TITLE
Tools should not clear the screen at start

### ISSUE THREAD

**Issue by cdrnet** [fsharp/fsharp#140]
I've noticed that in some specific constellation, the F# tools fsparpc and fsharpi cause the shell screen to be cleared about half a second after they start.

I've only observed this in a very specific system setup, but there it reproduces reliably. There's likely some issue with that setup causing this, but I noticed the clearing only seems to affect the F# tools - neither mono nor nunit-console are affected.

**System where it reproduces:**
- Vagrant setup as described [here](http://christoph.ruegg.name/blog/2013/6/7/test-csharp-fsharp-on-mono-with-vagrant.html).
- Compiled from sources at tags, Mono 3.0.10, F# 3.0.27, as described [here](http://fsharp.org/use/linux/)
- Host: Windows 8, Guest: Debian Wheezy
- git bash -> vagrant ssh -> fsharpi

**Where it does _not_ reproduce:**
- Same setup but logging directly into the VM (VirtualBox GUI) and using its shell directly
- Same setup but instead of using git-bash and vagrant-ssh connect and open a shell with the Bitvise SSH client.

**Interpretation**

I suspect this is not directly an issue of the F# tools but an issue on how git bash and vagrant ssh play together, which is somehow triggered by running the F# tools. Maybe the tools use a special capability, like colors? Maybe it's actually the ssh connection being reset?

**Comment by dsyme** [comment]
Closing this very old issue - it's something in Mono, not F#
