### ISSUE TITLE
Fix #r so mono fsi has some behaviour than .NET fsi

### ISSUE THREAD

**Issue by ovatsus** [fsharp/fsharp#251]
There seems to be a difference in assembly resolution where in mono:

```
#r "a/b/c.dll"
```

doesn't find dependencies of "c.dll" in directory in directory "a/b", while in .NET it works fine.
People usually adjust this to:

```
#I "a/b"
#r "a/b/c.dll"
```

But it's something every F# library hits when someone first try it on mono.
We should definitely fix this

**Comment by dsyme** [comment]
It's possible this fix from F# 4.0 will fix this: https://github.com/Microsoft/visualfsharp/commit/3ed163fff4b200514f945e3a7a940fe8ca4f60c6

If so, we should cherrypick it to "master" in this repo (it will also appear in the "fsharp4" branch as a result of this integration: #397 )

**Comment by dsyme** [comment]
Closing in favour of #307
