### ISSUE TITLE
AssemblyInformationalVersion taken as AssemblyVersion

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#289]
Example:

```
namespace Loggly.Zipkin.Example
open System.Reflection
open System.Runtime.CompilerServices
open System.Runtime.InteropServices
[<assembly: AssemblyTitle("Intelliplan.Loggly.Zipkin.Example")>]
[<assembly: AssemblyDescription("Assembly is a part of Intelliplan's Shared assemblies")>]
[<assembly: AssemblyConfiguration("RELEASE")>]
[<assembly: AssemblyCompany("Intelliplan International AB")>]
[<assembly: AssemblyProduct("Intelliplan.Loggly.Zipkin.Example")>]
[<assembly: AssemblyCopyright("(c) Intelliplan International 2014")>]
[<assembly: AssemblyVersion("1.2.0.0")>]
[<assembly: AssemblyFileVersion("1.2.0.0")>]
[<assembly: AssemblyInformationalVersion("1.2.0.5f0cfa")>]
()
```

Output from compiler:

```
5>FSC: warning FS2003: An AssemblyVersionAttribute specified version '1.2.0.5f0cfa', but this value is invalid and has been ignored
```

**Comment by embix** [comment]
So you're telling me, when switch from C# to F# we can no longer store our SemVer in AssemblyInformationalVersion?

**Comment by haf** [comment]
Yes, you can, with F# 4.0 without warnings.

With F# 3.1 it's just a warning, not an error.

**Comment by embix** [comment]
Using

    [<assembly: AssemblyVersion("1.0.0.0")>]
    [<assembly: AssemblyFileVersion("1.0.0.10003")>]
    [<assembly: AssemblyInformationalVersion("1.1.0-alpha+0003")>]

 with F#4 [and the following parameters][1] I still get the FS2003 warning. Using Explorer->Properties->Details I see

    File version 1.0.0.10003
    Product version 1.0.0.0

instead of 

    File version 1.0.0.10003
    Product version 1.0.1-alpha+0003

what I get with the c# assembly.
[1]: https://gist.github.com/embix/07c2c625679fb515b855#file-fsinfoversion_fsharpcompilerflags_-txt

**Comment by embix** [comment]
Nevermind, I just found https://github.com/Microsoft/visualfsharp/issues/605
