### ISSUE TITLE
CROSS_PLATFORM_COMPILER has divergent reference resolution behaviour

### ISSUE THREAD

**Issue by quasilord** [fsharp/fsharp#307]
From https://github.com/fsharp/FSharp.Compiler.Service/issues/118

To quote: 

---

I cannot extract small code snippet that reproduces the bug, so I'm afraid we have to use the sample solution here https://github.com/vasily-kirichenko/FSharpWeb1 as repro. 

---

Cause of the issue is bits in https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/ReferenceResolution.fs ifdef-ed with CROSS_PLATFORM_COMPILER. If command line suppied to the compiler doesn't have core runtime assembly (mscorlib\System.Runtime) then compiler tries to infer version of the highest installed .NET Framework and use core assembly from it. Max framework that can be inferred by F.C.S is 4.0, when desktop compiler can infer up to 4.5.1. In NET 4.0 ClaimsIdentity class was located in separate assembly but in 4.5 it was merged into mscorlib (http://msdn.microsoft.com/en-us/library/microsoft.identitymodel.claims.claimsidentity.aspx). In the bug type reference for ClaimsIdentity class says that it should be in mscorlib, mscorlib is not in command line so F.C.S will load the one for the highest available framework it is aware of (4.0) and this mscorlib doesn't contain ClaimsIdentity - boom.
I'd say that reference resolution on Windows in F.C.S and in desktop compiler should be the same.

**Comment by dsyme** [comment]
Closing old issue - this is resolved sufficently through SimulatedMSBuildReferenceResolver
