### ISSUE TITLE
Building Fsharp (CentOS)

### ISSUE THREAD

**Issue by TonyAbell** [fsharp/fsharp#313]
I followed the steps outlined in option 2 here:
http://fsharp.org/use/linux/

```
git clone https://github.com/mono/mono
 cd mono
 ./autogen.sh --prefix /usr/local
 make get-monolite-latest
 make EXTERNAL_MCS="${PWD}/mcs/class/lib/monolite/gmcs.exe"
 make
git clone https://github.com/fsharp/fsharp
 cd fsharp
 ./autogen.sh --prefix /usr/local
```

./autogen.sh --prefix /usr/local
Fsharp build failed because it assumed that mono was installed with a package.
Where I had installed mono using the source code, i.e. make; make install.

I ended up commenting out the package checks in configure.ac

```
#if ! $PKG_CONFIG --atleast-version=$MONO_REQUIRED_VERSION mono; then
#       AC_MSG_ERROR("You need mono $MONO_REQUIRED_VERSION")
#fi

#if ! $PKG_CONFIG --atleast-version=$MONO_RECOMMENDED_VERSION mono; then
#       AC_MSG_WARN([Mono $MONO_RECOMMENDED_VERSION or higher is recommended, for better GC performance])
#fi
```

then setting the mono prefix manually

```
MONOPREFIX="/usr/local"
```

There should be a command switch which would override the check for the mono package and allow the user to input the mono location.

With the changes above, I am able to generate a the Make files needed to build.  However the build fails with the following error:

```
/root/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj (default targets) ->
/usr/local/lib/mono/4.5/Microsoft.Common.targets (GetFrameworkPaths target) ->

        /usr/local/lib/mono/4.5/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v2.1' not supported by this toolset (ToolsVersion: 4.0).

/root/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj (default targets) ->
/usr/local/lib/mono/4.5/Microsoft.Common.targets (GetReferenceAssemblyPaths target) ->

        /usr/local/lib/mono/4.5/Microsoft.Common.targets:  warning : Unable to find framework corresponding to the target framework moniker '.NETFramework,Version=v2.1'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior.

         2 Warning(s)
         0 Error(s)
```

For reference I am using the Linux sandbox provided by Hortonworks
http://hortonworks.com/products/hortonworks-sandbox/#install

Any ideas on what I am doing wrong or how I can fix this build error?

**Comment by caxelrud** [comment]
I am having the same problem. The difference is that I installed mono from source to /usr (so the executables are in /usr/bin). I use: 
> $ export PKG_CONFIG_PATH=/usr/lib/pkgconfig
>  $ echo $PKG_CONFIG_PATH
> /usr/lib/pkgconfig

I can see the folder /usr/lib/pkgconfig.
But when I use:
> $ ./autogen.sh --prefix /usr

The error is exactly the same as presented before this issue:
> checking whether make sets $(MAKE)... yes
> checking for pkg-config... /usr/bin/pkg-config
> configure: "pkg-config: /usr/bin/pkg-config"
> configure: "PKG_CONFIG_LIBDIR: "
> configure: error: "You need mono 3.0"

**Comment by knocte** [comment]
> $ ./autogen.sh --prefix /usr

Mmm, I've always used "=" instead of a space here: `--prefix=/usr`. Maybe it's the same but can't hurt to test.

**Comment by caxelrud** [comment]
I realized that mono is actually installed at /mono (/<root>/mono). The error is gone but now I got another error during compilation, so I will open a new issue.
