### ISSUE TITLE
Offline Documentation

### ISSUE THREAD

**Issue by archaeron** [fsharp/fsharp#320]
Hello

is there a way to download the F# documentation?
(http://msdn.microsoft.com/en-us/library/dd233154.aspx)

I'd like to integrate it into Dash (http://kapeli.com/dash)

Is this possible?

Thank you very much

**Comment by gitfoxi** [comment]
+1

**Comment by dsyme** [comment]
You can now get the source of the MSDN Visual F# docs here : https://github.com/Microsoft/visualfsharpdocs.

**Comment by gitfoxi** [comment]
Thanks @dsyme

**Comment by gabehollombe-aws** [comment]
There's also the F# guide, available as a PDF download on this page: https://docs.microsoft.com/en-us/dotnet/fsharp/index  (current design shows it as a link in the lower-right)
