### ISSUE TITLE
MSBuildExtensionsPath32 mismatch between mono and fsharp when using homebrew formulas 

### ISSUE THREAD

**Issue by beurdouche** [fsharp/fsharp#328]
Mono xbuild extensions path:
/usr/local/Cellar/mono/3.6.0/lib/mono/xbuild

FSharp xbuild extension path (should be the same as mono as for visual studio):
/usr/local/Cellar/fsharp/3.1.1.25/lib/mono/xbuild

Since fsharp formula has mono as dependency it could symlink objects from fsharp dir to mono dir...
Note also that mono extension path only contains extensions up to v11.0, while FSharp extensions are for v12.0

**Comment by haf** [comment]
This should be fixed with https://github.com/Homebrew/homebrew/pull/36651 - but I'm opening https://github.com/fsharp/fsharp/issues/378 to finish it up.

**Comment by dsyme** [comment]
Closing this since the remainder is covered by #378 by the sounds of it
