### ISSUE TITLE
Embed tag in version string

### ISSUE THREAD

**Issue by rneatherway** [fsharp/fsharp#337]
It doesn't seem easy to tell what version of F# you have installed. There isn't a `--version` option, and the banner is just:

```
F# Compiler for F# 3.1 (Open Source Edition)
```

It would be good to have the tag in this banner at the least, preferably --version. A significant use case is to allow it to be printed in CI builds along with the mono version. Once Xamarin packages are being used for CI builds on Linux it gets difficult to work out what build of F# is in there.

**Comment by rneatherway** [comment]
Ah, I hadn't seen your PR. I have written there supporting the case for its inclusion in at least some form.

**Comment by dsyme** [comment]
It would be great to have a PR for this, to this repo if necessary.

**Comment by rneatherway** [comment]
Enrico has submitted it twice, once here previously, and he was then asked to switch it to codeplex, where it was declined.

**Comment by latkin** [comment]
I agree that having this information is useful for official releases - it's simple to check what version you are using, or to tell someone else the same.

Visual F# already embeds the version in the banner for official builds:

![image](https://cloud.githubusercontent.com/assets/5943573/6787000/f352d4a4-d14c-11e4-8483-3f4f9869e283.png)

It would make sense if the open edition did something similar.  That's a contribution to this repo.

**Comment by dsyme** [comment]
A decision has been made not to include this flag in the Visual F# Tools compiler shipped by Microsoft. See https://github.com/Microsoft/visualfsharp/pull/764#issuecomment-162613480

I'm OK with respecting that decision and keeping the flags consistent across versions.

**Comment by dsyme** [comment]
(However, we could still adjust the version string printed by the F# open edition to include the version tag, as originally proposed here, so reopening to cover that)

**Comment by enricosada** [comment]
Let's add the info to logo instead of `--version`

I think

`F# Compiler 4.3.1.0 (2014-09-05 fd84301) FSF`

FSF or fsharp foundation or fsharp.org is ok? I think git sha help a lot, but need a bit of work so i am asking before implement it

**Comment by ReedCopsey** [comment]
It should be either "FSSF", "fsharp.org", or "F# Software Foundation" - I suspect the latter might cause issues if the "#" is problematic.

My preference would be to use "fsharp.org".

**Comment by KevinRansom** [comment]
Please submit any change in the version to fsharp/fsharp.  This repo will maintain version info with it's historic format, and consistent in format with other managed languages.

**Comment by enricosada** [comment]
Yes, for that i tried first to add `--version` , more standard ( in the big world outside Microsoft ) and changing the logo was going to be a dead end in VisualFSharp , so i tried first a cross repo solution (less diff, less maintenance, more features) but if it's going only in this repo no problem
