### ISSUE TITLE
 Autogenerated gethashcode causes too many collisions

### ISSUE THREAD

**Issue by hodzanassredin** [fsharp/fsharp#343]
We had a very big troubles with collisions rate in autogenerated gethashcode function. Sample is here https://gist.github.com/hodzanassredin/90d45c5c6f8d7eb7fbef

//good keys
//struct custom(copy of standard tuple gethhashcode) 1.506934 sec 0.000000 collisions
//struct auto 4.832881 sec 0.776863 collisions
//struct auto explicit 3.166931 sec 0.776863 collisions
//bad keys
//struct custom(copy of standard tuple gethhashcode) 3.631251 sec 0.061893 collisions
//struct auto 10.340693 sec 0.777034 collisions
//struct auto explicit 8.893612 sec 0.777034 collisions

**Comment by Neftedollar** [comment]
Hi! Is this problem exist now?

**Comment by Neftedollar** [comment]
@dsyme Is this problem exist now?
