### ISSUE TITLE
When using F# Tupled functions dont have correct debug display or locals

### ISSUE THREAD

**Issue by DavidKarlas** [fsharp/fsharp#369]
Bug reported in XS also reproducible in VS as debugger bug I came to conclusion it's compiler bug... See comment 3 for more details.
https://bugzilla.xamarin.com/show_bug.cgi?id=21537

C#>F#, couldn't resist... :heart: ya all

**Comment by latkin** [comment]
Can you please open this at http://visualfsharp.codeplex.com/workitem/list/basic ? This is a general bug in the compiler, so that's the appropriate repo to file the bug.

This is definitely a bug, but FWIW if you single-step a few times (through invisible code...) the identifiers resolve correctly.

**Comment by enricosada** [comment]
moved to visualfsharp repo, can close
