### ISSUE TITLE
Seq.item fails compilation with "This construct is deprecated. please use Seq.item"

### ISSUE THREAD

**Issue by Andrea** [fsharp/fsharp#375]
Verified this bug on both latest pre-release and previous one

![screenshot 2](https://cloud.githubusercontent.com/assets/3103/5946566/b72467b0-a72e-11e4-9827-e3c2e1b89945.png)

Same error occurs for Seq.nth.

The implementation of Seq.item doesn't seem to be available in Seq. However according to [this](https://visualfsharp.codeplex.com/wikipage?title=Status) it looks like it should 

I am testing a little bit more will update this issue when I know more

**Comment by dungpa** [comment]
@Andrea Please move this to https://github.com/Microsoft/visualfsharp/issues :-)

**Comment by latkin** [comment]
Whoops.  Can you please open this at https://github.com/Microsoft/visualfsharp/ ?

`item` should be replacing `nth`, it is a mistake that `item` got marked Obsolete. See [here](https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/ListSeqArrayAdditions.md)

Culprit [here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/FSharp.Core/seq.fsi#L570)

BTW I would not think this is an error, just a warning. Do you have "warnings as errors" enabled?

**Comment by Andrea** [comment]
Done :D
