### ISSUE TITLE
Remote FSI

### ISSUE THREAD

**Issue by ProTip** [fsharp/fsharp#377]
Hello,

I'm not really sure where to direct this feature request as it's a mix of an FSI and VS/Xamarin/etc.  With the cross-platforming of CoreCLR moving full steam ahead some are starting to think about remote debugging capabilities.  I think it would be great if we could also attach our IDE's to a remote FSI instance.  Coupled with remote debugging this could allow for pretty seamless cross-platform development using VM's .

**Comment by brodyberg** [comment]
Maybe uservoice? https://visualstudio.uservoice.com/forums/121579-visual-studio/category/30935-languages-f-tools

**Comment by dsyme** [comment]
I agree this would be a great feature - and I actually think it wouldn't be very hard to implement.

This belongs in the Visual F# Tools repo, see the contributing guidelines for that repo and please consider submitting a prototype - people would be interested.  Some relevant code is here: https://github.com/Microsoft/visualfsharp/blob/fsharp4/vsintegration/src/vs/FsPkgs/FSharp.VS.FSI/sessions.fs
