### ISSUE TITLE
Linking .Targets files with homebrew => '127 not found'

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#378]
```
/usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/Microsoft.FSharp.Targets: 
error : Error executing tool '/usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/fsc.exe':
ApplicationName='/usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/fsc.exe', 
CommandLine='-o:obj/Debug/logibit.sqlite.dll -g --debug... [snip] ...ropyva- Sqlite.fs ', 
CurrentDirectory='/Users/henrik.feldt/dev/extra.sqlite', 
Native error= Cannot find the specified file
```

Repro: `brew install fsharp` with this https://github.com/Homebrew/homebrew/pull/36651 PR merged, or using its code, and then compiling a F# library/console app.

I'm using a Paket dependency for `FSharp.Core` in this `fsproj` file.

The OS X homebrew mono package doesn't add FSharp.Core to the GAC.

Just calling `mono fsc.exe` with the same arguments works fine.

Adding further debugging to the command doesn't help, because it works fine on its own.

Adding /verbosity:debug to the `xbuild myproj.fsproj` command doesn't help in any particular way.

I tried dtracing it, but that  (finding the xbuild's fsc pid when it's running fsc) eluded me a for a while, so I'm giving up on that right now.

**Comment by dsyme** [comment]
Anyone know what's up here?!

**Comment by dsyme** [comment]
@haf - any thoughts on what to do here?

**Comment by haf** [comment]
It would take a couple of hours to sort out; I would start by looking at how the fsharp and mono repos install things and then compare that to how homebrew does it. Any difference I would fix inside the Formula in homebrew.

**Comment by haf** [comment]
As for the specific error; file not found -- one could possibly find the setting inside the .targets file for F# which controls verbosity and simply print all commands that it tries to run.

**Comment by dsyme** [comment]
So is this a bug for this repo or for the homebrew formula?  Could it be related to casing of Microsoft.FSharp.Targets v. Microsoft.FSharp.targets?

**Comment by haf** [comment]
Getting information on how to debug the F# target with increased logging verbosity and a place to discuss the installation of the software that this repository holds, is why I filed this ticket.

**Comment by dsyme** [comment]
I see, thanks!

**Comment by haf** [comment]
If there a way to increase verbosity in the targets file?

**Comment by dsyme** [comment]
Could you share a full log of the current state of the homebrew build? I need to understand where the error happens in the build process.

**Comment by haf** [comment]
It's not a problem building F#, it's a problem using the .Targets files that F# provides. So you can create the simples console project from the homebrew formula and it won't compile.

**Comment by dsyme** [comment]
If you have the hombrew log that would still be useful as it will indicate the --prefix used when building and installing fsharp (which is probably the problem - the --prefix must be the same as the mono --prefix)

**Comment by haf** [comment]
Ok, let me see what I can get the next few weeks

**Comment by 7sharp9** [comment]
If brew working with the latest mono and F#?  I get a:
```
System.InvalidProgramException: Invalid IL code in System.Collections.Generic.Stack`1:System.Collections.Generic.IEnumerable<T>.GetEnumerator (): IL_0000: ret
```

**Comment by dsyme** [comment]
That's odd, I haven't seen any problem. Looks very likely to be a Mono bug though.

**Comment by 7sharp9** [comment]
I think its a mismatch where its trying to use .Net4.0 assemblies that don't exist anymore, I must have a mangles installation somewhere.

**Comment by dsyme** [comment]
Should [this line be updated to tag 3.1.1.32](https://github.com/Homebrew/homebrew/pull/36651/files#diff-cb774ca6cc7f4656e3b0864484a89961R5) ???

**Comment by 7sharp9** [comment]
I think so, there were install fixes for mono4 since the one in brew

**Comment by dsyme** [comment]
Can someone submit the PR to homebrew for that please?

**Comment by 7sharp9** [comment]
Done: https://github.com/Homebrew/homebrew/pull/39391

**Comment by dsyme** [comment]
F# homebrew has been updated to 3.1.2.2 tag, I'm closing this since I believe that corrects the problem, let us know if the problem reoccurs.
