### ISSUE TITLE
R E A D T H i S !!!!! xD

### ISSUE THREAD

**Issue by Nhie01** [fsharp/fsharp#380]
Hello everyone. Im having a little trouble about installing Visual F#. Can you kindly help me to fix it? I need an installer of it exclusively for Windows XP. Contact me via yahoomail (ellajeanorongan@yahoo.com) or via facebook (www.facebook.com/ellajeancesar or ellajeanorongan@yahoo.com). Thank you.

**Comment by smoothdeveloper** [comment]
I see two options to try out on http://fsharp.org/use/windows/

First make sure you have dotnet framework 4 installed

Option 6: Run already compiled F# code on servers
try to install this, despite it doesn't mention XP, worth a look:
http://www.microsoft.com/en-us/download/details.aspx?id=44011

Option 5: Build F# from source
I think this should be supported

**Comment by Nhie01** [comment]
Thanks. :)

**Comment by Nhie01** [comment]
Thank you Pal.

**Comment by Nhie01** [comment]
By the way. What do you think is the best programming language that i should learn to do? Cause im not the type of persons that want to program useless applications, my prof says that it is best to learn Web-Based application. Do you guys agree?
