### ISSUE TITLE
Is it possible to receive documentation about statically resolved type parameters?

### ISSUE THREAD

**Issue by GregRos** [fsharp/fsharp#392]
There is barely any information anywhere, including in the specification. There are no answers to questions such as,

1. How do static and regular type parameters work together?
2. What are the limitations of member invocation expressions? (e.g. generic type parameters in the methods)
3. How are overloads resolved?
4. How does using statically resolved type parameters in types work?
5. How exactly do the `or` and `and` keywords work when invoking/specifying member constraints?
6. How do inline instance members work?
7. In what scopes can you define inline functions?
8. Is it possible to have abstract/override inline members?

This is a very complex and powerful feature, and I'm sure a lot of time has gone into implementing it, but using it is mostly trial and error.

**Comment by dsyme** [comment]
Hi @GregRos 

Could you move this to be a proposal at http://fslang.uservoice.com please and add a cross-link to this thread? Thanks.  

We don't track language spec issues here, indeed there's actually no specific github site currently used to track issues with the F# Language Spec, so the UserVoice site is the right place for now to put requests (and it also allows people to vote on them).  I'm still trying to work out the best workflow for the F# language spec - moving the whole thing to markdown would be a huge job unfortunately.

thanks
don
