### ISSUE TITLE
Optimization error in Set's Intersection, Difference

### ISSUE THREAD

**Issue by GregRos** [fsharp/fsharp#398]
It appears that whatever algorithm you use for Intersection, you don't check which is the larger set before you apply it, giving different performance depending on which of the two sets is the larger. I discovered this while benchmarking some collections against FSharp.Set. Union seems unaffected.

I ran 1000 iterations of the set-theoretic operations with one set containing 10,000 elements while the other containing 1 element, 20 times and then averaged out. The benchmarking was very careful and there was practically no noise. I ran it several times to confirm and got very similar results.

There is also a similar issue with Except, and one with Difference, though those might be harder to iron out. Over all the performance of the data structure is pretty good.

![image](https://cloud.githubusercontent.com/assets/1788329/6773102/da4cd758-d114-11e4-9f9d-ce0206f14566.png)

Oh, if you are interested, here some detailed results of benchmarks between my collections, FSharp's, and System.Collections.Immutable. Note that these were performed under specific conditions (see the log file for detailed information). Under different conditions the results are different. I'm not going to link to my library here because it would seem like advertising. 
https://www.dropbox.com/s/apsrmyrnt25okug/benchmark070.rar?dl=0

**Comment by dsyme** [comment]
Hi @GregRos 

Could you submit an issue (and, preferably, a PR) for this to https://github.com/Microsoft/visualfsharp?  I agree it makes sense to address this.

Thanks
don

**Comment by GregRos** [comment]
I forgot that the operation called `Difference` in the table is actually symmetric difference that `Set` doesn't support, so I implemented naively for comparison. The operation appearing as `Except` is actually `Set.difference`. 

Is `Set.difference` part of the scope of the fix or just the intersection? I looked at the code and the error is pretty similar in character:

        let rec diffAux comparer m acc = 
            match m with 
            | SetNode(k,l,r,_) -> diffAux comparer l (diffAux comparer r (remove comparer k acc))
            | SetOne(k) -> remove comparer k acc
            | SetEmpty -> acc    

It doesn't check if `acc` is empty. 

One question though. There is something puzzling me about the set implementation, and maybe you could spare a second to answer it. These are some benchmarks:
![075 setlike setsingle](https://cloud.githubusercontent.com/assets/1788329/6792007/68c60246-d1bc-11e4-8e15-7cef837e61ce.png)

Do you have any idea how can `Contains` be so fast for `FSharp.Set`? The key is a string, and as far as I can see the code uses `String.CompareOrdinal` to compare them, but it's miles ahead of the other comparison-based sets.

**Comment by dsyme** [comment]
Hi @GregRos - now you have the issue at https://github.com/Microsoft/visualfsharp/issues/324 I'll close the issue here.  Did you mean to add the comment above to that copy of the issue?

Thanks
