### ISSUE TITLE
Escaped unicode characters are incorrectly decoded

### ISSUE THREAD

**Issue by fsoikin** [fsharp/fsharp#399]
In strings with espaced Unicode characters (i.e. `"\uABCD"`), characters in the range from `D800` to `DFFF` always get encoded as `FFFD` (65533 decimal).

Here's from the F# Interactive:

```
    > "\uD500".[0] |> uint16 ;;
    val it : uint16 = 54528us
    > "\uD700".[0] |> uint16 ;;
    val it : uint16 = 55040us
    > "\uD800".[0] |> uint16 ;;
    val it : uint16 = 65533us
    > "\uD900".[0] |> uint16 ;;
    val it : uint16 = 65533us
    > "\uE000".[0] |> uint16 ;;
    val it : uint16 = 57344us
```

Here's an SO question that prompted me to fiddle with it: http://stackoverflow.com/questions/29359408/surrogate-pair-detection-fails

**Comment by dsyme** [comment]
Hi @fsoikin  - 

Could you open this bug at http://github.com/Microsoft/visualfsharp?  If it gets fixed there first we'll then integrate it into this edition.

Thanks, Don

**Comment by fsoikin** [comment]
@dsyme done: https://github.com/Microsoft/visualfsharp/issues/338

**Comment by dsyme** [comment]
Closing here as the discussion and fix is underway at https://github.com/Microsoft/visualfsharp/issues/338
