### ISSUE TITLE
F# compiler becomes abnormally slow

### ISSUE THREAD

**Issue by arcturius** [fsharp/fsharp#400]
F# compiler becomes abnormally slow when it compiles a code based on generic overloads. Libraries that are based on this feature of the language are victimized by this bug. e.g. FsControl, FSharpPlus.  

Example code to reproduce the bug: https://gist.github.com/gmpl/5c2fae2d6e6a115d729e

In addition to that F# Intellisense stops working normally, VS consumes CPU and memory uncontrollably, VS hangs and stops responding when requested to quit. 

Example code to reproduce the bug: 
https://github.com/gmpl/FSharpPlus/blob/master/FSharpPlus/Samples/Learn%20You%20a%20Haskell.fsx

Used environment: VS 2013 Update 4, F# 3.1, .NET 4.5, Win 8.1 x64

**Comment by dsyme** [comment]
This is covered by this issue: https://github.com/Microsoft/visualfsharp/issues/343.

**Comment by dsyme** [comment]
Closing this copy of the issue since any updated from a resolution of  https://github.com/Microsoft/visualfsharp/issues/343 will eventually be integrated here
