### ISSUE TITLE
Quoted function name clashes with DU Pattern ID

### ISSUE THREAD

**Issue by xenocons** [fsharp/fsharp#402]
Hello,

I am not sure if this is a bug, or an issue localised to me, or perhaps it is meant to be this way (or I am just doing something stupid).

```
    let ``TEST`` = id

    type XXXX = 
        | A
        | TEST
    
    let lookup = function   
        | A -> Some id
        | TEST -> Some ``TEST``
```

On the last line, the error is: error FS0001: This expression was expected to have type
    'a -> 'a    
but here has type
    XXXX    

I would have expected this to compile, but it seems that the DU XXXX is overriding the function \`\`TEST\`\`, is this normal and expected?
Edit: tried to update function name

**Comment by dsyme** [comment]
Hi @xenocons - Language issues should be logged at http://github.com/Microsoft/visualfsharp.  Any fixes/updates will then be integrated into this repo.

**Comment by dsyme** [comment]
(closing this - see above comment)

**Comment by xenocons** [comment]
thanks, will enter it in on the other site, it is a bit messy knowing where to post different types of issues.
