### ISSUE TITLE
Why does FSharp.Core 3.3.1.0 reference .NET Framework assemblies?

### ISSUE THREAD

**Issue by eggapauli** [fsharp/fsharp#405]
`%programfiles(x86)%\Reference Assemblies\Microsoft\FSharp\.NETCore\3.3.1.0\FSharp.Core.dll` is the version of FSharp.Core built against .NET Core, right? Why does it contain a reference to some dll's built against .NET Framework (e.g. it has a reference to System.Collections v4.0.0.0 which references mscorlib)? Shouldn't it reference the .NET core version of System.Collections (i.e. System.Collections v4.0.10-beta-22809)?

**Comment by latkin** [comment]
You are getting different ".NET cores" mixed up, which is easy to do.

3.3.1.0 shipped with VS 2013, and targets .NET portable profile 7.  Profile 7 and some others target ".NETCore" which is totally independent of the new, open-source, cross-platform ".NET Core" that is getting press today.  Yes, the naming is terrible.

See http://blog.stephencleary.com/2012/05/framework-profiles-in-net.html, search for "netcore."

**Comment by eggapauli** [comment]
Ahh I see, I got confused with that, thanks for clarifying that. Is there or will there be a version of FSharp.Core that targets the cross-platform .NET Core?

**Comment by cdrnet** [comment]
Apparently the PCL builds for profiles 78 and 259 included in the NuGet package [should work](https://github.com/dotnet/corefx/issues/973#issuecomment-75852041) with .NET Core (the new one).

**Comment by eggapauli** [comment]
Oh perfect, thanks. I'll try those builds.

**Comment by eggapauli** [comment]
I tried both profiles and basically they work fine, but there are some methods missing, for example `printf`. Is there a replacement somewhere?

**Comment by 7sharp9** [comment]
Methods are normally missing because those features are not present on the target platform, like console output.

**Comment by eggapauli** [comment]
Ok I see, thanks. I also get an error when calling `sprintf`:

    Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies. The system cannot find the file specified.
        at Microsoft.FSharp.Core.PrintfImpl.PrintfBuilderStack..ctor()
        at Microsoft.FSharp.Core.PrintfImpl.PrintfBuilder`3..ctor()
        at Microsoft.FSharp.Core.PrintfImpl.Cache`4.generate(String fmt)
        at Microsoft.FSharp.Core.PrintfImpl.f@4277-44[T,TState,TResidue,TResult](String key, Unit unitVar0)
        at Microsoft.FSharp.Core.PrintfImpl.Cache`4.get(String key)
        at Microsoft.FSharp.Core.PrintfImpl.Cache`4.Get(PrintfFormat`4 key)
        at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThen[TResult,T](FSharpFunc`2 continutation, PrintfFormat`4 format)
        at Program.Help.print()
        at Program.main(String[] args)

What am I doing wrong?

**Comment by 7sharp9** [comment]
What were the arguments to sprinf?

**Comment by eggapauli** [comment]
e.g. `let foo = sprintf "bar"`

**Comment by 7sharp9** [comment]
I suspect its a bug then, was this profile 259 or 78?

**Comment by eggapauli** [comment]
78, I can also try with 259, just a moment.

**Comment by 7sharp9** [comment]
259 will be more restrictive than 78, 7 is the least restrictive.

**Comment by eggapauli** [comment]
It seems to fail with all of the profiles. Or I'm doing something wrong.

**Comment by 7sharp9** [comment]
Are you referencing an mscorlib too?

**Comment by eggapauli** [comment]
I build it with System.Runtime.4.0.20-beta-22703 which is also in the same directory when executing.

**Comment by 7sharp9** [comment]
I suspect its that, that is the issue, I suspect the pcl profile is trying to find the older mscorlib or system dll

**Comment by eggapauli** [comment]
Ahh no wait a minute, there is a mscorlib 4.6 in the directory. This seems to be not quite right.

**Comment by 7sharp9** [comment]
sprintf works with the portable profiles, I just checked to be sure, souds like you gave a mismatch of different mscorlib/fsharp.cores

**Comment by eggapauli** [comment]
Ahh ok, thanks for checking that. I'll continue playing around with it, thanks for your help.
