### ISSUE TITLE
Bundle the compiler and tools in a Nuget

### ISSUE THREAD

**Issue by granicz** [fsharp/fsharp#408]
As it recently came up, it would be often useful in various automation scenarios (Azure deployments, etc.) to fetch and use the compiler tools (`fsc.exe` and `fsi.exe`) without requiring a previous F# installation on the executing machine.

**Comment by dsyme** [comment]
I think it's mostly a matter of someone submitting a PR with a nuget package spec like [these ones for the FSharp.Core package](https://github.com/fsharp/fsharp/blob/master/FSharp.Core.Nuget), and then the package getting pushed.  I don't know of any real technical reason why the contents of this repo shouldn't be available in this way, given that they are already part of Linux packages, Xamarin etc.

**Comment by forki** [comment]
I look at this, but the FSharp.Core packages only redistribute the already signed and commited dlls.

**Comment by dsyme** [comment]
They also do MonoAndroid, MonoTouch, Xamarin iOS https://github.com/fsharp/fsharp/blob/master/FSharp.Core.Nuget/FSharp.Core.3.1.nuspec#L64

**Comment by forki** [comment]
see https://github.com/fsharp/fsharp/pull/409
