### ISSUE TITLE
Compile quotations into IL

### ISSUE THREAD

**Issue by GabrieleCocco** [fsharp/fsharp#410]
After developing and profiling some projects involving repetitive evaluation of quotations, I found quotation evaluation to represent a bottleneck in several occasions. 
While doing my best to evaluate quotations ahead of time, at least partially, being able to compile quotations into IL should boost quotation evaluation. 
I guess this is particularly true when quotations contain lambdas. The most common case in my projects is having a quoted lambda that I partially transform and then evaluate. The result is the applied multiple times to different args.
Currently, evaluating a quoted lambda results in converting the body to LINQ expression and convert the resulting LINQ lambda to an F# function (by wrapping/proxying the call to the LINQ lambda, according to the ToFSharpFunction method source).
I'd suggest to provide a way, again especially for lambdas/functions, to compile F# quotations to IL. In case of functions/lambdas I see in packing and returning a dynamic method, using emit to jit the body, a feasible way.
Any feedback/opinion is appreciated.

**Comment by rojepp** [comment]
I'm sure there are optimizations to be had, especially when no locals are being captured. This was the bottleneck for an experimental lib of mine: https://bitbucket.org/rojepp/reflenses/overview
I'm not sure what you are saying about LINQ? Do you mean conversion between `FsharpFunc` and `Func`?

**Comment by eiriktsarpalis** [comment]
A few months ago I started this project:

https://github.com/eiriktsarpalis/QuotationCompiler

It's a small library that runs on top of FSharp.Compiler.Service which
converts quotations into F# ASTs. This in turn yields IL optimized by the
compiler itself. It is a somewhat incomplete project but my intention is to
someday incorporate this to FSharp.Compiler.Service.

Perhaps this is similar to what you are looking for?

**Comment by GabrieleCocco** [comment]
Definitely something close to that.

**Comment by dsyme** [comment]
Also take a look at [Unquote](https://code.google.com/p/unquote/) which contains a fast quotation compiler/evaluator, and the recent improvements to [FSharp.Quotations.Evaluator](https://github.com/fsprojects/FSharp.Quotations.Evaluator)

**Comment by dsyme** [comment]
I'll close this as it doesn't belong in this repro, and the discussion has been quiet for a while
