### ISSUE TITLE
Characters don't show up in http://www.tryfsharp.org/Create

### ISSUE THREAD

**Issue by brodyberg** [fsharp/fsharp#413]
I hardly think this is the right spot for this, please redirect: 

On OS X 10.10.2 (14C109), when using Safari Version 8.0.3 (10600.3.18) at tryfsharp.org/Create, no text that I type in the 'script window' actually appears when I type. However, after typing, and then pressing 'run', what I typed appears in the 'output window'

Thanks, Brody

**Comment by dsyme** [comment]
Hi @brodyberg - Yes, not the right spot.  I think use TryFSharp AT microsoft.com.
