### ISSUE TITLE
Custom attributes on a method return type are not reflected when a tuple type annotation is not surrounded by parentheses

### ISSUE THREAD

**Issue by bbenoist** [fsharp/fsharp#414]
Hello,

After hours struggling to retrieve the values of some custom attributes assigned to an F# method return type, I have found an unexpected behavior and would like to know why it did not worked as I thought.

Suppose that you have an F# method which returns a tuple value:

```fsharp
type MyType =
    static member DoSomething () : string * string = ("Foo", "Bar")
```

Then, you code a custom attribute containing a string describing each tuple field:

```fsharp
[<AttributeUsage(AttributeTargets.ReturnValue, AllowMultiple = true)>] 
type TupleFieldDescriptionAttribute(description:string) =
    inherit Attribute()
    member x.Description = description
```

If you apply it to the `DoSomething` method:

```fsharp
type MyType =
    static member DoSomething () :
        [<TupleFieldDescription("A string containing Foo.")>]
        [<TupleFieldDescription("A string containing Bar.")>]
        string * string =
            ("Foo", "Bar")
```

The following reflection will not return anything:

```fsharp
let methodInfo = typeof<MyType>.GetMethod("DoSomething")
methodInfo.ReturnParameter.GetCustomAttributes(typeof<ReturnInfoAttribute>, false)
```

Whereas it works correctly when the explicit tuple specification is surrounded by parentheses:

```fsharp
type MyType =
    static member DoSomething () :
        [<TupleFieldDescription("A string containing Foo.")>]
        [<TupleFieldDescription("A string containing Bar.")>]
        (string * string) =
            ("Foo", "Bar")
```

Does anyone knows why the first attempt does not returns the custom attributes ?

Full example of my problem ([try it in your web browser](https://dotnetfiddle.net/lPhWrt)):

```fsharp
open System

[<AttributeUsage(AttributeTargets.ReturnValue, AllowMultiple = true, Inherited = false)>]
type ReturnInfoAttribute(info:string) =
    inherit Attribute()
    member x.Info = info
    
type Simple =
    static member Format name :
        [<ReturnInfo("A 'Hello <name>!' string.")>]
        string =
            "Hello " + name + "!"
            
type Tuple =
    static member Format name :
        [<ReturnInfo("A 'Hello <name>!' string.")>]
        [<ReturnInfo("A 'Goodbye <name>!' string.")>]
        (string * string) =
            ("Hello " + name + "!", "Goodbye " + name + "!")

type TupleNoParenthesis =
    static member Format name :
        [<ReturnInfo("A 'Hello <name>!' string.")>]
        [<ReturnInfo("A 'Goodbye <name>!' string.")>]
        string * string =
            ("Hello " + name + "!", "Goodbye " + name + "!")

[| typeof<Simple>; typeof<Tuple>; typeof<TupleNoParenthesis> |]
|> Array.map (fun t ->
        printfn "--- %s ---" t.Name
        t.GetMethod("Format").ReturnParameter.GetCustomAttributes(typeof<ReturnInfoAttribute>, false)
        |> Array.map (fun attr -> (attr :?> ReturnInfoAttribute).Info |> printfn "%s")
    )
```

**Comment by latkin** [comment]
Note that you need `[<AttributeUsage(AttributeTargets.ReturnValue, AllowMultiple = true)>]` on your first sample attribute.

This looks like a parser bug.  Maybe the parens are required, but if so you should get an error telling you something's wrong.  As it stands your attributes are just silently ignored - they don't appear anywhere in the generated IL.

**Comment by latkin** [comment]
Can you please move this to https://github.com/Microsoft/visualfsharp?

**Comment by bbenoist** [comment]
@latkin 

Thank you for the quick reply!

> Note that you need  `[<AttributeUsage(AttributeTargets.ReturnValue, AllowMultiple = true)>]`  on your first sample attribute.

Fixed. Thanks for correcting me :+1: 

> This looks like a parser bug. Maybe the parens are required, but if so you should get an error telling you something's wrong.

That's what my (quick) reading of the [F# specifications](http://fsharp.org/specs/language-spec/3.0/FSharpSpec-3.0-final.pdf) led me to think but I'm still a newcomer in this language :confused: 

> As it stands your attributes are just silently ignored - they don't appear anywhere in the generated IL.

The generated IL displayed by dotnetfiddle does not seems to include the attributes in any of the cases presented here. I also tested with [this C# code](https://dotnetfiddle.net/Lz3bU6) and got the same results. Where is it supposed to be?

> Can you please move this to https://github.com/Microsoft/visualfsharp?

OK, feel free to close this issue if it's not relevant anymore...

**Comment by bbenoist** [comment]
Moved to the correct repository: https://github.com/Microsoft/visualfsharp/issues/462
