### ISSUE TITLE
Exception raised during pretty printing when using Lazy List with Cons and Nil. Works with "int" but not with "string" (F#) 

### ISSUE THREAD

**Issue by chamons** [fsharp/fsharp#417]
From: https://bugzilla.xamarin.com/show_bug.cgi?id=30245 but this appears to be an F# bug:

--------------------------------------------------------------------------------
Mono version:
--------------------------------------------------------------------------------
[ mon@mbai7 ~ ] mono --version
Mono JIT compiler version 4.0.0 ((detached/d136b79 Mon Apr 13 14:40:59 EDT
2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors.
www.mono-project.com
    TLS:           normal
    SIGSEGV:       altstack
    Notification:  kqueue
    Architecture:  x86
    Disabled:      none
    Misc:          softdebug 
    LLVM:          yes(3.6.0svn-mono-(detached/a173357)
    GC:            sgen
--------------------------------------------------------------------------------
FSI version
--------------------------------------------------------------------------------
[ mon@mbai7 ~ ] fsi

F# Interactive for F# 3.1 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> 
--------------------------------------------------------------------------------
Issue: Following code works on a PC with Windows and .NET 4.5.2
--------------------------------------------------------------------------------
> type 'a ListLazy = Cons of 'a * 'a ListLazy Lazy | Nil;;

type 'a ListLazy =
  | Cons of 'a * Lazy<'a ListLazy>
  | Nil

> Cons(42,lazy Nil);;                          
val it : int ListLazy = Cons (42,Value is not created.)

> Cons("42",lazy Nil);;

Exception raised during pretty printing.
Please report this so it can be fixed.
Trace: System.InvalidCastException: Cannot cast from source type to destination
type.
  at (wrapper castclass) object:__castclass_with_cache (object,intptr,intptr)
  at
Microsoft.FSharp.Compiler.Interactive.Shell+Utilities+AnyToLayoutSpecialization`1[FSI_0002+ListLazy`1[System.String]].Microsoft-FSharp-Compiler-Interactive-Shell-Utilities-IAnyToLayoutCall-AnyToLayout
(Internal.Utilities.StructuredFormat.FormatOptions options, System.Object o)
[0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Compiler.Interactive.Shell+FsiValuePrinter.PrintValue
(Microsoft.FSharp.Compiler.Interactive.FsiValuePrinterMode printMode,
Internal.Utilities.StructuredFormat.FormatOptions opts, System.Object x,
System.Type ty) [0x00000] in <filename unknown>:0 
val it : string ListLazy = 
> 
--------------------------------------------------------------------------------

**Comment by dsyme** [comment]
@chamons  - This looks like the same issue as #423 - could you add a Mono bug at https://bugzilla.xamarin.com/ please and paste the link here? thanks

**Comment by dsyme** [comment]
@chamons - I'm pretty sure this is a Mono bug as it works OK on Windows, and I'm certain it's worked on previous releases of F# + Mono.  It would bee good to identify precisely which cast is failing in which condition so we can get more info to the Mono team.

Could you reactivate the Mono bug with the information that it works OK on Windows? Thanks

**Comment by dsyme** [comment]
Note related bugs #418 , #426 , #423 all of which seem to be casting exceptions on recent versions of Mono - perhaps only when interactive (dynamically generated) code is involved.

**Comment by chamons** [comment]
I reopened that bug and pushed to mono / general desktop for them to look at.

**Comment by dsyme** [comment]
According to the comment by @obadz on the bugzilla bug,  this was fixed by mono/mono#1654
