### ISSUE TITLE
F# should be able to await non-generic Task

### ISSUE THREAD

**Issue by svick** [fsharp/fsharp#421]
`Control.Async` contains the method `AwaitTask` that converts `Task<'T>` to `Async<'T>`. But there is no similar method for the widely-used non-generic `Task`. There are [some workarounds](http://stackoverflow.com/q/8022909/41071), but I think this is so common that a proper solution is warranted.

I propose adding the following method to `Contol.Async`:

```f#
static member AwaitVoidTask: task: Task -> Async<unit>
```

One caveat of this method is that it accepts any `Task<'T>` too (since it inherits from `Task`). Hopefully, the "void" in the name of the method (or should it be "unit"?) will make it clear that the returned `Async<unit>` won't contain the result in such cases.

**Comment by 7sharp9** [comment]
This is already in F#4, so its just a matter of waiting for the release

**Comment by svick** [comment]
Oh, I just assumed that the master branch contains the newest code. Sorry for not checking more carefully.
