### ISSUE TITLE
Possible inconsistency in type unification

### ISSUE THREAD

**Issue by optimusbrine** [fsharp/fsharp#422]
let foo (a: seq<seq<'a>>) = a
    let someCharArAr()        = [|[| 's' |]|]
    let quack                 = [|[| 's' |]|]
    let moo : char [][]       = quack
 
    foo [|[| 's' |]|]  |> ignore // OK
 
    foo (someCharArAr()) |> ignore // Fails
    foo moo   |> ignore // Fails
    foo quack |> ignore // Fails

I would think that if `foo [|[| 's' |]|]` typechecked, that the other applications of `foo` would typecheck too, but they do not. Type checking for each of the others fails with:

    The type 'seq<'a>' does not match the type 'char []'

I have not tested whether or not this behavior is currently exhibited by version of the compiler in this repo (i have not had any success building from source). 

I am working with the version packaged with VS2015pre, fsi reports a version of '14.0.22810.0'

**Comment by latkin** [comment]
This does seem odd.  Can you please open it at https://github.com/microsoft/visualfsharp/issues - that's the repo where primary compiler development is done.

This repros in F# 3.0, so it does not seem to be a new bug in F# 4.0.

FWIW there is a simple workaround - use a [flexible type](https://msdn.microsoft.com/en-us/library/vstudio/dd233198(v=vs.140).aspx) in your function signature:

```fsharp
let foo (a: seq<#seq<'a>>) = a
let someCharArAr()        = [|[| 's' |]|]
let quack                 = [|[| 's' |]|]
let moo : char [][]       = quack

foo [|[| 's' |]|]  |> ignore // OK
foo (someCharArAr()) |> ignore // OK
foo moo   |> ignore // OK
foo quack |> ignore // OK
```
