### ISSUE TITLE
Why does the seq library use while instead of for?

### ISSUE THREAD

**Issue by pmwhite** [fsharp/fsharp#424]
I apologize if I'm doing this wrong.  This is my first involvement in any Github project, so I don't really know what I'm doing.

I asked this question on SO - http://stackoverflow.com/questions/30904613/why-does-fsharp-core-use-getenumerator-instead-of-for?noredirect=1#comment49867431_30904613.

The only reason I really got was that it might possibly be for performance.  

I'v been looking at the implementation of F# Seq methods - https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/seq.fs.

This gist - https://gist.github.com/pmwhite/2b0bad76f0726ae7205b#file-scanwithfor
has both the original code and one in which I replaced the while loop with a for loop.
My implementation definitely looks better, but the question is whether there is a difference in performance.

As was suggested in the SO comments, the IL generated by the for loop could be less efficient.
If this is so, that's weird, because the use of the while loop in this case seems to be exactly what a for loop is meant to replace.

I tried to look at the generated code with ILSpy.  The code generated is nearly the same.  It has just one variable extra (and it seems to be an intermediate variable).

It seems to me that either the loops should be changed to for loops.  If there are performance implications, that should be fixed so there aren't any(because there really shouldn't be any).

I don't know how important this is, so I apologize if it doesn't matter at all.

**Comment by dsyme** [comment]
IIRC it's largely historical - the state-machine compilation of sequence expressions came in F# 2.0, whereas the Seq library dates from 1.0.  Prior to that the "while" implementations were significantly faster.
