### ISSUE TITLE
Deriving an F# type from a C++/CLI class with modopt decoration creates non-loadable assembly

### ISSUE THREAD

**Issue by marklam** [fsharp/fsharp#425]
A C++/CLI abstract member function with modopt decoration (e.g. to note that a method was declared with a 32-bit long rather than 32-bit int) cannot be overridden in F#.
The C# compiler copies the modopt flags to its override, and so it works correctly. The F# compiler doesn't and so the assembly won't load.
If the member function was only virtual rather than abstract, the resulting F# assembly will load but only the base function will be called, not the F# override.
I've created a minimal demo solution here (there's a little extra info in the [Readme](https://github.com/marklam/modopt/blob/master/README.md) too.
https://github.com/marklam/modopt

I've tested this in F# 3 and 4RC with .net 4.5.2

**Comment by 7sharp9** [comment]
As this seems to be a compiler bug it should go to the https://github.com/Microsoft/visualfsharp repo rather than the OSS one which deals with xplat issues.

**Comment by marklam** [comment]
Ok. Will do.
