### ISSUE TITLE
Release updated FSharp.Core on nuget?

### ISSUE THREAD

**Issue by amazingant** [fsharp/fsharp#429]
Would be really helpful if an updated copy of the FSharp.Core package on nuget could get published with a "prerelease" package containing v4.4 for those of us targeting F# 4 :smiley:

Not sure who maintains it, but it mentions @forki and @ctaggart on the nuget page, @forki  suggested posting here.

**Comment by ctaggart** [comment]
I am the current maintainer. I would be happy to hand it off to the Visual F# team when the time is right. /cc @KevinRansom @latkin

**Comment by 7sharp9** [comment]
Theres several new xamarin FSharp.Core profiles that have been created too over the last few months, Im not sure which would be useful in the nuget.

**Comment by dsyme** [comment]
@7sharp9 - I think all of them should go in the nuget package

**Comment by 7sharp9** [comment]
@dsyme Theres a caveat with the mac full and mobile profiles, theres no way for nuget to differentiate them.  

@mward Can you remember the issue for Mac mobile/ full profiles in nuget?

**Comment by 7sharp9** [comment]
@mrward Can you remember the issue for Mac mobile/ full profiles in nuget?

**Comment by 7sharp9** [comment]
@dsyme Theres another one waiting in a PR too ...

**Comment by mrward** [comment]
A Xamarin.Mac project has three different types which you can switch between in the project options.

![image](https://cloud.githubusercontent.com/assets/372361/8429803/f9bb7700-1f22-11e5-9afb-73a1856d969d.png)

 1. Xamarin.Mac Mobile Framework => Target framework = Xamarin.Mac
 2. Xamarin.Mac .NET 4.5 Framework => Target framework = .NET 4.5
 3. Unsupported Framework => Target framework = .NET 4.5

The last two from NuGet's point of view look like normal .NET 4.5 projects due to the target framework.

The Xamarin.Mac .NET 4.5 Framework does not support the full .NET framework, for example, System.Configuration is missing.

I have ignored MonoMac (open source Mac framework) projects here which have the same problem since they have a target framework of .NET.

**Comment by ctaggart** [comment]
@7sharp9 @mrward Any chance you can test the NuGet in #433 and propose what changes should be made for 4.0.

**Comment by ctaggart** [comment]
Don and I got the 3.1 builds output to the project NuGet feed `https://ci.appveyor.com/nuget/fsgit-fsharp`. See https://github.com/fsharp/fsharp/pull/437#issuecomment-119375124 for details.

Once 4.0 code and binaries get merged into the 4.0 branch, we should be able to do it the same way.

**Comment by 7sharp9** [comment]
Quick question, if we have separate targets for MonoTouch and iOS why do we ship a single nuget target for both?

**Comment by ctaggart** [comment]
I'm in need of some assistance. I did a bunch of testing on Xamarin a few months ago and thought `portable-net45+monoandroid1+monotouch1+xamarinios1` was working. Should that work? Unfortunately, I think I hit a Paket bug with it https://github.com/fsprojects/Paket/issues/917.

**Comment by ctaggart** [comment]
Thanks for @forki's PR #454, it looks like we are pretty close on this. The latest builds from the AppVeyor project feed can be tried out. See the build history here:
https://ci.appveyor.com/project/fsgit/fsharp/history

Instructions for adding the feed are here:
https://github.com/fsharp/fsharp#nuget-feed-of-fsharpcore-and-fsharpcompilertools-packages

I suspect that @dsyme will tag a `4.0.0.1` soon.

**Comment by amazingant** [comment]
Many thanks @ctaggart, @7sharp9, and @forki! I'll start updating my projects to use build 251 and add the feed to my system nuget sources. :+1: :smile:

**Comment by dsyme** [comment]
Tagged 4.0.0.1. @ctaggart can you push the nuget packages and submit a PR to increment version numbers please? thx

**Comment by ctaggart** [comment]
Pushed to NuGet Gallery. Enjoy!
https://www.nuget.org/packages/FSharp.Core/4.0.0.1

@dsyme You want something that increments the [4th number of the version](https://github.com/fsharp/fsharp/blob/fsharp4/appveyor.ps1#L3) each time you do a tag so that you don't have to do it manually?

**Comment by ctaggart** [comment]
If you are using Paket and don't wish to upgrade to 4 yet, the easy way is to add `< 4` in `paket.dependencies`:
```
nuget FSharp.Core < 4
```

**Comment by dsyme** [comment]
@ctaggart Would it be possible for you to update FSharp.Compiler.Tools as well please?  They should be done together I suppose.

**Comment by dsyme** [comment]
@ctaggart - re versions, I was just wanting you to put in a PR to manually increment the version numbers after you push the packages.  I guess I should have done it when I tagged but I was in a hurry :)

**Comment by ctaggart** [comment]
Just to verify: FSharp.Core 4.0.0.1 may be used from Visual Studio 2013 projects, correct? I read http://fsharp.github.io/2015/04/18/fsharp-core-notes.html again and it looks to be binary compatible.

https://twitter.com/sforkmann/status/624466685878235136
![image](https://cloud.githubusercontent.com/assets/80104/8879478/80e56a8a-31e6-11e5-9901-600553fa7137.png)

I had a coworker try it out from a basic VS 2013 console app and it looks good.

**Comment by latkin** [comment]
@ctaggart - referencing vN+1 version of FSharp.Core from vN compiler is not supported. It will probably work ok in a lot of cases but quite possible it could blow up. It's not something we test at all, so very much "use at your own risk".

In particular I wonder about new quotation serialization format in 4.0 and how that might cause conflicts.

**Comment by ctaggart** [comment]
Thank you for clarifying that.

**Comment by dsyme** [comment]
Hi @ctaggart  - can we close this issue now that the update has been released?

BTW "master" is now F# 4.0+ in this repo. F# 3.1 has been archived at branch "fsharp31" and stable F# 4.0 is also at "fsharp4"

**Comment by ctaggart** [comment]
Yes, you may close this issue. If I could, I would.

**Comment by amazingant** [comment]
I can! :)
