### ISSUE TITLE
missing FSharp.Core net20 in 3.1.2.1 nupkg

### ISSUE THREAD

**Issue by ctaggart** [fsharp/fsharp#430]
@eiriktsarpalis just brought this up on twitter. /cc @forki

There is no `net20` package when you install FShap.Core 3.1.2.1.
![image](https://cloud.githubusercontent.com/assets/80104/8516426/efac6cc0-2368-11e5-8898-46e7642a2e27.png)

but according to this page, it looks like there should be:
https://msdn.microsoft.com/en-us/library/ee353567.aspx
![image](https://cloud.githubusercontent.com/assets/80104/8516434/093ce638-2369-11e5-9027-4b4f61d62c53.png)

**Comment by eiriktsarpalis** [comment]
:+1: 

Would it be possible to have an update which incorporates `2.3.0.0`?

**Comment by dsyme** [comment]
That seems reasonable. PR anyone?

**Comment by eiriktsarpalis** [comment]
I think it's as simple as copying [this entry](https://github.com/fsharp/fsharp/blob/master/FSharp.Core.Nuget/FSharp.Core.3.0.nuspec#L25) to the 3.1 nuspec. Or am I missing something?

**Comment by eiriktsarpalis** [comment]
@dsyme I have created a [branch](https://github.com/eiriktsarpalis/fsharp/tree/add-net35-in-nuspec) with some initial changes. Could you review before I make the PR?

**Comment by ctaggart** [comment]
@eiriktsarpalis I'll review your branch. I want to make sure the the file versions are indeed the ones shipped with 3.1.2 installer.
https://github.com/fsharp/fsharp/compare/master...eiriktsarpalis:add-net35-in-nuspec

**Comment by ctaggart** [comment]
Listed below are libraries from:
 * fsharp\lib\bootstrap\signed
 * nuget install FSharp.Core -version 3.0.2
 * nuget install FSharp.Core -version 3.1.2.1

I listed their assembly version and their file version.

```
.NETCore\3.259.3.1\FSharp.Core.dll
  3.259.3.1   3.259.30815.0  
.NETCore\3.3.1.0\FSharp.Core.dll
  3.3.1.0     3.31.30815.0   
.NETCore\3.78.3.1\FSharp.Core.dll
  3.78.3.1    3.78.30815.0   
.NETFramework\v2.0\2.3.0.0\FSharp.Core.dll
  2.3.0.0     2.3.50727.0    
.NETFramework\v4.0\4.3.0.0\FSharp.Core.dll
  4.3.0.0     4.3.50727.0    
.NETFramework\v4.0\4.3.1.0\FSharp.Core.dll
  4.3.1.0     4.31.30815.0   
.NETPortable\2.3.5.0\FSharp.Core.dll
  2.3.5.0     2.3.60315.1    
.NETPortable\2.3.5.1\FSharp.Core.dll
  2.3.5.1     2.3.30815.0    

FSharp.Core.3.0.2\lib\net35\FSharp.Core.dll
  2.3.0.0     2.3.50727.0    
FSharp.Core.3.0.2\lib\net40\FSharp.Core.dll
  4.3.0.0     4.3.50727.0    
FSharp.Core.3.0.2\lib\portable-net45+sl5+netcore45+MonoAndroid1+MonoTouch1\FSharp.Core.dll
  2.3.5.0     2.3.60315.1    

FSharp.Core.3.1.2.1\lib\MonoAndroid\FSharp.Core.dll
  2.3.98.1    2.3.98.1       
FSharp.Core.3.1.2.1\lib\MonoTouch\FSharp.Core.dll
  2.3.98.1    2.3.98.1       
FSharp.Core.3.1.2.1\lib\net40\FSharp.Core.dll
  4.3.1.0     4.31.30815.0   
FSharp.Core.3.1.2.1\lib\portable-net45+netcore45+MonoAndroid1+MonoTouch1\FSharp.Core.dll
  3.3.1.0     3.31.30815.0   
FSharp.Core.3.1.2.1\lib\portable-net45+netcore45+wp8+MonoAndroid1+MonoTouch1\FSharp.Core.dll
  3.78.3.1    3.78.30815.0   
FSharp.Core.3.1.2.1\lib\portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1\FSharp.Core.dll
  3.259.3.1   3.259.30815.0  
FSharp.Core.3.1.2.1\lib\portable-net45+sl5+netcore45+MonoAndroid1+MonoTouch1\FSharp.Core.dll
  2.3.5.1     2.3.30815.0    
```

Is it correct that the exact same binary from 3.0 should be included in the 3.1 package?
```
.NETFramework\v2.0\2.3.0.0\FSharp.Core.dll
  2.3.0.0     2.3.50727.0 
```
It looks like it to me. I will add it to the 3.1 package. I will add it to my changes for #367 submit a PR, and push a new nupkg to a MyGet feed so that we can test it before I upload it to NuGet Gallery. I'll get the nupkg out later today.

**Comment by dsyme** [comment]
@ctaggart  Yes, that looks right. I'm OK with including "the latest available FSharp.Core for old framework versions" in the FSharp.Core nuget package.  The 2.3.0.0 is the FSharp.Core for F# 3.0.  You can still use it with F# 3.1 and F# 4.0 but some functionality will be limited (new APIs will not be available).

**Comment by ctaggart** [comment]
This shouldn't actually be closed until verified and I upload it to the NuGet Gallery. A `3.1.2.1` is available for testing from the AppVeyor NuGet feed. See details here for testing:
https://github.com/fsharp/fsharp/pull/437#issuecomment-119375939

**Comment by ctaggart** [comment]
The Xamarin library issue with Paket is resolved with https://github.com/fsharp/fsharp/pull/450.

**Comment by ctaggart** [comment]
@dsyme We just need a new git `3.1.2.5` tag when you are ready.

**Comment by dsyme** [comment]
done

**Comment by ctaggart** [comment]
Tested it with a couple of solutions. Published:
https://www.nuget.org/packages/FSharp.Core/3.1.2.5
