### ISSUE TITLE
[<Extension>] functions have to use tuple form to be usable in F#?

### ISSUE THREAD

**Issue by wezhu** [fsharp/fsharp#431]
Assume I write a library in F#, and provided the following:
 
    type Foo (a : int) =
 
        member x.Add2 (b:int) (c:int) = 
            a + b + c
 
    [<Extension>]
    type ExtensionsToFoo =
    
        [<Extension>]
        static member Add2Ext1(o : Foo, b, c) =
            o.Add2 b c
     
        [<Extension>]
        static member Add2Ext2 (o : Foo) b c =
            o.Add2 b c
 
Note Add2Ext1 uses tuple form and Add2Ext2 uses the currying form.  There’s no compilation error.   However, when I use this library from an F# program, “Add2Ext2” is not considered an extension method to Foo
 
    let x = Foo(3);
    let y = x.Add2 1 2
    let z1 = x.Add2Ext1(1, 2)
    let z2 = x.Add2Ext2 1 2
 
There will be a compilation error “’AddExt2’ is not defined”.   So I assume only methods using tuple form can be considered as extension methods.  Is that right?  If this is the case, why there isn’t a compiler error when build the library?  The [<Extension>] should have declared the intent explicitly.  The compiler should be able to warn instead of silently disallowing it.
 
More interestingly, if I try to use this exact same library from a C# program, “AddExt2” is actually regarded as an extension methods for Foo. The code below compiles fine
 
    var x = new Foo(3);
    var y = x.Add2(1, 2);
    var z1 = x.Add2Ext1(1, 2);
    var z2 = x.Add2Ext2(1, 2);
 
This inconsistent behavior is by design or a bug?  I’m using F# 3.1. I also tried F# 4.0 briefly, seems to be the same behavior. 

One reason I'm asking this question is that I need to decide whether the member functions of type Foo should use currying form or tuple form. If the extension functions (using ExtensionAttribute) can only use tuple form, to be consistent, it seems I will have to use tuple form throughout. 

What if someone wants to extend a type that has already used currying form for its members? It will have to suffer the inconsistency between the original member functions and the new extension functions?  Seems unfortunate. 

====

About why not using F#'s Type Extensions (https://msdn.microsoft.com/en-us/library/dd233211.aspx), which does allow curry form. However, for my real usage of extension functions is for generic types, I don't know how to achieve it with type extensions but ExtensionAttribute seems to work fine. 

Let’s say I have a type
 
    type Foo<'U> () = 

        member x.Method1(f : 'U) =
            f

Use ExtensionAttribute, I can add an extension function specific to Foo<’K*’V> but not other Foo’s

    [<Extension>]
    type ExtensionsToFoo =

        [<Extension>]
        static member Method2(o : Foo<'K*'V>, kv : 'K*'V) =
            kv

Then I can write

    let x = Foo<int*int>()
    let y = x.Method1((5, 5))
    let z = x.Method2((5, 5))

If I have x = Foo<int>() or Foo<int*int*int>, then compiler will find that Method2 is not available for object "x".  This is what I’m trying to achieve. C# can do the same. 

I cannot figure how to do the same thing with Type Extensions, would love to learn if it's possible. 

Regardless of Type Extensions' capability, this issue is about the behavior of [<Extension>].  

Thanks,

**Comment by dsyme** [comment]
These are questions about the F# language design and probably belong at stackoverflow.com (this repo is for cross-platform issues)
