### ISSUE TITLE
create stable builds using AppVeyor from Git tag

### ISSUE THREAD

**Issue by ctaggart** [fsharp/fsharp#434]
#433 makes all the builds pre-release NuGet builds. I am proposing that the stable NuGet builds be done from AppVeyor as well. I do this for my open source and work projects. The AppVeyor NuGet project feed may be used for testing the builds. If a stable build fails testing, you can delete and then re-add the Git tag. AppVeyor will replace the file in the nupkg in the feed.

The changes to appveyor.ps1 would be pretty simple.
```
if ($env:appveyor_repo_tag -eq 'true' -and isVersionTag($env:appveyor_repo_tag_name)){
```

We would just need to agree upon what locally the `isVersionTag` is. I don't currently understand how this repo is being tagged:
![image](https://cloud.githubusercontent.com/assets/80104/8537263/553ae334-2411-11e5-9825-1b37f0143504.png)

Why aren't there any `3.1.2.x` builds? Why are there so many? Are some unstable builds? Does the change log only have the stable builds?
https://github.com/fsharp/fsharp/blob/master/CHANGES.txt

**Comment by dsyme** [comment]
Re tagging - yes, it looks like 3.1.2,x tags should have been used at some point.  I don't see any reason not to have used those. CHANGES.txt looks like it has not been kept up to date (I did the last couple of integrations from visualfsharp so it's my fault)

.

**Comment by ctaggart** [comment]
If you merge in #437, you and create a `3.1.2.2` git tag, it will create a FSharp.Core.3.1.2.2.nupkg and put it in the AppVeyor Project Feed.  We can then test out that package if rename the AppVeyor Project Feed as explained in #433. After a sufficient period of testing, I can promote it to the NuGet Gallery.

**Comment by ctaggart** [comment]
@dsyme Thanks for merging in #433, but it is #437 that is needed before creating the `3.1.2.2` tag. Could you merge it in and then move the tag?

PS for moving the tag:
``` powershell
$v = '3.1.2.2'
git tag -d $v; git push origin ":$v"
git tag $v; git push origin $v
```
