### ISSUE TITLE
Need to add signed FSharp.Core 4.4.0.0 when final version is available

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp#444]
Right now the Nuget FSharp.Core for 4.0 is not building:

    [00:08:08] NuGet.exe : Could not find a part of the path 'C:\projects\fsharp\lib\bootstrap\signed\.NETFramework\v4.0\4.4.0.0'.

When the Visual F# Tool 4.0.0 RTM comes out we need to add a copy of the signed FSharp.Core to lib\bootstrap\signed\.NETFramework\v4.0\4.4.0.0.

**Comment by ctaggart** [comment]
Will this be in the `fsharp4` branch? It would be nice to clean up the versioned branches:

![image](https://cloud.githubusercontent.com/assets/80104/8665540/dfc777a0-2999-11e5-89d0-a970c0b989f6.png)

I'm a big fan of versioned branches. To eliminate any confusion and to create consistency, you could make a `3.1` branch and a `4.0` branch and make the `4.0` the default GitHub branch. Then remove `master` and some of the others.

**Comment by 7sharp9** [comment]
If F#4 is ready then mono needs to be notified to bump the tag referenced.

**Comment by knocte** [comment]
I don't like the idea of removing master.

**Comment by 7sharp9** [comment]
Oh I missed that, no, don't remove master, master should be the current standard stable version.

**Comment by forki** [comment]
what is the status of F# 4.0 on mono?

**Comment by 7sharp9** [comment]
Theres currently no official F#4, the sooner there is a tagged version the sooner it can be included in a future mono.

Unless you mean does it work on mono?  No idea never tried it.

**Comment by dsyme** [comment]
It works and is ready to roll apart from the finalized, signed FSharp.Core. See the "fsharp4" branch.  We need to submit the finalized FSharp.Core binaries there

**Comment by forki** [comment]
ok will try to do that

**Comment by ctaggart** [comment]
This was resolved by #454.
