### ISSUE TITLE
What is the difference betwean Microsoft/visualfsharp and fsharp/fsharp/ repositories?

### ISSUE THREAD

**Issue by xperiandri** [fsharp/fsharp#455]
What is the difference between [Microsoft/visualfsharp](https://github.com/Microsoft/visualfsharp/) and [fsharp/fsharp/](https://github.com/fsharp/fsharp/) repositories?
I am confused with this coexistence.

**Comment by ctaggart** [comment]
This should help:
http://fsharp.github.io/2014/06/18/fsharp-contributions.html
