### ISSUE TITLE
Map.add crashes with  a record key and DU as a value

### ISSUE THREAD

**Issue by GeoffreyKing** [fsharp/fsharp#459]
Running on: 
Mono JIT compiler version 4.0.2 (Stable 4.0.2.5/c99aa0c Wed Jun 24 10:04:37 UTC 2015)
FSharp 3.1
Ubuntu 14.04
Works when compiled (and an entrypoint added)
Fails when run from in the REPL 
    
    // This code causes a core dump.
    // The types of key & value passed to Map.add seem to be the triggers.
    // If primitive types are used it doesn't crash
    type Cell =
      | Int of int
      | Float of float

    type CellRef = {
      Col   : int
      Row   : int
      }

    let cref c r = {
      Col = c
      Row = r
      }

    let folding sheet =
      let initialRange = {Col=0;Row=1}
      let update cref range = range
    
      Map.fold (fun range cref cell -> update cref range) initialRange sheet

    let evil () =
      Map.empty
      |> Map.add (cref 10 9) (Int 7)
      |> folding

**Comment by dsyme** [comment]
This is a Mono bug, please add at https://bugzilla.xamarin.com/ and cross-link back here.

thanks

**Comment by GeoffreyKing** [comment]
Filed here :
https://bugzilla.xamarin.com/show_bug.cgi?id=32454

**Comment by dsyme** [comment]
Could you check again with Mono master?  What looks like a related bug was stated as fixed here: https://bugzilla.xamarin.com/show_bug.cgi?id=31934#c8, would be good to check.

**Comment by dsyme** [comment]
I'm closing this as it appears fixed on Mono master. Please check again if you can.
