### ISSUE TITLE
F# 4.0 not on homebrew

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#460]
It should be added so that you can install F# just like any other programming language.

**Comment by 7sharp9** [comment]
I don't think F#3.1 installs properly on home brew yet either.

**Comment by dsyme** [comment]
F# 3.1 installs ok, and has done for a while. There is a reported issue with the project scaffold, see https://github.com/fsharp/fsharp/issues/451. Any help in investigating would be appreciated.

**Comment by sgtz** [comment]
checking along the #451 angle.  See #451.

**Comment by dsyme** [comment]
This is fixed, fsharp is now part of "mono" homebrew
