### ISSUE TITLE
F# 4.0 Constructor as first class function does not work for structs

### ISSUE THREAD

**Issue by rookboom** [fsharp/fsharp#462]
The following code does not compile:
```fsharp
module Test =
    [<Struct>]
    type SparseEntry(index:int, value:float32) =
        member m.Index = index
        member m.Value = value

    let create(items:(int*float32)[]) =
        items.map(SparseEntry)
```
If I remove the ```[<Struct>]``` attribute it works fine.

**Comment by smoothdeveloper** [comment]
Can you fix the code format with triple backticks: see "Syntax highlighting" on https://guides.github.com/features/mastering-markdown/

Thanks

**Comment by rookboom** [comment]
Sure

**Comment by latkin** [comment]
This should be moved to https://github.com/microsoft/visualfsharp

FWIW I do not repro, at least not with built-in APIs.  Where are you getting `map` from? Its signature might not be compatible with the feature.

i.e., this compiles/runs fine for me:

```fsharp
module Test =
    [<Struct>]
    type SparseEntry(index:int, value:float32) =
        member m.Index = index
        member m.Value = value

    let create(items:(int*float32)[]) =
        items |> Array.map SparseEntry

Test.create [| (1, 1.f) |]
```

**Comment by rookboom** [comment]
Looks like this bug is related to FSharp.Core.Fluent 4.0. If I use Array.map it works fine. I'll flag the issue in that repository.
