### ISSUE TITLE
"The byref-typed variable 't' is used in an invalid way" when accessing a field from a closure inside of a member

### ISSUE THREAD

**Issue by Rickasaurus** [fsharp/fsharp#466]
Noticed this when I was messing around, and it appears to be the same in 2013 as 2015, but I figured this is an odd edge case in the spirit of the new mutable work and so should report it:

```fsharp
type [<Struct>] Matrix =
    val array : float [,]
    new (arr: float [,]) = { array = arr }
    member t.ToVector () =
        if Array2D.length1 t.array = 1 then Array.init (Array2D.length2 t.array) (fun j -> t.array.[0,j]) 
        elif Array2D.length2 t.array = 1 then Array.init (Array2D.length1 t.array) (fun i -> t.array.[i,0]) 
        else failwith "Cannot convert a multidimensional matrix to a Vector"
``` 

simple workaround seems to be to add a `let t = t` at the top of the function, but that seems kind of ugly.

```fsharp
type [<Struct>] Matrix =
    val array : float [,]
    new (arr: float [,]) = { array = arr }
    member t.ToVector () =
        let t = t  
        if Array2D.length1 t.array = 1 then Array.init (Array2D.length2 t.array) (fun j -> t.array.[0,j]) 
        elif Array2D.length2 t.array = 1 then Array.init (Array2D.length1 t.array) (fun i -> t.array.[i,0]) 
        else failwith "Cannot convert a multidimensional matrix to a Vector"
```

**Comment by dsyme** [comment]
Hi @Rickasaurus - Could you put this on http://fslang.uservoice.com please?  It's a valuable suggestion we may want to action in a future language version. 

(Right now the behaviour is as expected - inside the closure "t" can't be mutated in the way that would be expected if it was a fully valid byref value)

**Comment by dsyme** [comment]
(Closing this as it's been redirected to http://fslang.uservoice.com)
