### ISSUE TITLE
[feature-request] Enable joint compilation of F# and C#

### ISSUE THREAD

**Issue by dsaf** [fsharp/fsharp#470]
Both languages have compilers-as-services. The general idea had been tried in past in the Java world:

http://www.groovy-lang.org/groovyc.html#section-jointcompilation
https://docs.gradle.org/current/userguide/groovy_plugin.html
http://www.codecommit.com/blog/scala/joint-compilation-of-scala-and-java-sources

Motivation:

1. Enable gradual transition of existing source code from C# to F#.
2. Smoothen the learning curve for C# developers.
3. Allow mixing language features (providing someone likes different aspects of both languages).

**Comment by dsyme** [comment]
Could you open this at http://fslang.uservoice.com please?  This repo is specifically for cross-platform issues for F#, and this is a major feature request.

Thanks!
don
