### ISSUE TITLE
Build FAILED '2.6.4' of package 'NUnit' -- Mono Ubuntu

### ISSUE THREAD

**Issue by igouy** [fsharp/fsharp#471]
:/usr/local/src/fsharp$ ./autogen.sh --prefix=/usr/local
checking whether make sets $(MAKE)... yes
checking for pkg-config... /usr/bin/pkg-config
configure: "pkg-config: /usr/bin/pkg-config"
configure: "PKG_CONFIG_LIBDIR: "
checking for xbuild... /usr/local/bin/xbuild
configure: xbuild: /usr/local/bin/xbuild
configure: PCL Reference Assemblies for Profile 47 found: no
configure: PCL Reference Assemblies for Profile 47 found: no
configure: PCL Reference Assemblies for Profile 7 found: no
configure: PCL Reference Assemblies for Profile 78 found: no
configure: PCL Reference Assemblies for Profile 259 found: no
configure: creating ./config.status
config.status: creating launcher
config.status: creating Makefile
config.status: creating config.make
config.status: creating src/fsharp/Makefile
config.status: creating src/fsharp/FSharp.Build-proto/Makefile
config.status: creating src/fsharp/FSharp.Compiler-proto/Makefile
config.status: creating src/fsharp/Fsc-proto/Makefile
config.status: creating src/fsharp/FSharp.Core/Makefile
config.status: creating src/fsharp/FSharp.Build/Makefile
config.status: creating src/fsharp/FSharp.Compiler/Makefile
config.status: creating src/fsharp/Fsc/Makefile
config.status: creating src/fsharp/FSharp.Compiler.Interactive.Settings/Makefile
config.status: creating src/fsharp/FSharp.Compiler.Server.Shared/Makefile
config.status: creating src/fsharp/FSharp.Data.TypeProviders/Makefile
config.status: creating src/fsharp/fsi/Makefile
config.status: creating src/fsharp/fsiAnyCpu/Makefile
config.status: creating src/fsharp/policy.2.0.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.2.3.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.3.3.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.3.7.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.3.47.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.3.78.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.3.259.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.4.0.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.4.3.FSharp.Core/Makefile

:/usr/local/src/fsharp$ make
make -C src/fsharp all
make[1]: Entering directory '/usr/local/src/fsharp/src/fsharp'
make build-proto
make[2]: Entering directory '/usr/local/src/fsharp/src/fsharp'
cp -p /usr/local/src/fsharp/lib/bootstrap/4.0/FSharp.Core.dll /usr/local/src/fsharp//lib/proto/FSharp.Core.dll
cp -p /usr/local/src/fsharp/lib/bootstrap/4.0/FSharp.Core.sigdata /usr/local/src/fsharp//lib/proto/FSharp.Core.sigdata
cp -p /usr/local/src/fsharp/lib/bootstrap/4.0/FSharp.Core.optdata /usr/local/src/fsharp//lib/proto/FSharp.Core.optdata
make -C FSharp.Build-proto Configuration=proto build-proto
make[3]: Entering directory '/usr/local/src/fsharp/src/fsharp/FSharp.Build-proto'
MONO_ENV_OPTIONS= /usr/local/bin/xbuild /p:Configuration=Proto
XBuild Engine Version 12.0
Mono, Version 4.3.0.0
Copyright (C) 2005-2013 Various Mono authors

Build started 8/10/2015 8:37:49 AM.
__________________________________________________
Project "/usr/local/src/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj" (default target(s)):
	Target CallFsSrGen:
	Skipping target "CallFsSrGen" because its outputs are up-to-date.
	Target BeforeBuild:
		Executing: mono --runtime=v4.0.30319 /usr/local/src/fsharp/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.exe restore packages.config -PackagesDirectory packages
		WARNING: Error: SendFailure (Error writing headers)
		WARNING: Error: SendFailure (Error writing headers)
		Unable to find version '2.6.4' of package 'NUnit'.
		Unable to find version '2.6.4' of package 'NUnit.Runners'.
/usr/local/src/fsharp/src/FSharpSource.targets: error : Command 'mono --runtime=v4.0.30319 /usr/local/src/fsharp/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.exe restore packages.config -PackagesDirectory packages' exited with code: 1.
	Task "Exec" execution -- FAILED
	Done building target "BeforeBuild" in project "/usr/local/src/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj".-- FAILED
Done building project "/usr/local/src/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj".-- FAILED

Build FAILED.
Errors:

/usr/local/src/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj (default targets) ->
/usr/local/src/fsharp/src/FSharpSource.targets (BeforeBuild target) ->

	/usr/local/src/fsharp/src/FSharpSource.targets: error : Command 'mono --runtime=v4.0.30319 /usr/local/src/fsharp/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.exe restore packages.config -PackagesDirectory packages' exited with code: 1.

	 0 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:01.7554000
Makefile:9: recipe for target 'build-proto' failed
make[3]: *** [build-proto] Error 1
make[3]: Leaving directory '/usr/local/src/fsharp/src/fsharp/FSharp.Build-proto'
Makefile:15: recipe for target 'build-proto' failed
make[2]: *** [build-proto] Error 2
make[2]: Leaving directory '/usr/local/src/fsharp/src/fsharp'
Makefile:10: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/local/src/fsharp/src/fsharp'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rneatherway** [comment]
Hi @igouy. Which version of mono are you using? (`mono --version`)

**Comment by igouy** [comment]
Mono JIT compiler version 4.3.0 (master/906ff55 Sun Aug  9 22:49:27 PDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/a92ada2)
	GC:            sgen

**Comment by rneatherway** [comment]
Hmm, I think this is most likely a temporary NuGet issue, as it works here with 4.0.2 and 4.3.0 (from Thursday). If this is the first mono installation on this machine you may need to run `mozroots --import --sync`.

**Comment by igouy** [comment]
I've been trying to build F# 4 for about a week, since I saw the release announcement.

I started off trying to build F# 4 with -- Mono JIT compiler version 4.3.0 (master/54e8010 Sun May 31 13:36:15 PDT 2015) -- and hit this same problem.

Yesterday I burned a couple of hours building LLVM for Mono, and then building Mono, and now...

**Comment by dsyme** [comment]
Perhaps a certificate problem?  Can you get any nuget packages on that machine?

**Comment by dsyme** [comment]
The error is definitely here: 
``
Executing: mono --runtime=v4.0.30319 /usr/local/src/fsharp/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.exe restore packages.config -PackagesDirectory packages
 WARNING: Error: SendFailure (Error writing headers)
 WARNING: Error: SendFailure (Error writing headers)
``

**Comment by dsyme** [comment]
See here (after searching Google for "SendFailure (Error writing headers)")

http://stackoverflow.com/questions/25081384/mono-httpwebrequest-over-ssl-error-writing-headers

**Comment by dsyme** [comment]
That is, try 

    mozroots --import --sync

**Comment by dsyme** [comment]
Another comment in the SO reply: 

> if you run your program with "sudo mono", adding the certs to the user store will not be enough. You would have to add them to the machine store by passing "--machine". This took me a while to figure it out

**Comment by igouy** [comment]
> mozroots --import --sync
Seems to be building.
Another comment in the SO reply says "Mono 3.12, or above, has removed the need to run mozroots".

I did not experience this problem building F# 3.1 on the same machine against the same Mono install back on May 31.

**Comment by dsyme** [comment]
Yes, I agree, I remember the comment that mozroots is no longer needed. @migueldeicaza or @directhex might know if something is up - or maybe the other certificate roots on your machine are somehow out of sync.

**Comment by dsyme** [comment]
In any case, closing this here - if you can isolate the problem with Mono then please add a bug to http://bugzilla.xamarin.com

**Comment by directhex** [comment]
@dsyme 3.12 and above include the "cert-sync" tool, which converts a user's OS-wide certificate store to Mono's cert store format. All our RPMs and .debs run cert-sync at install time. If users go out of their way to avoid using the helpers they're provided with, that's sorta out of my hands

**Comment by dsyme** [comment]
Ah ok, thanks @directhex.  So I suppose this isn't run on a fresh build of Mono from source.

**Comment by knocte** [comment]
Mono from source?

Is the cert-sync run as part of mono's install target, or is it only a debian-package routine?

**Comment by directhex** [comment]
There's no sane way to run it via "make install", because there's no standard location for the cert store on Linux - if there was, frankly, we could just consume it directly.

**Comment by directhex** [comment]
http://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync

**Comment by knocte** [comment]
Thanks
