### ISSUE TITLE
Conditional breakpoints don't work in VS 2015 for reference types when target is x86/Any CPU

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsharp/fsharp#477]
It works for value types bindings. I tried int and float.
But fails for reference types - I tried string and record type with property of type int.
It happens only for x86/Any CPU (which defaults to x86) targets.

![image](https://cloud.githubusercontent.com/assets/3004037/9447935/adfc2d30-4a4e-11e5-93af-0a51cceae75e.png)

**Comment by enricosada** [comment]
Hi @dmitry-a-morozov , visual studio issues should be submitted and fixed in the https://github.com/Microsoft/visualfsharp repo, can you create a new issue there?

This repo is for cross platoform packaing, see http://fsharp.github.io/2014/06/18/fsharp-contributions.html for a guide
