### ISSUE TITLE
incorrectly reported unused variables inside query expressions

### ISSUE THREAD

**Issue by dmitry-a-morozov** [fsharp/fsharp#478]
```fsharp
    query {
        for x in [1..10] do
        where true
        select x 
    }
```
With --warnon:1182 specified compiler complains "warning FS1182: The value 'x' is unused"
It happens both in VS 2013 and 2015

**Comment by enricosada** [comment]
duplicated of Microsoft/visualfsharp#422 

@dmitry-a-morozov Language issues should be entered and fixed at http://github.com/Microsoft/visualfsharp. Any fixes/updates will then be integrated into this repo. See http://fsharp.github.io/2014/06/18/fsharp-contributions.html for a guide
