### ISSUE TITLE
Discriminated union type in order to be able to write exception free code in f#

### ISSUE THREAD

**Issue by wallymathieu** [fsharp/fsharp#479]
In order to be able to write code that you can easily consume that does not throw an exception. @wastaz mentioned that chessie declares:

```
type Result<'TSuccess, 'TMessage> = 
    | Ok of 'TSuccess * 'TMessage list
    | Bad of 'TMessage list
```

**Comment by enricosada** [comment]
hi @wallymathieu, the requests of new features are tracked in https://fslang.uservoice.com/ not the github repo, can you open a new suggestion there? /cc @dsyme  

Btw this repo is for cross platform packaging, the contributions to f# library/tools/compiler are managed in https://github.com/Microsoft/visualfsharp

**Comment by wallymathieu** [comment]
@enricosada the signature of the Result type looks better. I've added the suggestion: https://fslang.uservoice.com/forums/245727-f-language/suggestions/9484395-discriminated-union-type-in-order-to-be-able-to-wr
