### ISSUE TITLE
eprintfn / printfn (stderr/stdout processing precedence) discrepancy on Linux

### ISSUE THREAD

**Issue by larsw** [fsharp/fsharp#481]
Hi,
 Ref. the folloing gist: https://gist.github.com/larsw/235e4a35c1470e575eee
 Is this behavior well known and a result of the underlying terminal subsystem in Linux?

**Comment by bjartwolf** [comment]
![onwindows](https://cloud.githubusercontent.com/assets/1174441/9490601/4027a7d4-4be9-11e5-9a78-04691a044c70.png)
Tried the same code on Windows, where it prints in the expected order.

**Comment by dsyme** [comment]
Yes, IIRC the output of a new line will flush stdout/stderr.  But in any case, AFAIK this isn't something related to F# specifically - the same differences would, I think, appear with Write/WriteLine for .NET.

**Comment by dsyme** [comment]
Closing as I don't think this is an F# bug, just a x-plat difference in how output is handled.
