### ISSUE TITLE
"automake" 2.69 requirement for OS X should be "autoconf"

### ISSUE THREAD

**Issue by wyoung** [fsharp/fsharp#482]
On the project home page, it claims you need "automake 2.69" to build on OS X, but there is no such thing. It clearly means autoconf 2.69.

**Comment by dsyme** [comment]
closing - the docs now mention autoconf

**Comment by wyoung** [comment]
Sorry to be difficult, but it isn't autoconf/automake 2.69. The version numbers are not synchronized: the current versions are autoconf 2.69 and automake 1.15.

I suppose it should say, "OS X no longer ships with autoconf and automake, which are needed to build F# from the git repository. To install them from Homebrew, say "brew install autoconf automake". "

**Comment by dsyme** [comment]
Hi @wyoung - can you send a PR to README.md for that please?  Thanks

**Comment by wyoung** [comment]
Done: https://github.com/fsharp/fsharp/pull/490
