### ISSUE TITLE
F#4.0 interactive: Method 'FSharpAsync.AwaitTask' not found

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#485]
I'm getting this error message:

```
W 2015-09-01T13:10:52.7268710+00:00: tcp request processing failed [Suave.Tcp.tcpIpServer.job] cont...
System.MissingMethodException: Method 'FSharpAsync.AwaitTask' not found.
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@805[Microsoft.FSharp.Core.FSharpChoice`2[Microsoft.FSharp.Core.Unit,Suave.Sockets.Error],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x0002b] in /private/tmp/source-mono-mac-4.0.0-branch-c5sr3/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/fsharp-fsharp-1f79c04/src/fsharp/FSharp.Core/control.fs:809
```

According to the stack trace, this fsharp-repo commit is being used: https://github.com/fsharp/fsharp/commit/1f79c04

Repro is this code base: https://github.com/haf/suave-presentation.2015-09-03/commit/ee7b3d71fb04eb4466010dc9ba6142b0de2ad051

 1. d/l code base
 1. pushd public && npm install
 1. popd
 1. mono paket.bootstrapper.exe
 1. mono paket.exe install
 1. ./site.fsx

Make a request to http://localhost:8083 in a browser on OS X.

```
$ mono --version
Mono JIT compiler version 4.0.3 ((detached/d6946b4 Wed Jul 29 14:46:23 EDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-(detached/a173357)
	GC:            sgen
```

You'll get either this error or https://bugzilla.xamarin.com/show_bug.cgi?id=33534

## Full stack trace:

```
./site.fsx
V 2015-09-01T14:05:50.8957870+00:00: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
I 2015-09-01T14:05:50.9939010+00:00: listener started in 93.933 ms with binding 127.0.0.1:8083 [Suave.Tcp.tcpIpServer]
V 2015-09-01T14:05:52.0607490+00:00: 127.0.0.1 connected, total: 1 clients [Suave.Tcp.tcpIpServer.job]
V 2015-09-01T14:05:52.0643790+00:00: reserving buffer: 811008, free count: 99 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
V 2015-09-01T14:05:52.0679210+00:00: -> processor [Suave.Web.httpLoop.loop]
V 2015-09-01T14:05:52.0688480+00:00: reading first line of request [Suave.Web.processRequest]
V 2015-09-01T14:05:52.0782750+00:00: reserving buffer: 802816, free count: 98 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
V 2015-09-01T14:05:52.0911970+00:00: reading headers [Suave.Web.processRequest]
V 2015-09-01T14:05:52.0943960+00:00: freeing buffer: 802816, free count: 99 [Suave.Web.split] [Suave.Socket.BufferManager]
V 2015-09-01T14:05:52.1041330+00:00: parsing post data [Suave.Web.processRequest]
V 2015-09-01T14:05:52.1063110+00:00: <- processor [Suave.Web.httpLoop.loop]
V 2015-09-01T14:05:52.1117440+00:00: Files.browse trying file (local file url:'/' root:'/Users/h/dev/haf/suave-presentation.2015-09-03/build/public/') [Suave.Http.Files.browse]
V 2015-09-01T14:05:52.1142850+00:00: failed to find resource by key '/Users/h/dev/haf/suave-presentation.2015-09-03/build/public/' [Suave.Http.ServeResource.resource]
V 2015-09-01T14:05:52.1471990+00:00: 'Connection: keep-alive' recurse [Suave.Web.httpLoop.loop]
V 2015-09-01T14:05:52.1473530+00:00: -> processor [Suave.Web.httpLoop.loop]
V 2015-09-01T14:05:52.1473700+00:00: reading first line of request [Suave.Web.processRequest]
V 2015-09-01T14:05:52.1475070+00:00: reserving buffer: 802816, free count: 98 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
V 2015-09-01T14:05:52.1869250+00:00: reading headers [Suave.Web.processRequest]
V 2015-09-01T14:05:52.1870360+00:00: freeing buffer: 802816, free count: 99 [Suave.Web.split] [Suave.Socket.BufferManager]
V 2015-09-01T14:05:52.1881540+00:00: parsing post data [Suave.Web.processRequest]
V 2015-09-01T14:05:52.1882030+00:00: <- processor [Suave.Web.httpLoop.loop]
V 2015-09-01T14:05:52.1882920+00:00: Files.browse trying file (local file url:'/js/index.js' root:'/Users/h/dev/haf/suave-presentation.2015-09-03/build/public/') [Suave.Http.Files.browse]
W 2015-09-01T14:05:52.2005860+00:00: tcp request processing failed [Suave.Tcp.tcpIpServer.job] cont...
System.MissingMethodException: Method 'FSharpAsync.AwaitTask' not found.
  at Microsoft.FSharp.Control.AsyncBuilderImpl+callA@805[Microsoft.FSharp.Core.FSharpChoice`2[Microsoft.FSharp.Core.Unit,Suave.Sockets.Error],Microsoft.FSharp.Core.Unit].Invoke (Microsoft.FSharp.Control.AsyncParams`1 args) [0x00000] in <filename unknown>:0
V 2015-09-01T14:05:52.2012350+00:00: 127.0.0.1 disconnected, total: 0 clients [Suave.Tcp.tcpIpServer.job]
```

**Comment by 7sharp9** [comment]
Does that version of mono have F#4?

**Comment by 7sharp9** [comment]
I think the first F#4 in mono begins with #a89330f

**Comment by 7sharp9** [comment]
As far as I know mono 4.4 release will have F#4 support, unless you build mono yourself.

**Comment by haf** [comment]
This issue is that I can't run F# 4.0 on mono despite fsharpi telling me I should be able to. Is fsharpi wrong? Doesn't fsharpi load the assemblies by the side of what it's implemented in itself?

**Comment by dsyme** [comment]
> This issue is that I can't run F# 4.0 on mono despite fsharpi telling me I should be able to. 

What's the output from fsharpi?  The above seems to say Mono 4.0, but that doesn't mean F# 4.0 (Mono 4.4 has F# 4.0, Mono 4.0 has F# 3.1)

**Comment by haf** [comment]
I was thinking the flag `--noframework` – and then `#r "FSharp.Core"` – or is it by design that fsharpi should not be able to load other versions of FSharp.Core than what it's been compiled with?

**Comment by dsyme** [comment]
Correct, it can't load other versions (though does binding redirects to the FSharp.Core being used where necessary)

**Comment by haf** [comment]
So in this case, I'm loading a lib depending on F# 4.0 into fsharpi compiled with F# 3.1; should fsharpi add a binding redirect to 3.1 (then it shouldn't crash), or can binding redirects only be from lower versions to higher versions?

**Comment by haf** [comment]
This is Mono 4.0.3 on OS X by the way.

**Comment by dsyme** [comment]
It does seem that the bug mentioned here (missing AwaitTask) could happen if you are down-binding 4.4.0.0 to 4.3.1.0.  In any case, that wouldn't be a valid scenario.  If you are using a library depending on FSharp.Core 4.4.00 you should consume it using fsharpi/fsi.exe for  4.0.  What library are you depending on, and is there any reason for it to have a dependency on FSharp.Core 4.4.0.0?  The [recommendation](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html) is that libraries depend on the lowest version of FSharp.Core possible (generally 4.3.0.0 or 4.3.1.0)

**Comment by dsyme** [comment]
(Closing as I don't think this is an F# bug, please reopen if necessary)

**Comment by haf** [comment]
Thanks, that's a good exhaustive answer.
