### ISSUE TITLE
Build is not possible without internet access

### ISSUE THREAD

**Issue by ismail** [fsharp/fsharp#489]
In openSUSE Build Service (http://build.opensuse.org) our build machine have no internet access and starting with fsharp 4.0 its no longer seems to be possible to build without internet access, see:

[...]
                Executing: mono --runtime=v4.0.30319 /home/abuild/rpmbuild/BUILD/fsharp-4.0.0.3/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.exe restore packages.config -PackagesDirectory packages
                WARNING: Error: NameResolutionFailure
                WARNING: Error: NameResolutionFailure
               Unable to find version '2.6.4' of package 'NUnit'.
               Unable to find version '2.6.4' of package 'NUnit.Runners'.
[...]

The machine itself has nunit 2.6.4 installed already but the build system does not use it.

**Comment by dsyme** [comment]
Can you try a patch that excludes that line (e.g. conditionally on some environment variable that indicates the build is an opensuse build)?

**Comment by ismail** [comment]
Sure, if you can tell me where to look for.

**Comment by ismail** [comment]
We workarounded this with https://build.opensuse.org/package/view_file/Mono:Factory/fsharp/use-internal-nunit.patch
