### ISSUE TITLE
Task: Integrate visualfsharp --> fsharp --> FSharp.Compiler.Service

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp#494]
As [mentioned on twitter](https://twitter.com/dsyme/status/649741044519694339).  One of the tasks of the F# core engineering group is to regularly integrate from http://github.com/Microsoft/visualfsharp --> http://github.com/fsharp/fsharp --> http://github.com/fsharp/FSharp.Compiler.Service, and also to publish new nuget packages for FSharp.Compiler.Service. 

This issue is opened to cover this instance of this task.  It's not for a discussion about why we do things like this - it's for actually doing it :)

Right now Microsoft/visualfsharp contains a bunch of extra commits which need to be integrated in. Some of these are "alignments" which brought back some of changes from fsharp/fsharp and fsharp/FSharp.Compiler.Service. Others are bug fixes and feature work.  Others are changes in the Visual F# IDE tools which are not included in fsharp/fsharp or fsharp/FSharp.,Compiler.Service.  Our job is to do the integration, reconcile the conflicts and submit the PRs.

Volunteers are @rojepp, @silverspoon, Fabian Romero, Chet Husk, @brodyberg. I'll take you through how to do these integrations by doing it live on a skype group screen share session, likely on Saturday or Monday, for whoever is available, Please send me your skype ID via reply, email or DM on twitter.

thanks!
don

**Comment by Andrea** [comment]
I am Andrea here (not silverspoon) you can find me as Andrea BatCat on skype, Monday is better for me (great if around lunch time)

**Comment by baronfel** [comment]
I DM'd my info to Don, but I can be available Saturday or Monday.  I'm on GMT-6 and am flexible with my hours.

**Comment by rojepp** [comment]
I also DM'd Don. Today is better for me, packed schedule on Monday. Please record it anyway, if possible. :)

**Comment by dsyme** [comment]
Thanks everyone.  Today has slipped by, I'll aim to do this on Monday. We'll leave full instructions one way or another :)

**Comment by brodyberg** [comment]
Available Monday - Pacific time though. Happy to adjust if possible. Also available through the week.

**Comment by fromeroj** [comment]
Ok, waiting for updates.

**Comment by dsyme** [comment]
Some personal things came up today, I'll aim to do this Tuesday. I suggest 5pm BST.

**Comment by fromeroj** [comment]
It is good for me. Cheers.

**Comment by brodyberg** [comment]
Works for me.

**Comment by Andrea** [comment]
can you add a link, I might or might not be able to make it (I m travelling
at the moment)

Andrea
www.roundcrisis.com

**Comment by rojepp** [comment]
Ditto, I probably won't be able to make it.

**Comment by dsyme** [comment]
Make that 1715 BST, I'll ping the skype ids I have :)

**Comment by baronfel** [comment]
minor suggestion:

Skype doesn't have a recording feature natively, but it's possible and easy to create a google 'hangout on air' that has screen sharing and is recorded/backed up to YouTube automatically.  It also has a nice feature where you can choose only one or more apps to share the screen of, or your entire desktop.

Just an idea, since these meetings are valuable and may contain information others could use.

**Comment by baronfel** [comment]
I took some notes from the screencast below, and Fabian suggested I share them.  Enjoy:

## notes for migration from microsoft/visualfsharp => fsharp/fsharp

# Things that are removed
* all tests under tests/fsharpqa
	* though there are some binaries that are left (long term remove these?)
* delete everything under vsintegration/ 
	* these are the VS IDE integrations, not needed for the xplat repository
* fsharp.languageservice.compiler is a MS-internal version of FCS
* the windows-specific update.cmd and runtests.cmd aren't necessary
* anything related to salsa testing library
	* lib that MS uses to test the VS integrations, not needed for xplat repository
* root/unittests are visualstudio-specific and use the salsa library, not needed for the xplat repository

# Everything else
* removal of the TypeProvider authorization dialog
* test renames
* whitespace alignments
* it's ok to make an in-progress pull request and ask for clarification on problem areas

**Comment by rojepp** [comment]
Great notes, Chester, thanks!

tis 6 okt 2015 20:44 Chester Husk III <notifications@github.com> skrev:

**Comment by dsyme** [comment]
Cool notes, thanks! Could you please add a version of those via a PR to https://github.com/fsharp/fsharp/blob/master/README.md#development-notes?  Perhaps also update the CI notes there too?

**Comment by baronfel** [comment]
Certainly.  I'll send a PR later tonight or tomorrow.

**Comment by dsyme** [comment]
As an aside, the following long-term tasks were discussed too

* light up more of the fsharpqa tests on Mono
* light up more of the fsharp tests on Mono
* Don said [this eliding](https://github.com/fsharp/fsharp/blob/73d3e3afbc3df7f11f89f93db72bb2accad24cd5/tests/fsharp/core/run-all.fsx#L131) was indicative of some Mono bugs and that he had trimmed them down to minimal repros.  I'm trying to find those but no luck yet so we may need to recreate them

**Comment by dsyme** [comment]
@baronfel Super.  If you want to reorganize the README.md material in anyway (e.g. separate DEVGUIDE.md or the like) then feel free to do so in the PR

**Comment by Andrea** [comment]
it would be awesome to know if there are other things to do what are those? and or if we should have another Skype session

**Comment by dsyme** [comment]
I'll open a few github "Task" issues :)

**Comment by dsyme** [comment]
@Andrea there is this one: https://github.com/fsharp/fsharp/issues/499 :)

**Comment by Andrea** [comment]
nice, I'll try linux as I don't apple :D

Andrea
www.roundcrisis.com

**Comment by dsyme** [comment]
Closing for now (though the integration needs to be done again)
