### ISSUE TITLE
SqlDataConnection TypeProvider can't handle databases with tables having X and _X columns

### ISSUE THREAD

**Issue by mmv** [fsharp/fsharp#496]
Create a database where a table exists that has both a column named `something` and a column named `_something`. In this case the type provider will not work.

Apparently some class in a generated temporary CS file will contain two fields named `_something`, which is invalid.

**Comment by rojepp** [comment]
This PR should probably be directed at [visualfsharp](https://github.com/Microsoft/visualfsharp). Changes flows from there to here. Changes targeted at improving cross-platform issues should go here.

**Comment by dsyme** [comment]
Yes agreed.  Closing this here, please reopen in Microsoft/visualfsharp.
