### ISSUE TITLE
Investigate building on multiple machine configurations/mono versions using Travis

### ISSUE THREAD

**Issue by baronfel** [fsharp/fsharp#499]
Don mentioned wanting to set up some sort of build matrix for OSX and Linux on Travis.

It looks like there is a beta Travis CI feature to specify an OS, using

```
os:
    - linux
    - osx
```

This variable can be referenced in our build invocation scripts by using $TRAVIS_OS_NAME

And you can even specify mono versions using

```
mono:
    - latest
    - alpha
    - beta
    - VERSION_DESIRED
```

**Comment by dsyme** [comment]
See 500
