### ISSUE TITLE
Task: Enable more testing on Mono

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp#507]
The testing run on Mono is limited to  what's in travis.yml, i.e.
- bootstrap
- compile and run a script run-opt.sh which includes many of the fsharp\core tests, but not all
- compile a lot of projects from various sources.

This could be improved, e.g.
- run more tests from fsharp\core
- run the FSharp.Core NUnit unittests DLL. This gets [built](https://github.com/fsharp/fsharp/blob/master/.travis.yml#L9) but NUnit is not actually run on the output

Harder is:
- run some of the test assets from Microsoft's tests\fsharpqa suite, which is elided from this repo (though this is difficult as the test infrastructure is somewhat obscure)

Generally we can assume that Microsoft's testing has been run over the code coming into this repo, so we prioritize testing relevant to Mono, particularly things that flush out problems in the GC, JIT, VM, libraries and XBuild.

**Comment by baronfel** [comment]
I think the first step in this should be to create windows and osx/unix runners for the nunit tests that @enricosada has introduced, and then we can more easily add tests in the areas you specify above to that suite.  Plus then we can add those test runs to the CI builds to gain more confidence in the build.

**Comment by enricosada** [comment]
i'll do that, i am checking the last failing tests on windows (only 2/1018), after that i'll fix the xplat.

Next step is convert the tests/fsharpqa to nunit (like tests/fsharp). That shoulb be a lot easier, the code is already there, need to convert only run.pl and read xml header of files

**Comment by enricosada** [comment]
as a note, @PatrickMcDonald created the nunitlite runner ( see Microsoft/visualfsharp#748 )

**Comment by dsyme** [comment]
Closing as we will add the testing first in the Microsoft/visualfsharp repo
