### ISSUE TITLE
Improving fsharpi

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#508]
I'm sorry if this is not the right place to address this. If you would like me to move this discussion, I can, just tell me where.

The issue is that fsharpi is pretty annoying to work with. I've used other repls; mostly rbi and clojure's, so that's what I'm comparing with:
- CTRL+L doesn't scroll/clear the buffer
- CTRL+A doesn't move the cursor to the first char of the current edit-line
- CTRL+W doesn't delete the current symbol behind the cursor
- CTRL+E doesn't move the cursor to the last char of the current edit-line
- On OS X the fsharpi buffer sometimes jumps/scrolls erratically in zsh
- CTRL+C once should clear the line
- CTRL+C twice should say "Press CTRL+C one more time to close the interactive"
- CTRL+C thrice should terminate the interactive
- When I'm inside `#load "C` and do **TAB**, I would like it to hint with files which are in the current source directory. Now, it looks like this (after I tried to delete the bad word): <img width="247" alt="screen shot 2015-10-23 at 17 25 16" src="https://cloud.githubusercontent.com/assets/193115/10697215/1911aa92-79ab-11e5-8ae0-83dc8563991c.png">
- It would be nicer if the text/code was colourised as it's typed and evaluated, right now it's pretty drab
- Let's say I want to write:

```
let h =
  4;;
```

I press ENTER and now I want to redefine it. I press UP arrow, and now it's:

<img width="179" alt="screen shot 2015-10-23 at 17 10 39" src="https://cloud.githubusercontent.com/assets/193115/10696578/ff425abe-79a8-11e5-8259-7f55ba18ff9c.png">

It should really let you edit the buffer including newlines, rather than forcing you to remember and keep track of the order with which the lines were originally written. This is especially annoying when the functions are more than two lines and/or you've pasted something into the interactive.
- It would be great if there was a command line switch to fsharpi to ignore the topmost module or auto-open it, because then I wouldn't have to qualify the module whenever I load it through `fsharpi mymodule.fs` and it would just 'give me the contents of the module/file I point to'.
- Getting access to code-doc like clojure lets you, inside the interactive would be great
- Alternatively it would be great with more official support for iFsharp/iPython notebooks with F#, including guides on how to configure it.
- Using TAB should do code-completion e.g. like zsh does it:
  <img width="384" alt="screen shot 2015-10-23 at 17 10 07" src="https://cloud.githubusercontent.com/assets/193115/10696572/f092ec36-79a8-11e5-9b9f-7c76e82510c1.png"> This is what it looks now when I try to complete `Length` on an array: <img width="146" alt="screen shot 2015-10-23 at 17 27 19" src="https://cloud.githubusercontent.com/assets/193115/10697280/63b108ae-79ab-11e5-8f93-d76533412068.png">
- It would be nice if I could execute commands from the fsharpi without necessarily leaving it; e.g. `#e pwd;;` would run `pwd` in a shell as a child process and pipe its output to the buffer when it's finished.
- Implement an alternative to `;;` e.g. SHIFT+ENTER to evaluate the code so I don't have to hurt my pinky. Or on a Swedish keyboard, I have to press SHIFT+COMMA, SHIFT+COMMA, ENTER to evaluate it, which sometimes can be frustrating when you don't have both hands on the keyboard.
- When I've started typing something, and press UP, perhaps it could only select to show textblocks starting with the substring I've typed?
- CTRL+R would be nice; reverse search.

**Comment by 7sharp9** [comment]
We can fix some of those things in the fsi pad in XS, we just added syntax highlighting for example.  

The stand alone fsharpi I is pretty clunky by todays standards, almost every language has a better repl.

I do have a partially completed new repl that Ive been working on with some modern features...

**Comment by yever** [comment]
Regarding the last point, I made a [suggestion](https://fslang.uservoice.com/forums/245727-f-language/suggestions/10100028-fsi-execute-without-evaluation-by-pressing-enter) on "F# Language Design User Voice" to allow quick evaluation of chunks that evaluate to unit with ENTER.

I didn't get any response there (I admit it wasn't very succinct). This would allow to use FSI as an interactive shell to quickly run .NET methods (using ``|> ignore`` if a functions happens to return an unneeded value). Besides being a wonderful functional language, F# is also very compact and useful as a scripting language in a slightly more imperative style. 

I think it would be great to be able to use it without having to type those semicolons, and without cluttering the screen with the result of the evaluation, that in the case of a function that evaluates to unit is anyway not very insightful.

**Comment by enricosada** [comment]
@haf great idea, fsi really need some love.

I'd like to help, can we chat about it? maybe a better place is visualfsharp repo.

I think instead of improve fsharpi directly, we should create a standalone library for a "interactive terminal ui", without f# code evaluation.
We can ask for help in the community, contribution is going to be easier that full fsharpi because we leave out the eval

We can add stuff like

- history
- coloring of output
- multiline input/buffer
- autocomplete
- shortcuts
- commands ( like `#command` )
- async evaluation of i/o (as console input, console output)
- pretty much your wish list

**not bound to f#**, that's because is easier to iterate, develop and test.

Separating the code on interactive ui from f# eval, it's a lot easier to mantain. 
Now fsi/fsharpi is more entangled than needed (not too bad) but the pr merge on visualfsharp/fsharp is slow.

When stable, we can reference the nuget from fsi project, and
- use the new libreary in fsharpi/fsi
- cleanup old interactive code, but leave basic repl code for the test suite (so we can use the current fsi test suite without modifications) or do a compatible output.
- improve the fsi test suite, separate repl (input -> eval -> expected output) from multiline/commands/shortcuts

We can discuss about this if it's a good roadmap in the visualfsharp repo (there is now a standup with visualfsharp team the monday)

I dont want to start a project like this alone, but with another one is going to be fun greenfield project And a good one to start f# if someone in the community want to help.

I think we should modularize more the fsharp repo, extract stuff as libraries or use existing where possibile (for example command line parsing etc)

/cc @7sharp9 @yever @dsyme

**Comment by haf** [comment]
@enricosada If you want to chat, you could add h.feldt on skype and we can decide a time. Towards weekends is normally when my schedule allows me indulgences like this ;)

**Comment by dsyme** [comment]
The list of things mentioned by @haf at the top of this thread seem appropriate contributions for this repo.  You could also propose them for Microsoft\visualfsharp (and especially for CoreCLR fsi) but I think they are specifically associated with *nix so can be submitted here first.

For more sophisticated super-repl features you might like to start a new greenfield project built on FSharp.Compiler.Service.  Or you can submit them here, or Microsoft\visualfsharp, but it would be good to disentangle a bit.  Additions to the FCS API may be needed.

**Comment by enricosada** [comment]
@haf sent request in skype

**Comment by 7sharp9** [comment]
I think everything needed is in FCS, anything I needed for Xamarin sketches I added to FCS anyway :-)

A green field project is the way to go I reckon.

**Comment by dsyme** [comment]
See also discussion here: https://twitter.com/dsyme/status/676828486217113600

**Comment by rmunn** [comment]
Incorporating the new [Readline for .Net library](https://github.com/tsolarin/readline) (MIT licensed) into FSI would solve some (but not all) of these problems. Or if the green field project mentioned above ever happens, the Readline library may be a good starting point for the project.

**Comment by nosami** [comment]
You might also consider using [rlwrap](https://github.com/hanslub42/rlwrap). I've used it before with REPLs that don't have native readline bindings.

**Comment by tobia** [comment]
@nosami rlwrap works well on completely "dumb" repls, such as Oracle's sqlplus or Kona's k. But fsharpi already has a few line-processing features and they interfere with rlwrap.

By the way, I discovered by chance that Esc clears the current line. Very useful, but I would have never guessed. Usually it's Ctrl-U + Ctrl-K, to clear characters both sides of the cursor (or just Ctrl-U on annoying repls like MySQL.)

Right now this is what seems to be present:

- Ctrl-A, Ctrl-E: move to bol / eol
- horizontal arrows or Ctrl-B, Ctrl-F: move inside the line
- vertical arrows or Ctrl-P, Ctrl-N: history, but somewhat naive; it should treat every `;;` block as a single history item
- delete / backspace or Ctrl-D, Ctrl-H: delete char before / after cursor
- Ctrl-K: delete to eol
- Esc: clear whole line
- Ctrl-C: interrupt
- Ctrl-D on an empty line: eof / exit

**Comment by nosami** [comment]
Yeah. I think I tried to use it after posting and it didn't work. Forgot to update the issue!

I also just noticed `--consolecolors[+|-]         Output warning and error messages in color` 

Works great in OSX, maybe I should make it the default.

<img width="526" alt="screen shot 2018-09-26 at 13 46 12" src="https://user-images.githubusercontent.com/667194/46080703-8e34a180-c192-11e8-9bb8-3d22c3a1cdcd.png">

**Comment by nosami** [comment]
I just took a look at `csharp` on Mono. Seems to have nice readline support.

<img width="369" alt="screen shot 2018-09-26 at 14 02 09" src="https://user-images.githubusercontent.com/667194/46081607-d785f080-c194-11e8-965c-5e948bdc9007.png">

It might be interesting to do autocomplete this way too.

**Comment by voronoipotato** [comment]
> 
> 
> See also discussion here: https://twitter.com/dsyme/status/676828486217113600

Hey Don, that discussion doesn't load for me. Do you have any backups I guess?

**Comment by dsyme** [comment]
@voronoipotato No, sorry, I don't have that backed up.  I wonder what happened to it

**Comment by dsyme** [comment]
Closing as any improvements to "fsharpi"  should go to Microsoft/visualfsharp, or a community project should be started for a "super-REPL"
