### ISSUE TITLE
Unions with 4 or more cases silently fail to utilize UseNullAsTrueValue.

### ISSUE THREAD

**Issue by bryanedds** [fsharp/fsharp#510]
Repro. case in F# 4.4.0.0 -

[<CompilationRepresentation (CompilationRepresentationFlags.UseNullAsTrueValue)>] type T = A | B of int | C of int | D of int;;
A;;

In F# interactive, here you'll see that A is a proper value, which is not desired.

[<CompilationRepresentation (CompilationRepresentationFlags.UseNullAsTrueValue)>] type T = A | B of int | C of int;;
A;;

In F# interactive, here you'll see that A is a null, which is desired.

Would be a nice optimization to have this work in general. Barring that fix, a warning or error about this missing functionality might be in order.

Cheers!

**Comment by enricosada** [comment]
hi @bryanedds , this repo is for cross platoform packaing ( see http://fsharp.github.io/2014/06/18/fsharp-contributions.html for a guide) can you create or move this issue to [Microsoft/visualfsharp](https://github.com/Microsoft/visualfsharp) repository? 

About this issue, there is a constant [UnionReprDecisions.TaggingThresholdFixedConstant](https://github.com/Microsoft/visualfsharp/blob/2d413fb940aa1677688454c50b8ec05cd3b6f78f/src/ilx/EraseUnions.fs#L58) = 4, below this value the UseNullAsTrueValue is applied.

This is used [here](https://github.com/Microsoft/visualfsharp/blob/2d413fb940aa1677688454c50b8ec05cd3b6f78f/src/ilx/EraseUnions.fs#L74-L75)

I dont know the history about of this decision, @dsyme ? we need to add a warning (error?) or remove this check?

**Comment by bryanedds** [comment]
Issue moved to - https://github.com/Microsoft/visualfsharp/issues/711
