### ISSUE TITLE
fsharp not available in homebrew

### ISSUE THREAD

**Issue by naveensrinivasan** [fsharp/fsharp#512]
I tried `brew install fsharp` I got response No available formula with the name "fsharp"

```
Last login: Sun Nov 15 20:56:23 on ttys000
MacBook-Pro:~ naveen$ brew install fsharp
Error: No available formula with the name "fsharp"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
MacBook-Pro:~ naveen$ uname -a
Darwin MacBook-Pro.home 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
MacBook-Pro:~ naveen$

```

Then I used `brew install mono` which got me fsharp.

**Comment by inosik** [comment]
There were some issues with `.props` and `.targets` files, so the F# package comes with mono now.

It used to be a separate package until one or two months ago.

**Comment by rneatherway** [comment]
@naveensrinivasan did you see instructions somewhere to install an 'fsharp' formula? As @inosik says, I've merged the fsharp and mono formulas together.

**Comment by naveensrinivasan** [comment]
@rneatherway Thanks. Would we want to remove the fsharp from the brew.

**Comment by rneatherway** [comment]
I don't quite understand the question. What are you asking exactly?

**Comment by naveensrinivasan** [comment]
I meant this option `brew install fsharp` shouldn't be available in brew going forward. It was suggestion.

**Comment by rneatherway** [comment]
Well, it isn't available, that's what the error message told you. If you put any random string there you will get the same message.
