### ISSUE TITLE
Upgrade Travis infrastructure used to run unit tests

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#520]
https://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

As can be seen at the top of the travis builds.

**Comment by rneatherway** [comment]
The dockerised builds are not allowed to use `sudo`, which we do: https://github.com/fsharp/fsharp/blob/master/.travis.yml#L19

I'm not sure if the `sudo make install` step is actually needed for testing though.

**Comment by dsyme** [comment]
@rneatherway It is necessary right now since the testing we do assumes FSharp.Core is in the GAC among other things.

**Comment by rneatherway** [comment]
I see, in that case #522 isn't going to work.

**Comment by haf** [comment]
Can we remove the dependencies on the GAC? It's so 2002 anyway ;)
