### ISSUE TITLE
mapping option valued function yields list containing null

### ISSUE THREAD

**Issue by jmchapman** [fsharp/fsharp#529]
I have installed mono and f# via Xamarin Studio (stable channel).

$ fsharpi

F# Interactive for F# 4.0 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> (fun x -> if x then Some x else None) false;;
val it : bool option = None

> List.map (fun x -> if x then Some x else None) [false];;
val it : bool option list = [null]

**Comment by rneatherway** [comment]
I believe that this is just an artefact of the compiler using null as the representation for None. The same happens in Visual Studio. For some discussion see https://stackoverflow.com/questions/11959321/why-is-none-represented-as-null

**Comment by dsyme** [comment]
Yes, that's correct (and we'd love to see printing fixed to track types properly!)
