### ISSUE TITLE
Use the same AssemblyVersion for all versions of FSharp.Core meant to be backward compatible

### ISSUE THREAD

**Issue by binki** [fsharp/fsharp#532]
Putting the responsibility of putting AssemblyBindingRedirects on the application which may not be using FSharp directly itself just seems wrong. Within the .net framework, the application does not need to put AssemblyBindingRedirects for mscorlib for that application to be able to use a library targeting an old version of the framework. Now, it can manage this because the framework has full control over binding. And if the GAC is usable, you may specify redirections for your GAC assembly. But FSharp.Core is intended not to be in the GAC.

I think the point of having different AssemblyVersions for FSharp.Core is that you can have some assurance that if the assembly compiles against a certain version of FSharp.Core it won't be run against an older version of FSharp.Core. However, this is not guaranteed. For example, the binding redirection syntax would allow someone to redirect new version numbers of FSharp.Core onto an older FSharp.Core version, perhaps an FSharp.Core that is ABI incompabitle with the library. Also, the enforcement of version-based compatibility checking does not happen until dynamically at runtime. You won’t know that your assembly won’t run on .net until some code that calls into an F#-based library runs because assemblies are loaded lazily. So changing the AssemblyVersion to prevent someone from trying to use a library that requires at minimum a particular FSharp.Core version does not really help anybody. It just forces lots of people to tiresomely maintain binding redirects all over the place and even in codebases which don’t have a single line of F# in them.

What problem F# was trying to solve by changing AssemblyVersion for backwards-compatible updates? It seems to me that F# is updating the AssemblyVersion when it should be updating the AssemblyFileVersion instead…

Since the assembly binding version is not verified until runtime dynamically anyway, why not use some trick like a module initializer in each F# assembly that calls a method in FSharp.Core to verify that it is new enough and otherwise compatible? Then just freeze FSharp.Core’s Assembly version and update the F# compiler to inject the necessary loadtime version validation code into each F# library. Then any application consuming an F#-implemented library no longer has to even know that it is consuming an F#-implemented library. Supposedly nuget might be trying to become better at solving dependency problems in the future, so it might even be capable of deciding to use, say, FSharp.Core-4.4.1 (get those bugfixes!) when a program uses libraries A and B, library A requires FSharp.Core-4.3.0, and library B requires FSharp.Core-4.4.0 (all of which have the same AssemblyVersion, of course and all without redirects!).

**Comment by smoothdeveloper** [comment]
@binki this seems to make a lot of sense! I've spent significant time figuring issues with missing redirects (binding exceptions in dotnet are to blame on this I guess) and dependencies on several version of that assembly, which would have been totally avoided if the assembly was part of the .net framework proper (like mscorlib & all). 

The type of errors you get with all of this is also quite cryptic and that could be solved with the module initializer idea you describe.

Would it make sense to open this issue on Microsoft/visualfsharp repository instead of here?

**Comment by dsyme** [comment]
This issue should be opened as a UserVoice feature request, I guess at http://fslang.uservoice.com.   However I'm sceptical that the Microsoft Visual F# Tools team would follow your proposed path: the options above were considered by that team when deciding how to version FSharp.Core. TBH it's unlikely they'll revisit such fundamental decisions. 

n.b. Please also make sure you are following the guidelines here: http://fsharp.github.io/2015/04/18/fsharp-core-notes.html

Best
Don
