### ISSUE TITLE
C# supports arbitrary text for AssemblyInformationalVersion where as F# does not

### ISSUE THREAD

**Issue by ReverseBlade** [fsharp/fsharp#534]
With C# assemblies we can make use of the following attribute:
``[assembly: AssemblyInformationalVersion("FooBar")]``

as you see AssemblyInforationalVersion is arbitrary text and it compiles fine and emitted properly to target assembly.

With F# however compiler gives a warning that this is not valid:
``[  assembly:AssemblyInformationalVersionAttribute("FooBar") ]``

FSC: warning FS2003: An AssemblyInformationalVersionAttribute specified version 'FooBar', but this value is invalid and has been ignored
PS: this comment box does not support less than and greater than characters.

**Comment by enricosada** [comment]
the Microsoft/visualfsharp#605 fix should address this issue. 
There is a [test case](https://github.com/enricosada/visualfsharp/blob/e27e4d142635dc1a5c3a74acc857d4cbbfb7cc45/tests/fsharp/fsc/warnings/FS2003/Warning_FS2003.fs#L30-L40) with a free AssemblyInformationalVersionAttribute ( the warning is expected )

@ReverseBlade this comment box syntax is Markdown ( https://guides.github.com/features/mastering-markdown/ )
To write \> character, you can escape it with `\` like `\>`

**Comment by dsyme** [comment]
Closing this since it's covered by the above
