### ISSUE TITLE
Build Error in Linux

### ISSUE THREAD

**Issue by icp1994** [fsharp/fsharp#535]
$ make
...
make[3]: Entering directory '/home/carl/Downloads/fsharp/src/fsharp/FSharp.Build-proto'
MONO_ENV_OPTIONS= /usr/bin/xbuild /p:Configuration=Proto
XBuild Engine Version 12.0
Mono, Version 3.2.8.0
Copyright (C) 2005-2013 Various Mono authors

Build started 25-01-2016 13:42:12.
__________________________________________________
/home/carl/Downloads/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj: error : /home/carl/Downloads/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj: /home/carl/Downloads/fsharp/src/fsharp/FSharp.Build-proto/../../FSharpSource.targets: Project file could not be imported, it was being imported by /home/carl/Downloads/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj: /home/carl/Downloads/fsharp/src/fsharp/FSharp.Build-proto/../../../lib/bootstrap/4.0/Microsoft.FSharp.Targets: Project file could not be imported, it was being imported by /home/carl/Downloads/fsharp/src/FSharpSource.targets: Unable to parse condition "$(MSBuildExtensionsPath32.Contains('xbuild'))" : Expected a property at position 2 in condition "$(MSBuildExtensionsPath32.Contains('xbuild'))". Missing closing parantheses'.
Build FAILED.
Errors:

/home/carl/Downloads/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj: error : /home/carl/Downloads/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj: /home/carl/Downloads/fsharp/src/fsharp/FSharp.Build-proto/../../FSharpSource.targets: Project file could not be imported, it was being imported by /home/carl/Downloads/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj: /home/carl/Downloads/fsharp/src/fsharp/FSharp.Build-proto/../../../lib/bootstrap/4.0/Microsoft.FSharp.Targets: Project file could not be imported, it was being imported by /home/carl/Downloads/fsharp/src/FSharpSource.targets: Unable to parse condition "$(MSBuildExtensionsPath32.Contains('xbuild'))" : Expected a property at position 2 in condition "$(MSBuildExtensionsPath32.Contains('xbuild'))". Missing closing parantheses'.

         0 Warning(s)
         1 Error(s)

Time Elapsed 00:00:00.0917840
Makefile:9: recipe for target 'build-proto' failed
make[3]: *** [build-proto] Error 1
make[3]: Leaving directory '/home/carl/Downloads/fsharp/src/fsharp/FSharp.Build-proto'
Makefile:15: recipe for target 'build-proto' failed
make[2]: *** [build-proto] Error 2
make[2]: Leaving directory '/home/carl/Downloads/fsharp/src/fsharp'
Makefile:10: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/carl/Downloads/fsharp/src/fsharp'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
$

**Comment by Cyclic3** [comment]
I am having exactly the same problem

**Comment by Cyclic3** [comment]
I have fixed it (I think). Try removing line 71 (\<UsingXBuild Condition="$(MSBuildExtensionsPath32.Contains('xbuild'))">true\</UsingXBuild>)

**Comment by rneatherway** [comment]
You need Mono 4 or greater for that xbuild property to be interpreted correctly.

**Comment by Cyclic3** [comment]
I ran
`sudo apt-get remove mono-complete --purge`
`sudo apt-get install mono-complete`
I was pretty sure that would get me to the latest version of mono, but running mono --version gave
>Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu4)

I applied the mono suggested:
` sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
sudo apt-get update`

and then
' sudo apt-get dist-upgrade (because upgrade kept back packages)'

That got me onto version 4.2.1.

# It now compiles perfectly!

**Comment by knocte** [comment]
>You need Mono 4 or greater for that xbuild property to be interpreted correctly.

Robin, if we require Mono 4, we should raise the dependency version in the configure.ac file.

**Comment by rneatherway** [comment]
Yeah #536
