### ISSUE TITLE
Yield prevents implicit cast to interface type

### ISSUE THREAD

**Issue by FrankBro** [fsharp/fsharp#545]
Using yield when building a collection seems to prevent implicit cast to the interface type expected

```fsharp
type IFirst = interface end

type ISecond = 
    inherit IFirst

module Test = 
    let instance = { new ISecond }

    let test () =
        let a : IFirst list =
            [
                instance
            ]
        let b : IFirst list = 
            [
                yield instance
            ]
        ()
```

In this example, you will get an error for `b`:

```
This expression was expected to have type
    IFirst    
but here has type
    ISecond
```

**Comment by dsyme** [comment]
Right now this is by design.  Since this is a language change suggestion, please add it to http://fslang.uservoice.com.

**Comment by dsyme** [comment]
Closing as this should go in user voice as mentioned above please.  Thanks!

**Comment by smoothdeveloper** [comment]
https://fslang.uservoice.com/forums/245727-f-language/suggestions/13361034-implement-implicit-casts-for-yield
