### ISSUE TITLE
FSharp.Quotations.DerivedPatterns.(|SpecificCall|_|) not working properly with methods of generic types

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsharp/fsharp#546]
The active pattern works as expected when matching against generic methods
```fsharp
open FSharp.Quotations.DerivedPatterns

let m = (|SpecificCall|_|) <@ fun x y -> x + y @> <@ "a" + "b" @>
//val m : (Expr option * Type list * Expr list) option =
//  Some
//    (null, [System.String; System.String; System.String],
//     [Value ("a"); Value ("b")])
```
However it fails to properly handle methods of generic types:
```fsharp
let s = set [1]
let m' = (|SpecificCall|_|) <@ fun (s : Set<_>) e -> s.Contains e @> <@ s.Contains 0 @>
//val m' : (Expr option * Type list * Expr list) option = None
```
Is this by design?

**Comment by enricosada** [comment]
hi @eiriktsarpalis, this repo is for cross platform packaging ( see http://fsharp.github.io/2014/06/18/fsharp-contributions.html for a guide) can you create or move this issue to [Microsoft/visualfsharp](https://github.com/Microsoft/visualfsharp) repository? 

About your questions, i think quotation doesn support generic definition, see http://stackoverflow.com/questions/26710818/f-code-quotations-and-generic-functions
In the first example, the argument are `System.String`

But maybe someone else can give a final answer about that

**Comment by dsyme** [comment]
@enricosada You can refer to existing generic definitions, but can't define new expression-bound local generic functions within quoted expressions.  You can define them in ReflectedDefinition saved definitions

**Comment by dsyme** [comment]
@eiriktsarpalis I believe it is reasonable to make SpecificCall work over methods in generic classes, but there may be a reason why it's not supported.  We'd accept a PR for this that works correctly.

**Comment by eiriktsarpalis** [comment]
@enricosada yeah sorry, I accidentally navigated to this repo and didn't notice it until I had the issue posted.

I've got [this](https://gist.github.com/eiriktsarpalis/5ffc567e670733cf7833) alternative implementation that works as expected with methods of generic types.

@dsyme I think it would be wrong to attempt to fix the current implementation of `(|SpecificCall|_|)`. In general altering implementations of active patterns with holes is bound to break legacy code. Perhaps we could simply mark it as deprecated and add a separate implementation that works correctly.

**Comment by dsyme** [comment]
@eiriktsarpalis Yes, you're right. I suppose some name like ``SpecificGenericCall``

**Comment by dsyme** [comment]
Closing this since as @enricosada says i's the wrong repo for this.  @eiriktsarpalis please add a link to a uservoice request?
