### ISSUE TITLE
Constraint format...

### ISSUE THREAD

**Issue by gdennie** [fsharp/fsharp#550]
The following layout of constraints for a sample class should be possible. 

       GroupedFixtures<'A, 'B 
          when
             'A :> Remote.RemoteWebDriver and 
             'A : (new: unit -> 'A) and 
             'B :> ServerFixture            
          >() as this =

Presently it almost was but the `new()` constraint use of parenthesis caused problems. currently all the constraints layout forces them on the same line which is not as clear or convenient (note the text, that `>() as this`, is allowed on a separate line):

       GroupedFixtures<'A, 'B when 'A :> Remote.RemoteWebDriver and 'A : (new: unit -> 'A) and 'B :> ServerFixture            
          >() as this =

**Comment by gdennie** [comment]
I will leave this suggest up but I think it can be closed since the need is considerably diminished. It seems these constraints can be resolved with lambdas...

      type GroupedFixtures
         (
            ctorDriver : unit -> IWebDriver, 
            ctorSite : unit -> ServerFixture
         ) as this  =

**Comment by dsyme** [comment]
Suggestions go to http://fslang.uservoice.com. Please see CONTRIBUTING.md.
