### ISSUE TITLE
How about allow flexible types in default constructor constraints...

### ISSUE THREAD

**Issue by gdennie** [fsharp/fsharp#551]
This would permit, 

    let ctor<'a when 'a:(new: unit -> #IWebDriver)> : unit -> IWebDriver = ...

versus

    let ctor<'a when 'a:(new: unit- > 'a) and 'a :> IWebDriver> = fun () -> new 'a() :> IWebDriver

**Comment by dsyme** [comment]
Suggestions go to http://fslang.uservoice.com. Please see CONTRIBUTING.md.
