### ISSUE TITLE
WdslProvider Accept both https and http for single type

### ISSUE THREAD

**Issue by jon49** [fsharp/fsharp#557]
I have a service that uses `https` when in production mode, but uses `http` for dev and beta mode. Real annoying and it should use https for everything. Anyways, is there a way to dynamically make it a type for both conditions?

This is basically the error:

`The provided URI scheme 'https' is invalid; expected 'http'`

I can dynamically change the endpoint address. But there doesn't appear to be a way to change the transportMode.

As seen here:
https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Data.TypeProviders/TypeProviders.fs#L984

**Comment by dsyme** [comment]
Please enter this as an issue in https://github.com/fsprojects/FSharp.Data.TypeProviders, and if possible provide a tentative fix too. Thanks!

**Comment by dsyme** [comment]
Closing this since development on the WSDL type provider has moved to the above repo.
