### ISSUE TITLE
[XBuild] ResX resources in sub-directories are missing the directory name 

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp#562]
Looking at the output for compiling `tests\projects\Sample_VS2012_FSharp_ConsoleApp_net45_with_resource`, it is easy to see that for F# on Linux, ResX resources are missing their subdirectory names . On Windows, the subdirectory names are added

For example, for that project compiled using MSBuild on Windows, the command line argument is :

```
--resource:obj\Debug\SubDir.ResxResourceInSubDir.resources 
```

giving this in the ILDASM of the output:

```
.mresource public SubDir.ResxResourceInSubDir.resources
```

For the same project compiled using XBuild on Linux, the command line argument is:

```
--resource:obj/Debug/ResxResourceInSubDir.resources 
```

giving:

```
.mresource public ResxResourceInSubDir.resources
```

**Comment by knocte** [comment]
Shouldn't this be reported in bugzilla.xamarin.com ?

**Comment by dsyme** [comment]
@knocte It's a bug in F# on Mono on Linux, it doesn't show up for .csproj,   The fix may be in Mono but we'd need to work it out first.

**Comment by dsyme** [comment]
Closing this as wont-fix

A workaround is to use ``msbuild`` on Linux (``xbuild`` is basically being deprecated slowly).
