### ISSUE TITLE
Note: Microsoft.FSharp.Targets --> Microsoft.FSharp.targets in source tree, but not in distributions!

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp#564]
Just a minor note for the records….

In a recent checkin (I think one by @otawfik-ms) we renamed

    Microsoft.FSharp.Targets --> Microsoft.FSharp.targets

This is OK, but just creating this issue to record the fact that all existing .fsproj files in the world use the capitalized names in their targets references.  

The renaming causes no harm on Windows or OSX. However, _the Mono editions of F# and the FSharp.Compiler.Tools package_ (both published from this repo) need to be careful to make sure the targets file is still called Microsoft.FSharp.Targets (capitalized).  This sucks and derives from a mistake made by Microsoft in Visual F# 2.0, but it’s now part of the Linux/Mono backwards compat for F#.

Summary:

•	Microsoft.FSharp.Targets : Must be used un any distribution of F# for Mono+Linux or any case-sensitive file system using MSBuild 
•	Microsoft.FSharp.Targets or Microsoft.FSharp.targets : Used in the Visual F# Tools distribution (on Windows it doesn't matter).
•	Microsoft.FSharp.targets : Used in the source tree as of 08/04/2016 (prior this was Microsoft.FSharp.Targets) 

-

**Comment by otawfik-ms** [comment]
Do you mean this?
https://github.com/Microsoft/visualfsharp/commits/master/src/fsharp/FSharp.Build/Microsoft.FSharp.targets
Can you please mention the commit causing that change?

**Comment by otawfik-ms** [comment]
I see here I 2 year old commit by @enricosada 
https://github.com/fsharp/fsharp/commits/master/src/fsharp/FSharp.Build/Microsoft.FSharp.Targets

**Comment by dsyme** [comment]
@otawfik-ms Yeah, it wasn't anything by you :) Sorry!

I think what's happened is that the capitalizations have just always been different in the two repos, but for the first time an actual change to the file has been propagated through - the copyright notice change here: https://github.com/Microsoft/visualfsharp/commits/master/src/fsharp/FSharp.Build/Microsoft.FSharp.targets. One problem is that git doesn't handle this case at all well on Windows, and it sometimes leaves your local repo in a whacky state.

In any case, this repo now aligns with Microsoft\visualfsharp and uses a _lowercase_ name in the source file in the repo.  However when it is deployed on Mono/Linux, it must be _uppercase_ as mentioned above.

**Comment by dsyme** [comment]
I'll close this as it's just a comment.

**Comment by knocte** [comment]
> In any case, this repo now aligns with Microsoft\visualfsharp

I see you added info about this in this commit: https://github.com/fsharp/fsharp/pull/558/commits/5953f529a755fa4b421d925bf8ff87a265d26751

But where is the actual rename?

> One problem is that git doesn't handle this case at all well on Windows, and it sometimes leaves your local repo in a whacky state.

A solution (workaround) to this is to do a 2step rename: 
1. Rename to *.targetsTEMP
2. Rename to *.Targets

I think consistency is important here. If I create a PR to do this in Microsoft/visualfsharp/, will it be accepted?

**Comment by enricosada** [comment]
i think i have aligned the wrong side in my commit (i was minimizing diff of the two repos), i used visualfsharp as the gold and renamed the fsharp/fsharp . sry

btw to do a case sensitive rename in windows without issues:

```
git mv Microsoft.FSharp.targets tempfile
git mv tempfile Microsoft.FSharp.Targets
```

and you can git add + commit.

**Comment by knocte** [comment]
> btw to do a case sensitive rename in windows without issues:

Yup, exactly what I said ;-)

> i used visualfsharp as the gold and renamed the fsharp/fsharp . sry

Is that a `yes` answer to my question?

**Comment by enricosada** [comment]
@knocte all the msbuild files i see use a lowercase `.targets` extensions.

from

- `C:\Program Files (x86)\MSBuild\12.0\Bin`
- `C:\Program Files (x86)\MSBuild\14.0\Bin`

and **usually are imported lowercase**
```
$(MSBuildBinPath)\Microsoft.CSharp.targets
```

**but the import in f# project use uppercase** ( ref https://github.com/Microsoft/visualfsharp/tree/master/vsintegration/ProjectTemplates for example the [console template](https://github.com/Microsoft/visualfsharp/blob/d7afa8384ad6c6c4adbe4d7df74ac954eac0306c/vsintegration/ProjectTemplates/ConsoleProject/Template/ConsoleApplication.fsproj#L67-L72) )

So yes, i think should be uppercase.

@knocte i commited wrong, i'll send to visualfsharp a pr. as you said it's important (visualfsharp it's going xplat soon, so it's needed i think)

**Comment by KevinRansom** [comment]
@dsyme I have fixed the visualfsharp repo to capitalize the durned thing.  So we should now be consistent and use capitalized targets throughout for Microsoft.FSharp.Targets and Microsoft.Portable.FSharp.Targets.

All other targets are correctly lowercased.

https://github.com/Microsoft/visualfsharp/pull/3176
