### ISSUE TITLE
Add .NET Core to FSharp.Core nuget package

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp#566]
The [FSharp.Core](https://www.nuget.org/packages/FSharp.Core) nuget package is currently authored from this repo. 

It would be great to start adding .NET Core versions of FSharp.Core to this nuget package, as this will make it easier for clients to use FSharp.Core.

My understanding is that Microsoft will make a package for the signed FSharp.Core we need to include, and we just need to either merge this package into FSharp.Core or list it as a dependency. I'm a bit unclear what the canonical source of this package will be
- There is this on nuget: https://www.nuget.org/packages/Microsoft.VisualFSharp.Core.Redist/
- @enricosada uses this today `source https://www.myget.org/F/fsharp-daily/api/v3/`, [browse here](https://www.myget.org/gallery/fsharp-daily).

**Comment by enricosada** [comment]
We are going to have alignment issues, a lots if we have two (or more) packages, and not from maintainer side but from develper side.

nuget support packages with multiple frameworks. we should use that and have a single `FSharp.Core`.

but merge different versions of assemblies in same package is a bad hack, features/bugs may change.

for example, if we add the new `FSharp.Core.dll` built for .NET Core to current packages, is not right, because that mean the package contains two different versions of same dll

- net46 => version 4.0.0.x
- netstandard1.5 => version built from latest commit of master branch

A packages should contain the assemblies built from same commit

**Comment by dsyme** [comment]
@enricosada Yes, agreed (the current package contains version 4.4.0.0 in net40).  Note sure what to do about that since we only like to put the finalized, signed netfx FSharp.Core in the package.  

We could just wait, of course, and accept that there are two FSharp.Core packages until 4.4.1.0 comes out.

**Comment by masaeedu** [comment]
So if I understand correctly, the plan is to wait until the next stable release of FSharp.Core, and distribute the NETStandard compatible bits with that? Will this mean `FSharp.Core.netcore` will disappear?

**Comment by masaeedu** [comment]
Also, when this does end up being released, would it be possible to target a lower .NET Standard API, e.g. 1.3? This would greatly increase the backwards compatibility of the library.

**Comment by enricosada** [comment]
ref #659

**Comment by enricosada** [comment]
done by https://www.nuget.org/packages/FSharp.Core/4.1.0

**Comment by masaeedu** [comment]
@enricosada I'm going to reiterate my request here; can this be targeted at a lower version of .NET Standard. Right now there are barely any runtimes that support .NET Standard 1.6, and the official advice is to use 1.4 until 2.0 is ready.

**Comment by dsyme** [comment]
cc @cartermp @KevinRansom 

@masaeedu Please add a specific request for this to http://github.com/Microsoft/visualfsharp, as the choice of .NET Standard originates from there

> Right now there are barely any runtimes that support .NET Standard 1.6, and the official advice is to use 1.4 until 2.0 is ready. 

The FSharp.Core package includes Profile259, Profile78, Profile7 binaries if you want to use those instead as the basis for your libraries. It also includes .NET 4.5 of course 

> Additionally, many of the APIs that are available in .NET Standard 1.5 and 1.6 are going to be removed in 2.0

My impression was that this had been cancelled and that 2.0 would be compatible with 1.6.  Does anyone have a latest authoritative reference link?  thank you

**Comment by enricosada** [comment]
@masaeedu see https://github.com/fsharp/fsharp/issues/669 for lower version. it should be really lower. there is not a real reason atm, just need to be fixed in microsoft/visualfsharp (we use same deps, target version of `Microsoft.fsharp.core.netcore` package)

**Comment by masaeedu** [comment]
@enricosada Thanks. Is there an issue to watch on microsoft/visualfsharp for this or does one need to be created?

**Comment by enricosada** [comment]
@masaeedu  https://github.com/Microsoft/visualfsharp/issues/2501
