### ISSUE TITLE
Record equality doesn't check potential recursion and can cause infinite loop

### ISSUE THREAD

**Issue by Horusiath** [fsharp/fsharp#570]
When provided a record definition with possible recursive field definition, an instance of that record may cause `StackOverflowException` during the equality check.

#### Repro steps

```fsharp
type TypeDef = {
    Name: string
    mutable Fields: FieldDef list
}
and FieldDef = {
    Name: string
    Type: TypeDef
}

let Int = { Name = "Int"; Fields = [] }
let Complex = { Name = "Complex"; Fields = [{ Name = "X"; Type = Int}] }
Complex.Fields <- { Name = "Deep"; Type = Complex } :: Complex.Fields

// This line will cause StackOverflowException
Complex = Complex
```

#### Expected behavior

Equality check should return true.

#### Actual behavior

On checking equality with itself, instance causes `StackOverflowException`.

#### Known workarounds

I'm not aware of current implementation, but I guess that simple check `Object.ReferenceEquals(x, y)` at the beginning could solve the problem in the case of `x = x`. Further problems may occur however, when we'll try to make a structural equality on two different instances, that are not reference equal, but still are structurally equal.

#### Related information 

* Operating system: Windows 8.1
* .NET Framework 4.5, F# 4.0 (Fsharp.Core, 4.4.0.0) 
* Editing Tools: Visual Studio 2015, Visual Studio Code 1.0 + Ionide

**Comment by forki** [comment]
Moced to https://github.com/Microsoft/visualfsharp/issues/1085
