### ISSUE TITLE
Compiler allows exporting type abbreviations that mention private types

### ISSUE THREAD

**Issue by Porges** [fsharp/fsharp#572]
The compiler doesn't currently prevent you exporting an alias for a private type, but it probably should. 

#### Repro steps

That is, given this code in an assembly:

```fsharp
module Library
type private Hidden = Hidden of unit
type Exported = Hidden
```

#### Actual behavior

Using this from *another assembly* can produce unexpected results:

```fsharp
// in the consuming executable...
open Library

[<EntryPoint>]
let main argv =
    let x : Exported = Unchecked.defaultof<_>
    printfn "%A" x
    0
```

Giving:

```
Unhandled Exception: System.MethodAccessException:
Attempt by method 'Program.main(System.String[])' to access method
'Microsoft.FSharp.Core.PrintfFormat`5<System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon>..ctor(System.String)' failed.
```

#### Expected behavior

The desired behaviour would be that a type abbreviation that mentions private types must also be private. This is how functions and "real" types work - neither of these are accepted:

```fsharp
type ExportedRealType = Bad of Hidden
let printExported (_ : Exported) = printfn "How did you get that?"
```

I had a quick look in the specification to find anything about this but wasn't able to.

#### Related information 

Provide any related information 

* F#: 4.0 (Core 4.4.0.0)
* Operating system: Windows 10
* .NET Runtime, CoreCLR or Mono Version: 4.5
* Editing Tools: VS2015 Update 2

**Comment by dsyme** [comment]
I haven't yet reproduced the behavior above.

Could you use the issue template please, with exact "Repro", "Actual" and "Expected" steps, and compiler versions etc?  I

```
type private Hidden = Hidden of unit
type Exported = Hidden

let x : Exported = Unchecked.defaultof<_>
printfn "%A" x

```

gives

```
a.fs(5,5): error FS0410: The type 'Hidden' is less accessible than the value, member or type 'val x : Exported' it is used in
```

while this code:
```

type private Hidden = Hidden of unit
type Exported = Hidden


let  private x : Exported = Unchecked.defaultof<_>
printfn "%A" x
```
gives
```
<null>
```

Splitting the code into multiple modules gives errors too.  This is all with the F# 4.0 ``fsc.exe`` compiler on Windows. ``fsi.exe`` gives similar results. However it seems there is some other variation that needs to be tried?

I do agree that it would be reasonable to give the error on the abbreviation

**Comment by Porges** [comment]
> I didn't try multiple assemblies

This is what is needed to reproduce the error.

I've reformatted the issue according to the template and made it more explicit that you need to put the consuming code in another assembly, hope that helps.

**Comment by dsyme** [comment]
OK, thanks.  Yes, that is a bug.  We actually need to reopen this under http://github.com/Microsoft/visualfsharp since it's not a Mono-specific issue (we use this repo to track Mono issues).  Could you do that for me please?

**Comment by Porges** [comment]
Ah, I thought there was something like that but didn't find it as I was looking under the `fsharp` organization. Moved it now, thanks.
