### ISSUE TITLE
Fsharpi throws OutOfMemoryException

### ISSUE THREAD

**Issue by arctiq1** [fsharp/fsharp#578]
Running this code as a whole causes a OutOfMemoryException, while in parts it works as expected:
```fsharp
//Part 1
type Enu = A=1
//Part 2
[|Enu.A|]
seq[ Enu.A ] |> Seq.windowed 1 |> Seq.map id
```
Should result in seq\<Enu[]\>, but results in OutOfMemoryException, when executed all at once.

#### Related information 
On windows with fsi 14.0.23413.0 it works, on fedora with fsharpi version from repository it doesn't.

Sorry if this is a problem on my part.

**Comment by dsyme** [comment]
This must be a Mono problem.  Could you run ``mono --version`` please.  It would be good to check against the latest packages available from http://fsharp.org/use/linux

**Comment by arctiq1** [comment]
```
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Tue Mar 15 11:39:54 EDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

```

**Comment by arctiq1** [comment]
I have just tried to re-add and update repositories and packages as per the fsharp.org guide, but no change.

**Comment by Banashek** [comment]
Happening in docker with fsharp/fsharp:latest image as well.

```
> type Enu = A=1;;

type Enu =
  |  A  =  1

> [|Enu.A|];;
val it : Enu [] = [|A|]
> seq[ Enu.A ] |> Seq.windowed 1 |> Seq.map id;;
val it : seq<Enu []> = seq [[|A|]]
> type Enu = A=1
- [|Enu.A|]
- seq[ Enu.A ] |> Seq.windowed 1 |> Seq.map id;;
System.OutOfMemoryException: Out of memory
  at (wrapper alloc) System.Object:AllocVector (intptr,intptr)
  at <StartupCode$FSI_0006>.$FSI_0006.main@ () <0x42220560 + 0x00032> in <filename unknown>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x7ffa755ab960 + 0x000a1> in <filename unknown>:0
Stopped due to error
>
```

**Comment by dsyme** [comment]
Please make sure a Mono bug is entered for this on the Xamarin bugzilla bug tracking system

**Comment by arctiq1** [comment]
Added it as [OutOfMemoryException while working with seq: id 41970.](https://bugzilla.xamarin.com/show_bug.cgi?id=41970)
Hopefully it's correct, I have no experience with either bug tracking system.

**Comment by dsyme** [comment]
Tracked in Mono - please ping them there if this continues to be an issue
