### ISSUE TITLE
Augmented members considered incorrect even though all conditions are satisfied

### ISSUE THREAD

**Issue by xperiandri** [fsharp/fsharp#581]
I want to compile such a piece of code

``` F#
namespace Models

type ElementList = LineElement ImmutableList

type LeadingLine =
    { Elements : ElementList
      InputEnding : Ending
      OutputEnding : Ending }

namespace Models.Operations

open Models

module LeadinLine =

    let insertElement line index element =
        { line with Elements = line.Elements.Insert(index, element) }

    let removeElement line element =
        { line with Elements = line.Elements.Remove(element) }

    let replaceElement line replacableElement replacementElement =
        { line with Elements = line.Elements.Replace(replacableElement, replacementElement) }

    let containsElement line element =
        line.Elements.Contains(element)

namespace Models

open Models.Operations.LeadinLine

type LeadingLine with
    member line.Contains = containsElement line
    member line.Insert = insertElement line
    member line.Remove = removeElement line
    member line.Replace = replaceElement line
```

And all the conditions are satisfied: same file, same namespace.

#### Expected behavior

Successful compilation

#### Actual behavior

`error FS0644: Namespaces cannot contain extension members except in the same file and namespace where the type is defined. Consider using a module to hold declarations of extension members.`

#### Related information 

* Windows 10 Pro 14372
* PCL Profile259
* Visual Studio 2015 Enterprise Update 2
* Severity: I can't achieve my goal

**Comment by dsyme** [comment]
@xperiandri It must be the same namespace declaration group. The error message should be clarified.  Either way, this should go in http://github.com/Microsoft/visualfsharp, see README.md

**Comment by xperiandri** [comment]
Why does such a weird restriction exists?
What is not valid in my scenario?
