### ISSUE TITLE
FSharp 4.0.1.5 failed to build on Arch Linux

### ISSUE THREAD

**Issue by fusion809** [fsharp/fsharp#591]
Hi,

I tried to build this program with `./autogen.sh --prefix=/usr && make` and it gave the error:

```bash
asm.h            cpuset.h  latin1.h    mp.h        semaphore.h  thread.h  utf16.h
asm-math.h       ctype.h   log.h       nocrt       spinlock.h   time.h    uuid.h

/usr/lib/../src/vboxhost-5.1.0_OSE/vboxpci/include/iprt/nocrt:
limits.h

/usr/lib/../src/vboxhost-5.1.0_OSE/vboxpci/include/VBox:
cdefs.h  err.h  log.h  param.h  rawpci.h  SUPDrvMangling.h  sup.h  types.h  version.h  vmm

/usr/lib/../src/vboxhost-5.1.0_OSE/vboxpci/include/VBox/vmm:
stam.h

/usr/lib/../src/vboxhost-5.1.0_OSE/vboxpci/linux:
SUPR0IdcClient-linux.c  VBoxPci-linux.c

/usr/lib/../src/vboxhost-5.1.0_OSE/vboxpci/math:
gcc

/usr/lib/../src/vboxhost-5.1.0_OSE/vboxpci/math/gcc:
divdi3.c  moddi3.c  qdivrem.c  quad.h  udivdi3.c  umoddi3.c

/usr/lib/../src/vboxhost-5.1.0_OSE/vboxpci/r0drv:
linux

/usr/lib/../src/vboxhost-5.1.0_OSE/vboxpci/r0drv/linux:
the-linux-kernel.h
make[2]: *** [Makefile:16: build-proto] Error 1
make[2]: Leaving directory '/home/fusion809/AUR/fsharp/src/fsharp-4.0.1.5/src/fsharp'
make[1]: *** [Makefile:10: all] Error 2
make[1]: Leaving directory '/home/fusion809/AUR/fsharp/src/fsharp-4.0.1.5/src/fsharp'
make: *** [Makefile:5: all] Error 2
```

Version 4.0.1.1 builds fine though, using the same procedure. Mono version is 4.4.1. Any ideas as to why I'm getting this build error?

Thanks for your time,
Brenton

**Comment by tathanhdinh** [comment]
I have got also this error yesterday, it can be fixed by commenting the line 

> ls -R $(monolibdir)/..

following the `build-proto` target in `fsharp-4.0.1.5/fsharp/src/Makefile`

**Comment by soimort** [comment]
> ls -R $(monolibdir)/..

Removed that line and another error is thrown:

```
Unhandled Exception:
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "FSComp.resources" was correctly embedded or linked into assembly "FSharp.Compiler-proto" at compile time, or that all the satellite assemblies required are loadable and fully signed.
  at Microsoft.FSharp.Compiler.ErrorLogger+ErrorLoggerExtensions.ReraiseIfWatsonable (System.Exception exn) <0x40bde570 + 0x00173> in <filename unknown>:0 
  at Microsoft.FSharp.Compiler.ErrorLogger+ErrorLoggerExtensions.ErrorLogger.ErrorRecovery (Microsoft.FSharp.Compiler.ErrorLogger x, System.Exception exn, range m) <0x40ba2b20 + 0x0026f> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "FSComp.resources" was correctly embedded or linked into assembly "FSharp.Compiler-proto" at compile time, or that all the satellite assemblies required are loadable and fully signed.
  at Microsoft.FSharp.Compiler.ErrorLogger+ErrorLoggerExtensions.ReraiseIfWatsonable (System.Exception exn) <0x40bde570 + 0x00173> in <filename unknown>:0 
  at Microsoft.FSharp.Compiler.ErrorLogger+ErrorLoggerExtensions.ErrorLogger.ErrorRecovery (Microsoft.FSharp.Compiler.ErrorLogger x, System.Exception exn, range m) <0x40ba2b20 + 0x0026f> in <filename unknown>:0 
```

**Comment by soimort** [comment]
It seems the package version of `FSharp.Compiler.Tools` needs to be updated (from 4.0.0.1) to:

```xml
<package id="FSharp.Compiler.Tools" version="4.0.1.3" />
```

to reflect the fix in d995c590c2daed74ccb43d519f74623027506da7, otherwise it won't build on systems where `4.0/Mono.Posix.dll` doesn't exist.

**Comment by tathanhdinh** [comment]
There may be not this problem about `Mono.Posix.dll` on my system (I have used Fedora with repos of Mono Project), so after commenting out this line; fsharp compile nicely.

**Comment by fusion809** [comment]
My error is fixed, see https://github.com/fusion809/fsharp for my PKGBUILD that successfully builds FSharp 4.0.1.5.

**Comment by dsyme** [comment]
There are a number of glitches mentioned above

* I deleted the ``ls -R`` line since it's just diagnostics and it was mentioned as a problem above
* I submitted [this PR to update the compiler tools to 4.0.1.3](https://github.com/fsharp/fsharp/pull/592) since that was mentioned as a problem - can anyone confirm the issue and whether this fixes things?  Does anyone know why Mono.Posix.dll 4.0.0.0 might not be installed?

I'd also be grateful if people using various Linux distros can confirm that [this issue](https://github.com/fsharp/fsharp/issues/555) is fixed

**Comment by dsyme** [comment]
@fusion809 @tathanhdinh @soimort Please indicate if other fixes are needed to get the latest tags building cleanly

**Comment by fusion809** [comment]
Just built v4.0.1.8 with the aforementioned PKGBUILD without issue, so from my point of issue this issue is still resolved.

**Comment by tathanhdinh** [comment]
@dsyme if I am not wrong, the `tar.gz` and `zip` of `v4.0.1.8` are the same as `v4.0.1.7-alpha`, they are both `84d78c4` !? (I have checked them, the content of unarchive folders are the same). Otherwise, I have changed all strings `4.0.0.1` to `4.0.1.3` in several files, and it is built nicely.

**Comment by dsyme** [comment]
@tathanhdinh Yes, the alpha tag was used for the FSharp.Core nuget pakage (which has stayed identical since 4.0.1.3, just the 4.0.1.7-alpha also includes an alpha of the FSharp.Core for .NET Core)
