### ISSUE TITLE
F# 4.0 stuck at .Net 4.5.0 compat-level

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#595]
There's currently no way to reference nugets or DLLs which have a higher level than .Net 4.5, because when changing TargetFrameworkVersion inside `fsproj` files, the compiler complains:

```
Project "/Users/h/dev/haf/logary/src/Logary/Logary.fsproj" (default target(s)):
	Target PrepareForBuild:
		Configuration: Debug Platform: AnyCPU
	Target GetFrameworkPaths:
/Library/Frameworks/Mono.framework/Versions/4.4.1/lib/mono/4.5/Microsoft.Common.targets:  warning : TargetFrameworkVersion 'v4.5.2' not supported by this toolset (ToolsVersion: 4.0).
```

#### Repro steps

 1. Create a new F# library
 2. Change the target version to 4.5.2
 3. Watch it crash as you try to use it/warning as you compile it.
 4. Alternatively add Topshelf 4.x, which has a lowest-.Net of 4.5.2 and try to compile: doesn't work.

#### Expected behavior

F# should be usable for later .net framework versions.

#### Actual behavior

F#'s compiler complains when compiling the fsproj file.

#### Known workarounds

No known workarounds.

#### Related information 

* Operating system: OS X
* Branch: -
* .NET Runtime, CoreCLR or Mono Version: Mono v4.4.1
* Editing Tools (e.g. Visual Studio Version): xbuild/vscode
* Links to F# RFCs or entries on http://fslang.uservoice.com
* Links to performance testing scripts
* Indications of severity: medium

**Comment by dsyme** [comment]
@haf That looks like an MSBuild issue - the ToolsVersion 4.0 refers to an MSBuild version number.  Have you tried changing ToolsVersion to 12.0 at the top of your project file?

Also, could you clarify the repro when you say "1. create an F# library", so we can know exactly how that library is created and the resulting project file?

**Comment by haf** [comment]
I think the warning about tools version is related to xbuild not implementing the same feature-set, hence the MSBuild port. ToolsVersion=4 has been used in Xamarin Studio for years now, so it's probably safe to ignore that warning; it's the default version for sln files created in it.

If I change to v12 then xbuild doesn't compile the library.

Using the xplatform msbuild is blocked on #583 so that's not usable at the moment.

Step 1, is through Xamarin Studio. New > Project > F# Library, but you can create any project type AFAIK, or just open any existing F# project; it's the changing of the targeted framework that's the issue.

**Comment by dsyme** [comment]
@haf Thanks.  

    F#'s compiler complains when compiling the fsproj file.

OK, but is it correct to say that this is xbuild complaining?   AFAIK the F# compiler doesn't emit a complaint when referencing 4.5.2 DLLs?

I'm not yet sure there's a specific adjustment we can make in the F# compiler or FSharp.Build support here.

**Comment by haf** [comment]
I don't know; what command do you then run, when you reference a 4.5.2 assembly on mono?

**Comment by dsyme** [comment]
@haf What I mean is this: is it the execution of "fsharpc" giving the error?  Or the execution of ``xbuild`` (before the invocation of ``fsharpc``).  If the former, then we have a problem with the F# compiler (this repo).  If the latter, then  it is either a problem with ``xbuild`` itself, or with the projecct file (e,.g. incorrect ToolsVersion), or with the Microsoft.FSharp.targets+FSharp.Build (this repo)

Clearly there's a problem, we just need to work out where the fix needs to be

**Comment by dsyme** [comment]
This seems to be an MSBuild issue - either ToolsVersion or the choice of .NET Framework
