### ISSUE TITLE
Microsoft.Portable.FSharp.Targets with different casing in repo

### ISSUE THREAD

**Issue by akoeplinger** [fsharp/fsharp#597]
The file is present twice in fsharp/src/fsharp/FSharp.Build, with different casings. This causes issues/confusion on case-insensitive file systems. One of the files should be removed.

![image](https://cloud.githubusercontent.com/assets/1376924/17311557/8e46bf5c-584c-11e6-8973-2097bc131106.png)

**Comment by dsyme** [comment]
This _should_ be fixed by #599. However it fails

**Comment by dsyme** [comment]
OK, the deletion above works, but may require an explicit

    git checkout -f src/fsharp/FSharp.Build/Microsoft.Portable.FSharp.targets
