### ISSUE TITLE
Difference between FSharp.Compiler.Tools 4.0.0.1 and 4.0.1.3

### ISSUE THREAD

**Issue by tpetricek** [fsharp/fsharp#600]
Is the [4.0.1.3](https://www.nuget.org/packages/FSharp.Compiler.Tools/4.0.1.3) version of FSharp.Compiler.Tools supposed to be have the same behaviour as version 4.0.0.1 on .NET (non-Core) on Windows?

On 4.0.0.1, running `fsc test.fs` with minimal hello world sample work, but with 4.0.1.3, I get:

> error FS0082: Could not resolve this reference. Could not locate the assembly "System.Runtime.dll".

Or is the 4.0.1.3 version supposed to be .NET Core only?

**Comment by dsyme** [comment]
@tpetricek The Nuget package should work as before on .NET Framework (it is not ".NET Core only" - and there are no plans for that to be the case), so this is a bug.

I think it has been fixed and we need to just push a new nuget.

Could you try a later version from CI please - e.g. 4.0.1.7 (https://ci.appveyor.com/project/fsgit/fsharp/build/4.0.1.7-b543/artifacts) or freshly tagged 4.0.1.9? https://ci.appveyor.com/project/fsgit/fsharp/build/553

**Comment by tpetricek** [comment]
Perfect, the new version from CI works :+1:

**Comment by dsyme** [comment]
4.0.1.10 pushed to nuget.org
