### ISSUE TITLE
PCL isn't a thing according to fsharp.org

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#601]
According to [fsharp.org](http://fsharp.org/guides/mac-linux-cross-platform/#portable-libraries) 

<blockquote>
At the time of writing, creating portable libraries was not yet fully supported in IDES on Mac and Linux, though you can normally build portable libraries successfully using xbuild and command-line tools on these platforms. If you are developing on Windows, or using libraries on Windows, then consider creating portable libraries to ease cross-platfom use.
</blockquote>

– I was looking for guidance on how to convert a library to PCL but found none. Only discussion about Visual Studio.

Ref https://github.com/logibit/Logibit.Hawk/issues/9

**Comment by 7sharp9** [comment]
Portable libs are supported in Xamarin Studio

**Comment by dsyme** [comment]
@haf We should really have a specific document on this at http://fsharp.github.io/

The project file fragments in http://fsharp.github.io/2015/04/18/fsharp-core-notes.html#examples-of-how-project-files-reference-fsharpcore-and-the-f-targets-file are a good start.

**Comment by haf** [comment]
There should also be a checklist of where to find the alternative APIs and what the different numbers `78`, `258` etc mean for library authors.
