### ISSUE TITLE
A method with the same name as DU counstructor

### ISSUE THREAD

**Issue by xperiandri** [fsharp/fsharp#604]
Why can't I create a static method with the same name as discriminated union constructor or static method generated from it?

Neither this
``` F#
type ElementDimensions =
    | Inherited of Length : Dimension
    | TypeSizeDimensions of TypeSize : TypeSize * Length : Dimension
    | CustomDimensions of Profile : Profile * Lenght : Dimension
    static member NewCustomDimensions (width, height, length) =
        CustomDimensions(Profile(width, height), length)
```
Nor this does work
``` F#
    static member CustomDimensions (width, height, length) =
        CustomDimensions(Profile(width, height), length)
```

And I wonder why because the number of parameters is different!

#### Expected behavior

If the list of parameters of DU constructor and the static method with the same name is different, it compiles well.

#### Actual behavior

error FS0023: The member 'NewCustomDimensions' can not be defined because the name 'NewCustomDimensions' clashes with the compiled form of the union case 'CustomDimensions' in this type or module

### Known Workarounds

``` F#
[<AutoOpen>]
[<CompilationRepresentation (CompilationRepresentationFlags.ModuleSuffix)>]
module Element =

    open System
    open System.Collections.Immutable
    open FSharp.Collections.Immutable
    open Microsoft.FSharp.Data.UnitSystems.SI.UnitSymbols

    let CustomDimensions (width, height, length) =
        CustomDimensions(Profile(width, height), length)
```

But it does not work for other .NET languages. I cannot expose an overload for DU case constructor method.

#### Related information 

* Windows 10 Pro 14393
* .NET Portable Profile259
* Visual Studio 2015 Enterprise Update 3

**Comment by forki** [comment]
you should post this to visualfsharp repo.

**Comment by xperiandri** [comment]
OK, I just wonder why.

**Comment by forki** [comment]
because that's the compiler issue repo. this one here is only for packaging the compiler for mono.

**Comment by forki** [comment]
mady that sample self-contained:

    type Dimension = int
    type TypeSize = int
    type Length = int
    type Profile = | Profile of int*int
    
    type ElementDimensions =
        | Inherited of Length : Dimension
        | TypeSizeDimensions of TypeSize : TypeSize * Length : Dimension
        | CustomDimensions of Profile : Profile * Lenght : Dimension
        static member NewCustomDimensions (width, height, length) =
            CustomDimensions(Profile(width, height), length);;

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/17929405/aa24d9e6-6a00-11e6-8f95-9b8f44891b1e.png)

CreateCustomDimensions would work.

**Comment by xperiandri** [comment]
Got it.
Thanks, however it won't look consistent to C# consumer

**Comment by 7sharp9** [comment]
You probably wouldn't want to expose a DU to a C# consumer anyway.

**Comment by xperiandri** [comment]
@7sharp9, why not, it is convenient.
@forki, reposted as https://github.com/Microsoft/visualfsharp/issues/1488

**Comment by enricosada** [comment]
@dsyme this can be closed
