### ISSUE TITLE
Can not debug `dotnet` project

### ISSUE THREAD

**Issue by koromorix** [fsharp/fsharp#606]
#### Repro steps

	mkdir f#
	cd f#
	dotnet new --lang F#
	code .

VSCode brings up messages telling me to add assets and restore, so I do.

I change "Program.fs" to read:

	open System

	[<EntryPoint>]
	let main argv = 
	    raise (Exception("ERR"))
	    0

Then I open the debugger and hit play.

#### Expected behavior

Debugger brings me to line 5 of Program.fs.

#### Actual behavior

I get taken to a new file that says:

	Source /Unknown Source is not available.

#### Other notes

When I follow the same steps for a C# project (plain old `dotnet new`), it works just fine.

Also, `dotnet run` works and shows me an exception:

	Project f# (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
	Compiling f# for .NETCoreApp,Version=v1.0

	Compilation succeeded.
	    0 Warning(s)
	    0 Error(s)

	Time elapsed 00:00:04.9752511
	 

	Unhandled Exception: System.Exception: ERR
	   at Program.main(String[] argv)

#### Known workarounds

None

#### Related information 

* Operating system: Linux Mint 17
* `dotnet --version` is `1.0.0-preview2-003121`
* VSCode 1.4.0

**Comment by enricosada** [comment]
@koromorix good bug report!

Debugging is not yet supported in dotnet core because work portable pdb is not completed.
The .pdb files are generated but doesnt work atm

**Comment by dsyme** [comment]
@koromorix Dotnet core issues should go to http://github.com/Microsoft/visualfsharp please.  This repo is the Linux/OSX packaging repo
