### ISSUE TITLE
Latest 4.0.1.7-alpha is packaged incorrectly for a netcoreapp.

### ISSUE THREAD

**Issue by matthid** [fsharp/fsharp#608]
When using the latest alpha package instead of "Microsoft.FSharp.Core.netcore" in a netcoreapp application the dotnet cli will not copy "FSharp.Core.sigdata" and "optdata" to the output directory because it is packaged incorrectly
#### Repro steps

Create a new package using `FSharp.Compiler.Service`, when you try to compile code at runtime you get:

```
error FS1225: File 'C:\projects\fake\nuget\dotnetcore\Fake.netcore\current\FSharp.Core.optdata' not found alongside FSharp.Core
```
#### Expected behavior

It should work like it does with "Microsoft.FSharp.Core.netcore".
#### Actual behavior

It fails.
#### Known workarounds

Add a dependency to `Microsoft.FSharp.Core.netcore` as well.
#### Related information

We should probably merge the nuget packages like we do for other F# projects as well. @enricosada 

![comparenugetpackages](https://cloud.githubusercontent.com/assets/1866463/18615329/275783da-7da4-11e6-9f92-14d95fab95c8.png)

If you let me know how the current package was build I might be able to help or update the release process.

**Comment by matthid** [comment]
OK, found https://github.com/fsharp/fsharp/issues/566 and therefore https://github.com/fsharp/fsharp/pull/590
Seems like `NupkgMerge` doesn't do what we want? 
Or was the 4.0.1.7-alpha version already generated with the merge tool from @enricosada?
Who published it and/or still knows?
/cc @dsyme @forki

**Comment by dsyme** [comment]
The package pushed to nuget is the one from AppVeyor, prepared by [these lines in appveyor.ps1](https://github.com/fsharp/fsharp/blob/master/appveyor.ps1#L34)

**Comment by dsyme** [comment]
@enricosada @ncave @matthid Help with this would be greatly appreciated :)

**Comment by enricosada** [comment]
@matthid can you close? is fixed by https://www.nuget.org/packages/FSharp.Core/4.1.0

**Comment by matthid** [comment]
@enricosada I trust you but will check eventually ;)

**Comment by enricosada** [comment]
@matthid i dont trust myself, only my test suite with all os :D https://github.com/dotnet/netcorecli-fsc#build
