### ISSUE TITLE
Diamond dependencies of fsx file doesn't work

### ISSUE THREAD

**Issue by eggapauli** [fsharp/fsharp#611]
I have a set of fsx files where the dependency graph is a diamond (i.e. "a.fsx" loads "b.fsx" and "c.fsx", "b.fsx" and "c.fsx" both load "d.fsx").  
When loading "a.fsx" in fsi it tells me that "The namespace or module 'D' is not defined".

#### Repro steps

1. Create four fsx files:
  * a.fsx:

            #load "b.fsx"
            #load "c.fsx"
            B.writeB()
            C.writeC()
  * b.fsx:

            #load "d.fsx"
            let writeB() = D.writeD "B"
  * c.fsx:

            #load "d.fsx"
            let writeC() = D.writeD "C"
  * d.fsx:

            let writeD ch = printfn "Yay %s" ch
* Invoke `fsi --load:a.fsx`

#### Expected behavior
Should print

    Yay B
    Yay C

#### Actual behavior
    Microsoft (R) F# Interactive version 14.0.23413.0
    Copyright (c) Microsoft Corporation. All Rights Reserved.

    For help type #help;;

    [Loading b.fsx
     Loading d.fsx
     Loading c.fsx
     Loading a.fsx]

    b.fsx(2,16): error FS0039: The namespace or module 'D' is not defined

#### Known workarounds

Remove load statement in "c.fsx" and it'll work. However IntelliSense will report errors in "c.fsx".

#### Related information 

* Operating system: Windows 10

**Comment by dsyme** [comment]
This is fixed in master of both fsharp/fsharp and Microsoft/visualfsharp
