### ISSUE TITLE
Fsharp >=4.0 fails to build on Gentoo Linux

### ISSUE THREAD

**Issue by afarah1** [fsharp/fsharp#616]
#### Reproduction
1. Clone and install mono as described in "Option 3" from http://fsharp.org/use/linux/
2. Clone and install fsharp according to "Option 3" as well, to the same prefix as mono

Alternatively, use "Option 5" and see [this bug report](https://bugs.gentoo.org/show_bug.cgi?id=564480) for details.
#### Expected behavior

fsharp should build without errors
#### Actual behavior

fsharp fails to build with the following build log after `make` is invoked

```
make -C src/fsharp all
make[1]: Entering directory '/home/afh/install/fsharp/src/fsharp'
make build-proto
make[2]: Entering directory '/home/afh/install/fsharp/src/fsharp'
cp -p /home/afh/install/fsharp/lib/bootstrap/4.0/FSharp.Core.dll /home/afh/install/fsharp//lib/proto/FSharp.Core.dll
cp -p /home/afh/install/fsharp/lib/bootstrap/4.0/FSharp.Core.sigdata /home/afh/install/fsharp//lib/proto/FSharp.Core.sigdata
cp -p /home/afh/install/fsharp/lib/bootstrap/4.0/FSharp.Core.optdata /home/afh/install/fsharp//lib/proto/FSharp.Core.optdata
make -C FSharp.Build-proto Configuration=proto build-proto
make[3]: Entering directory '/home/afh/install/fsharp/src/fsharp/FSharp.Build-proto'
MONO_ENV_OPTIONS= /home/afh/install/mono-4.6.0/b/bin/xbuild /p:Configuration=Proto
XBuild Engine Version 14.0
Mono, Version 4.6.0.0
Copyright (C) 2005-2013 Various Mono authors

Build started 9/27/2016 5:06:45 PM.
__________________________________________________
Project "/home/afh/install/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj" (default target(s)):
        Target CallFsSrGen:
                Created directory "obj/proto/./"
                Tool /home/afh/install/fsharp/src/fsharp/FSharp.Build-proto/../../../lib/bootstrap/4.0/fssrgen.exe execution started with arguments:  /home/afh/install/fsharp/src/fsharp/FSharp.Build/FSBuild.txt  obj/proto/./FSBuild.fs  FSBuild.resx 
        Target BeforeBuild:
                Executing: mono --runtime=v4.0.30319 /home/afh/install/fsharp/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.exe restore packages.config -PackagesDirectory packages
                WARNING: Error: TrustFailure (The authentication or decryption has failed.)
                WARNING: Error: TrustFailure (The authentication or decryption has failed.)
                Unable to find version '2.6.4' of package 'NUnit'.
                Unable to find version '2.6.4' of package 'NUnit.Runners'.
/home/afh/install/fsharp/src/FSharpSource.targets: error : Command 'mono --runtime=v4.0.30319 /home/afh/install/fsharp/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.exe restore packages.config -PackagesDirectory packages' exited with code: 1.
        Task "Exec" execution -- FAILED
        Done building target "BeforeBuild" in project "/home/afh/install/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj".-- FAILED
Done building project "/home/afh/install/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj".-- FAILED

Build FAILED.
Errors:

/home/afh/install/fsharp/src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj (default targets) ->
/home/afh/install/fsharp/src/FSharpSource.targets (BeforeBuild target) ->

        /home/afh/install/fsharp/src/FSharpSource.targets: error : Command 'mono --runtime=v4.0.30319 /home/afh/install/fsharp/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.exe restore packages.config -PackagesDirectory packages' exited with code: 1.

         0 Warning(s)
         1 Error(s)

Time Elapsed 00:00:03.7702470
Makefile:9: recipe for target 'build-proto' failed
make[3]: *** [build-proto] Error 1
make[3]: Leaving directory '/home/afh/install/fsharp/src/fsharp/FSharp.Build-proto'
Makefile:15: recipe for target 'build-proto' failed
make[2]: *** [build-proto] Error 2
make[2]: Leaving directory '/home/afh/install/fsharp/src/fsharp'
Makefile:10: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/afh/install/fsharp/src/fsharp'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```
#### Known workarounds

Some suggestions can be found [here](https://bugs.gentoo.org/show_bug.cgi?id=564480), though they did not solve the issue for me.
#### Related information

This report is for the fsharp4 branch, though master also fails to build.

System information:

```
Portage 2.2.28 (python 3.4.3-final-0, default/linux/amd64/13.0/no-multilib, gcc-4.9.3, glibc-2.22-r4, 4.4.6-gentoo x86_64)
=================================================================
System uname: Linux-4.4.6-gentoo-x86_64-Intel-R-_Core-TM-2_Quad_CPU_Q6600_@_2.40GHz-with-gentoo-2.2
KiB Mem:     4036096 total,    117504 free
KiB Swap:    1048572 total,   1042084 free
Timestamp of repository gentoo: Tue, 27 Sep 2016 18:00:01 +0000
sh bash 4.3_p42-r1
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
app-shells/bash:          4.3_p42-r1::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.22.2::gentoo
dev-lang/python:          2.7.10-r1::gentoo, 3.4.3-r1::gentoo
dev-util/cmake:           3.5.2-r1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.21.7::gentoo
sys-apps/sandbox:         2.10-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.14.1::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::gentoo
sys-devel/gcc-config:     1.7.3::gentoo
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.3::gentoo (virtual/os-headers)
sys-libs/glibc:           2.22-r4::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe -march=core2"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -pipe -march=core2"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j4"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
USE="acl alsa amd64 berkdb bindist bzip2 cli cracklib crypt cxx dri gdbm iconv ipv6 mmx mmxext modules ncurses nls nptl openmp pam pcre readline seccomp smp sse sse2 ssl tcpd unicode vim-syntax xattr zlib zsh-completion" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="keyboard mouse evdev" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfo ntz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" RUBY_TARGETS="ruby20 ruby21" USERLAND="GNU" VIDEO_CARDS="intel i965" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, USE_PYTHON
```

Edit: It's worth mentioning fsharp31 builds successfully.

**Comment by dsyme** [comment]
@afarah1 This is a failure in nuget restore - perhaps it is a certificates issue?  In any case it seems to be some problem with the Mono or nuget installation.  Perhaps related to #617

**Comment by adamss3** [comment]
I have the same issue when trying to build on Crunchbang++ 1.0.  As mentioned above, 3.1 builds just  fine in that environment.

**Comment by smoothdeveloper** [comment]
@afarah1 / @adamss3 could you look into:

> Command 'mono --runtime=v4.0.30319 /home/afh/install/fsharp/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.exe restore packages.config -PackagesDirectory packages' exited with code: 1.
 
Can you try to run the same command from directly and report the output here?

We are sorry it seems the error reporting from the build script isn't so great.

Thanks!

**Comment by adamss3** [comment]
user@x100eA:~/fsharp-fsharp4$ mono --runtime=v4.0.30319 
/home/adamss/fsharp-fsharp4/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.exe 
restore packages.config -PackagesDirectory packages
Unable to find version '2.6.4' of package 'NUnit'.
Unable to find version '2.6.4' of package 'NUnit.Runners'.

**Comment by smoothdeveloper** [comment]
@adamss3 thanks, could you try this:

in an empty directory create `paket.dependencies` text file:

```
source https://nuget.org/api/v2
nuget NUnit = 2.6.4
nuget NUnit.Runners = 2.6.4
```

Download `paket.exe` from https://github.com/fsprojects/Paket/releases/tag/3.36.0 and put it in same directory.

call `mono paket.exe install` from that same directory

and check if this succeeds?

**Comment by adamss3** [comment]
Thanks!  That fixed my problem.

**Comment by smoothdeveloper** [comment]
@dsyme / @forki should we prepare a PR to replace `NuGet.exe` with `paket.exe` to pull packages in fsharp/fsharp repository?

**Comment by knocte** [comment]
Paket uses nuget under the hood, why would nuget fail and paket succeed?

**Comment by smoothdeveloper** [comment]
@knocte paket.exe uses nuget.org to download the files, but it doesn't use NuGet.exe to issue the download over http.

I believe paket.exe has been more battle tested to work on mono than NuGet.exe, especially wrt proxy or certificates issues.

**Comment by forki** [comment]
I have no power to decide this

Am 28.02.2017 08:08 schrieb "Gauthier Segay" <notifications@github.com>:

**Comment by knocte** [comment]
> @knocte paket.exe uses nuget.org to download the files, but it doesn't use NuGet.exe to issue the download over http.
> I believe paket.exe has been more battle tested to work on mono than NuGet.exe, especially wrt proxy or certificates issues.

Sorry but seems such a massive hack to tell .net users to use nuget in windows and paket in linux. What is preventing nuget from implementing the paket way of doing things? Has anyone reported the mono bugs that prevent nuget to work properly with it that spawned the need for paket?

**Comment by forki** [comment]
I'm sure the idea wasn't to use nuget for Windows and paket for other OSes.

Regarding nuget on mono. There is an endless stream of reported bugs and
also fixes. Unfortunately backwards compatibility broke at some point.
Anyways, which version are we using here? Has anyone tried to upgrade that?

Am 28.02.2017 09:30 schrieb "Andres G. Aragoneses" <notifications@github.com
>:

@knocte <https://github.com/knocte> paket.exe uses nuget.org to download
the files, but it doesn't use NuGet.exe to issue the download over http.
I believe paket.exe has been more battle tested to work on mono than
NuGet.exe, especially wrt proxy or certificates issues.

Sorry but seems such a massive hack to tell .net users to use nuget in
windows and paket in linux. What is preventing nuget from implementing the
paket way of doing things? Has anyone reported the mono bugs that prevent
nuget to work properly with it that spawned the need for paket?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fsharp/fsharp/issues/616#issuecomment-282974968>, or mute
the thread

**Comment by dsyme** [comment]
@smoothdeveloper In theory we could switch to using paket here

However we've been trying really hard to reduce the divergence between http://github.com/Microsoft/visualfsharp and http://github.com/fsharp/fsharp, and we're almost at complete convergence right now.  I think my preference would be to try firs to update ``NuGet.exe`` to the latest version (or the same version as http://github.com/Microsoft/visualfsharp, or upgrade both to the latest version) as @forki suggests.

If someone could try that on a clean repo on the various Linux distributions that would be great, and then submit a PR

thanks
don

**Comment by smoothdeveloper** [comment]
@dsyme apparently this bug is open in gentoo for long now (check the bug report link from 1st comment), they have been discussing how to get nuget to work properly in the `ebuild`.

> Reported:	2015-10-30 08:57 UTC by Toralf Förster

Also, we updated NuGet recently in this repository (@adamss3 / @afarah1 would you confirm you repro the error on a recent checkout of this repository?).

This seem to be a good reason to rely on paket, at least for building on linux. I know harmonization and trying to get visualfsharp / fsharp builds aligned requires efforts, but letting issues like that go for ever hurts the language.

As of today, it seems we have more control on issues user would face with `paket.exe` than `NuGet.exe` and faster turnaround to get them troubleshooted.

@knocte I disagree that using paket here would be a "massive hack", setting up a `paket.dependencies` (we don't even need to touch the *proj files) is easy given the `packages.config`, we are talking about getting a handfull of packages with fixed version downloaded, the changes, I assume, would be:

* replace one xml file by a simpler text one
* add .paket folder with paket.exe
* change one line calling nuget in the build script

the diff incurred with visualfsharp would be quite minimal (again no change in .*proj files)

**Comment by dsyme** [comment]
Closing as external

**Comment by kflu** [comment]
FYI, I saw the same error on FreeBSD mono 4.8.1. [This issue](https://github.com/NuGet/NuGetGallery/issues/335) fixed my problem. Basically, use `mozroot --import` to import all the root certs. You have to type "yes" MANY MANY times. 

Oh I'm in a FreeBSD jail not sure if that's why I don't have those certs by default. 

`nuget` has the same problem not just `paket`.

Other packaging system works like `raco` for Racket.
