### ISSUE TITLE
build: hangs indefinitely on 'nuget restore'

### ISSUE THREAD

**Issue by hasufell** [fsharp/fsharp#617]
```
hasufell@localhost ~/git/fsharp $ ./autogen.sh --prefix=/usr/x86_64-pc-linux-gnu
checking whether make sets $(MAKE)... yes
checking for pkg-config... /usr/host/bin/pkg-config
configure: "pkg-config: /usr/x86_64-pc-linux-gnu/bin/pkg-config"
configure: "PKG_CONFIG_LIBDIR: "
configure: Using bootstrap : /home/hasufell/git/fsharp/packages/FSharp.Compiler.Tools.4.0.1.3/tools
checking for xbuild... /usr/host/bin/xbuild
configure: xbuild: /usr/x86_64-pc-linux-gnu/bin/xbuild
configure: PCL Reference Assemblies for Profile 47 found: no
configure: PCL Reference Assemblies for Profile 47 found: no
configure: PCL Reference Assemblies for Profile 7 found: no
configure: PCL Reference Assemblies for Profile 78 found: no
configure: PCL Reference Assemblies for Profile 259 found: no
configure: creating ./config.status
config.status: creating launcher
config.status: creating Makefile
config.status: creating config.make
config.status: creating src/fsharp/Makefile
config.status: creating src/fsharp/FSharp.Build-proto/Makefile
config.status: creating src/fsharp/FSharp.Compiler-proto/Makefile
config.status: creating src/fsharp/Fsc-proto/Makefile
config.status: creating src/fsharp/FSharp.Core/Makefile
config.status: creating src/fsharp/FSharp.Build/Makefile
config.status: creating src/fsharp/FSharp.Compiler/Makefile
config.status: creating src/fsharp/Fsc/Makefile
config.status: creating src/fsharp/FSharp.Compiler.Interactive.Settings/Makefile
config.status: creating src/fsharp/FSharp.Compiler.Server.Shared/Makefile
config.status: creating src/fsharp/fsi/Makefile
config.status: creating src/fsharp/fsiAnyCpu/Makefile
config.status: creating src/fsharp/policy.2.0.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.2.3.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.3.3.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.3.7.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.3.47.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.3.78.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.3.259.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.4.0.FSharp.Core/Makefile
config.status: creating src/fsharp/policy.4.3.FSharp.Core/Makefile
hasufell@localhost ~/git/fsharp $ make -j1
MONO_ENV_OPTIONS= mono .nuget/NuGet.exe restore packages.config -PackagesDirectory packages -ConfigFile .nuget/NuGet.Config
Restoring NuGet package FSharp.Data.2.2.5.
Restoring NuGet package NUnit.Runners.3.0.0.
Restoring NuGet package FSharp.Compiler.Tools.4.0.1.3.
Restoring NuGet package FsCheck.2.0.3.
Restoring NuGet package NUnit.Console.3.0.0.
Restoring NuGet package NUnit.3.0.0.
Restoring NuGet package NUnitLite.3.0.0.
Restoring NuGet package NUnit3TestAdapter.3.0.8-ctp-8.
Restoring NuGet package System.Collections.Immutable.1.2.0.
Restoring NuGet package System.Reflection.Metadata.1.4.1-beta-24227-04.
Restoring NuGet package Microsoft.DiaSymReader.PortablePdb.1.1.0.
Restoring NuGet package Microsoft.DiaSymReader.1.0.8.
Restoring NuGet package FsSrGen.3.0.0.
Restoring NuGet package FSharp.SRGen.Build.Tasks.3.0.0.
Restoring NuGet package Microsoft.VisualFSharp.Core.Redist.1.0.0.
Restoring NuGet package System.ValueTuple.4.0.0-rc3-24212-01.
```

System:
Exherbo Linux, fsharp master branch, mono-4.2.2.30

**Comment by phreme** [comment]
The same happens on freshly installed Fedora, mono 4.2.4.

**Comment by dsyme** [comment]
I don't see anything indicating what the problem might be - my guess is a nuget.org or myget.org problem.  I've removed myget.org here: https://github.com/fsharp/fsharp/pull/619/, if that passes CI then please try it out to see if it fixes the problem?

**Comment by hasufell** [comment]
Pretty much the same, except that I also get some warnings now:
```
$ make -j1
MONO_ENV_OPTIONS= mono .nuget/NuGet.exe restore packages.config -PackagesDirectory packages -ConfigFile .nuget/NuGet.Config
Restoring NuGet package FSharp.Compiler.Tools.4.0.1.3.
Restoring NuGet package FsCheck.2.0.3.
Restoring NuGet package NUnit.Runners.3.0.0.
Restoring NuGet package FSharp.Data.2.2.5.
Restoring NuGet package NUnit.Console.3.0.0.
Restoring NuGet package NUnitLite.3.0.0.
Restoring NuGet package NUnit.3.0.0.
Restoring NuGet package System.Collections.Immutable.1.2.0.
Restoring NuGet package System.Reflection.Metadata.1.4.1-beta-24227-04.
Restoring NuGet package NUnit3TestAdapter.3.0.8-ctp-8.
Restoring NuGet package Microsoft.DiaSymReader.PortablePdb.1.1.0.
Restoring NuGet package Microsoft.DiaSymReader.1.0.8.
Restoring NuGet package FsSrGen.3.0.0.
Restoring NuGet package FSharp.SRGen.Build.Tasks.3.0.0.
Restoring NuGet package System.ValueTuple.4.0.0-rc3-24212-01.
Restoring NuGet package Microsoft.FSharp.Core.netcore.1.0.0-alpha-160831.
WARNING: Unable to find version '3.0.0' of package 'NUnit.Runners'.
  /home/hasufell/.local/share/NuGet/Cache: Package 'NUnit.Runners.3.0.0' is not found on source '/home/hasufell/.local/share/NuGet/Cache'.
  https://www.nuget.org/api/v2/: Unable to load the service index for source https://www.nuget.org/api/v2/.
  The HTTP request to 'GET https://www.nuget.org/api/v2/' has timed out after 100000ms.

```

**Comment by dsyme** [comment]
That warning should be fixed now

Strange - I don't know why nuget is timing out for you - it is ok for me

**Comment by hasufell** [comment]
This seems to be an SSL issue. NuGet works when I change `https://www.nuget.org/api/v2/` to `http://www.nuget.org/api/v2/` in `.nuget/NuGet.Config`. How does NuGet interface with ssl libraries? It seems this is incorrectly shipped.

**Comment by dsyme** [comment]
@hasufell If the build goes through when using v2, then we can still use that.

**Comment by hasufell** [comment]
> If the build goes through when using v2, then we can still use that.

Sorry, I'm not sure I understand. It only goes through when not using https.

Ultimately, you shouldn't rely on NuGet during build time anyway. Especially source distros usually have a policy (or even sandbox) to not allow fetching during build time. Everything must be fetchable BEFORE the build starts, otherwise offline-builds etc break.

The C# based game OpenRA has worked around this in two ways:
1. providing a curl-based [noget](https://github.com/OpenRA/OpenRA/blob/bleed/thirdparty/noget.sh) alternative
2. [picking up existing files if they already exist](https://github.com/OpenRA/OpenRA/blob/bleed/thirdparty/fetch-thirdparty-deps.sh#L29)

@Mailaender (OpenRA developer) also told me that NuGet is known to have problems with certificates and that it can be related to the way NuGet is built or even the system mono version. However, I doubt this is related to the system mono version since I even added `https://nuget.org` to the mono certificate store manually with `certmgr` without any change.

**Comment by dsyme** [comment]
> Sorry, I'm not sure I understand. It only goes through when not using https.

@hasufell My bad I thought it was v2 v v3 API

**Comment by dsyme** [comment]
> Ultimately, you shouldn't rely on NuGet during build time anyway. Especially source distros usually have a policy (or even sandbox) to not allow fetching during build time. Everything must be fetchable BEFORE the build starts, otherwise offline-builds etc break.

This is becoming trickier for the F# compiler in this repo, which has picked up some dependencies on Nuget packages.  @directhex has the same problem when preparing Debian source balls.

**Comment by knocte** [comment]
> This is becoming trickier for the F# compiler in this repo, which has picked up some dependencies on Nuget packages. @directhex has the same problem when preparing Debian source balls.

Good solution for this is to use git submodules instead of nuget dependencies. It makes more sense for opensource projects.

**Comment by hasufell** [comment]
The problem of nuget not doing proper ssl is because mono uses it's own certificate store. Depending on your mono installation, the store might not have been initialized yet. F* has [instructions](https://github.com/FStarLang/FStar/blob/master/INSTALL.md#on-linux-or-mac-os-x-using-mono) for that.

So the different methods of creating the mono certificate store are:
```
# local, downloaded from mozilla store
mozroots --import --sync
# global as root
mozroots --import --machine --sync
# global as root, read from system ca-certificate bundle
cert-sync /etc/ssl/certs/ca-certificates.crt
```

It can be debated whether this is a distro packaging problem or a problem with bundled NuGet or with documentation.

IMO, we should:
1. document that one _might_ have to create the mono certificate store as per above
2. allow to use the system NuGet binary
3. try to make NuGet optional

**Comment by dsyme** [comment]
I'm going to close this as external 

@hasufell If you could submit a PR adding the information to the README.md, that would be great.
