### ISSUE TITLE
Strange behaviour with member constraints having multiple arguments

### ISSUE THREAD

**Issue by AntonioL** [fsharp/fsharp#620]
Member constraints with multiple non tupled arguments seem to not be working in F#.

#### Repro steps

```fsharp
let inline foca (x : ^a) c' g' =
    let f' = (^a : (static member DrawL : Color -> Graphics -> unit) (c', g'))
    ()

type Drawer() =
    static member DrawL (color : Color)  (g: Graphics) =
        let r = g.VisibleClipBounds |> Rectangle.Truncate
        g.FillRectangle(Brushes.Orange, r)
        ()

(*Assume that p is an object with the CreateGraphics method but that
is not important in the scope of this ticket.
*)
foca (Drawer()) Color.Black (p.CreateGraphics())
```

I admit that it could be due to my ignorance regarding member constraints, if that is the case please close this report, I have checked the documentation and could not find any information about the matter.

#### Expected behavior

The above should compile as the Drawer class effectively has a member DrawL with the signature:  -> Color -> Graphics -> unit.

#### Actual behavior

Instead it does not compile as it objecting that it could not find a DrawL method in the object.
Which is weird.

#### Known workarounds

The reason I am filing this ticket is the strange workaround.

If I modify the DrawL method in the Drawer class such that the arguments are tupled (see the below code snippet), then it works but it should not.

```fsharp
type Drawer() =
    static member DrawL (color : Color, g: Graphics) =
        let r = g.VisibleClipBounds |> Rectangle.Truncate
        g.FillRectangle(Brushes.Orange, r)
        ()
```

The reason it should not is that the above has type signature: Color * Graphics -> unit

#### Related information 

Provide any related information 

* Operating system: Windows 10
* .NET Runtime (Framework 4.5)
* F# 4.0 (FSharp.Core 4.4.0.0)

**Comment by dsyme** [comment]
@AntonioL Please report to http://github.com/Microsoft/visualfsharp, thanks
