### ISSUE TITLE
Arch Fsharp infinite loop installation Problem

### ISSUE THREAD

**Issue by Stratos695** [fsharp/fsharp#626]
When I try to install [4.0.1.13-1](https://aur.archlinux.org/packages/fsharp/) with yaourt I get an infinite loop. I've copied a part of the log, can you help me? 

http://pastebin.com/0u5DKf0B

btw: Same issue if I edit the pkgbuild and try to use an older version.

I'm using mono 4.6.1.3 & mono-pcl 2014.04.14

Before you ask, I've read the [ build: hangs indefinitely on 'nuget restore issue ](https://github.com/fsharp/fsharp/issues/617) and tried to edit the NuGet.config and disable ssl, but it doesn`t work... The whole log looks different anyways.

**Comment by dsyme** [comment]
Strange.  Could you show a longer log?  That build log looks OK so far

**Comment by Stratos695** [comment]
Just tried to install it again to generate a longer log. This time it didnt't loop endlessly and worked right away. Thanks anyways. :)

**Comment by dsyme** [comment]
@Stratos695 Thanks for checking this, great to have this closed
