### ISSUE TITLE
fsi script start up is slow (5x slower than Microsoft fsi)

### ISSUE THREAD

**Issue by kflu** [fsharp/fsharp#627]
Even for the simplest script, it is very slow to start. Here're the info and measurements. I'm using Windows 10. I compare it with the "Microsoft" version, and it's 5x slower. Why?

```
PS C:\Users\brucew\work> type .\hi.fsx
printfn "%s" "hello world!"

# ------- The "free" fsi ------------
PS C:\Users\brucew\work> C:\fsi\fsi.exe
F# Interactive for F# 4.1
Freely distributed under the Apache 2.0 Open Source License

# ------- time it -------------
PS C:\Users\brucew\work> (Measure-Command { (0..10) | %{ C:\fsi\fsi.exe .\hi.fsx } }).ToString()
00:00:24.0280356

# ------- Microsoft fsi -------------
PS C:\Users\brucew\work> & 'C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe'
Microsoft (R) F# Interactive version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

# ------- time it -------------
PS C:\Users\brucew\work> (Measure-Command { (0..10) | %{ & 'C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe' .\hi.fsx } }).ToString()
00:00:05.1855948
```

**Comment by dsyme** [comment]
You need to run 

    ngen install c:\fsi\fsi.exe

**Comment by kflu** [comment]
Thanks @dsyme , I understand that ngen is to generate native image cache but I still have two questions:

1. Could it be something done at the package publication stage, or as part of the package installation? Using `ngen` requires Visual Studio installation so having customers to do this won't scale.
2. I've written quite some .NET applications and I never `ngen` any of them and still they are started fast. What's so special about `fsi.exe` that it has such a significant start up delay before `ngen`?

**Comment by dsyme** [comment]
@kflu The F# compiler (FSharp.Compiler.dll) is a significant chunk of code that's got a pretty long hot path.  The startup time per invocation is ~2.2seconds by the look of it.

NGEN can't be used at package publication time.  It is part of the .NET Framework though, so you may be able to arrange to have this done at install:

```

>dir \Windows\Microsoft.NET\Framework\v4.0.30319\ngen.exe

 Directory of C:\Windows\Microsoft.NET\Framework\v4.0.30319

08/12/2015  15:24           140,944 ngen.exe
               1 File(s)        140,944 bytes
               0 Dir(s)  11,066,617,856 bytes free
```

**Comment by kflu** [comment]
@dsyme ah didn't know it's part of the framework! Just tried ngen install it and it's now significantly faster.  It would be nice if this can be part of the package installation when this type of optimization is possible. I don't think regular user would know to do this kind of thing. If you agree then I can create a tracking issue for that improvement in the nuget package installation.
