### ISSUE TITLE
Question about FSharp.Core.dll versions for NuGet package "FSharp.Core".

### ISSUE THREAD

**Issue by Rodhern** [fsharp/fsharp#630]
#### Regarding older versions of FSharp.Core.dll in the FSharp.Core Nuget package.

Is it possible to get an FSharp.Core.dll built against .Net 3.5 included in the Nuget package?

Alternatively, how do I check that the file version 2.3.50727.0 of FSharp.Core.dll already included is licensed under the Apache license? (My Visual Studio redistributable one seems to have a license with this clause "You may not ... distribute Distributable Code to run on a platform other than the Windows platform; ..." in it).

B.t.w. Would I be better off asking over at https://github.com/Microsoft/visualfsharp ?

**Comment by dsyme** [comment]
@Rodhern There was an explicit clause in Visual Studio 2010/2012 licensing saying that FSharp.Core could be redistributed. Really, it's not a problem. 

What's your target platform for deployment?

**Comment by Rodhern** [comment]
@dsyme The target is Unity, which sometimes is run on a Windows platform and sometimes another platform. (In this case I am playing around with an add-on to the game Kerbal Space Program). Everything works fine, the only potential problem is that even though the FSharp.Core.dll file is explicitly mentioned as a redistributable, there is a set of conditions, one of which I quoted above. Anyway, thank you for answering.

At the moment I get errors if I try to compile with "/p:TargetFramework=net20"; was that always the case?

**Comment by dsyme** [comment]
@Rodhern TBH we no longer really try to compile FSharp.Core for .NET 3.5 and before.   It might be that you can easily patch up FSharp.Core.fsproj to compile (though don't even bother trying with the compiler itself)

**Comment by Rodhern** [comment]
That sounds like the way to go. Thank you.

Is it customary to leave the issue  ( #630 ) open to remind other users that the code (currently) won't compile to .NET 3.5 as-is, or do I close it now that I have gotten a good answer?

B.t.w. (unrelated): In README.md I think "ngen install ..\lib\proto\fsc-proto.exe" was supposed to be "ngen install lib\proto\fsc-proto.exe".

**Comment by dsyme** [comment]
@Rodhern It's customary to close, which I'll do, thanks
