### ISSUE TITLE
NuGet Profile78 dll doesn't contain printf functions

### ISSUE THREAD

**Issue by nosami** [fsharp/fsharp#631]
Reported on [Bugzilla](https://bugzilla.xamarin.com/show_bug.cgi?id=39063)
NuGet Profile78 dll doesn't contain [printf functions](https://github.com/fsharp/fsharp/blob/835b79c041f9032fceeceb39f680e0662cba92ec/src/fsharp/FSharp.Core/printf.fsi#L180-L205). Looking [here](https://github.com/Microsoft/visualfsharp/blob/1f6b0f75c73fb6e485a304560b062013167744c2/src/FSharpSource.targets#L284-L319), I don't see FX_NO_SYSTEM_CONSOLE defined, so not sure what is going on here. 

#### Repro steps

Provide the steps required to reproduce the problem

1. Add FSharp.Core NuGet package to an F# PCL project

2. FSharp.Core.4.0.0.1/lib/portable-net45+netcore45+wp8/FSharp.Core.dll should be referenced (3.78.4.0)

#### Expected behavior

Should see Printf.printf function available

#### Actual behavior

Most Printf functions are ifdeffed out

<img width="392" alt="screen shot 2016-10-27 at 15 17 49" src="https://cloud.githubusercontent.com/assets/667194/19770975/37055be4-9c59-11e6-8a22-ba98c6317abf.png">

#### Known workarounds

None

#### Related information 

OSX / Mono (although I don't think this is relevant)

**Comment by dsyme** [comment]
I think this is by design?  That System.Console is not available in Profile 78?

**Comment by nosami** [comment]
That's what I suspected at first, but then I saw https://github.com/Microsoft/visualfsharp/blob/1f6b0f75c73fb6e485a304560b062013167744c2/src/FSharpSource.targets#L284-L319 . So now I'm not sure :)

**Comment by nosami** [comment]
OK. It does define FX_NO_SYSTEM_CONSOLE. I'm going code blind. Thanks!
