### ISSUE TITLE
pown: unoptimal performance for negative n

### ISSUE THREAD

**Issue by miegir** [fsharp/fsharp#632]
Please consider file `prim-types.fs`, function `gpown` (currently at line [6198](https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/prim-types.fs#L6198)). When `n < 0`, the `PowGeneric` should be called with `-n` instead of `n`. Perhaps one should consider the corner case of `Int32.MinValue` as in generic variant of `pown`. This fix should be done also in every specialization of `pown`. Currently, the `pown x -1` expands to `1 / (1 * 1 * x)` and it gets worse for larger `n`.

Simple code to verify unoptimal behavior:
```F#
type N = 
    | N of string
    static member One = N "1"
    static member (*) (N a, N b) = N(sprintf "(%s * %s)" a b)
    static member (/) (N a, N b) = N(sprintf "(%s / %s)" a b)

let (N n) = pown (N "x") -1

printfn "%s" n // will print "(1 / ((1 * 1) * x))"
```

**Comment by dsyme** [comment]
@miegir Could you submit a PR to http://github.com/Microsoft/visualfsharp to fix this problem please?

This repo is for cross-platform issues

thanks
don

**Comment by miegir** [comment]
@dsyme Currently I have no PR and just reported this as an issue.

**Comment by dsyme** [comment]
Closing as this is not a x-plat issue
