### ISSUE TITLE
Executable bit not set for fsc.exe and fsi.exe in FSharp.Compiler.Tools package

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp#638]
Ideally the executable bit should be set for .EXEs in the tools directory of nuget packages so they can be run directly on Mono.  I don't know how to make this happen

**Comment by dsyme** [comment]
@forki Any idea how to do this?

**Comment by forki** [comment]
Urgs not sure if paket/NuGet could do it. We need real mono experts. 

/cc @7sharp9 @nosami @dnauck

**Comment by dsyme** [comment]
Yeah, [this search](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=set%20executable%20bit%20nuget%20package%20mono) doesn't reveal much

**Comment by 7sharp9** [comment]
I normally just use chmod if I need to set executable bits /shrug

**Comment by dsyme** [comment]
Yes, that's the workaround here: https://github.com/dsyme/visualfsharp/blob/ae5b3ec722b64b9d44a28050d128876bfb259aa3/before_install.sh#L18  

But it's wrong :)

**Comment by yishaigalatzer** [comment]
Cc @migueldeicaza

**Comment by dsyme** [comment]
@yishaigalatzer I suspect that this is a nuget issue.  Is it feasible for nuget to just set the executable bit on all .EXEs when it unzips?

**Comment by yishaigalatzer** [comment]
We could look at that, but I'd like to hear feedback from the mono guys first

**Comment by yishaigalatzer** [comment]
We are already "chmoding" some stuff in the shared lock folder path

**Comment by joelverhagen** [comment]
Yes, this is similar to the (still open) issue in NuGet where restoring from a different user on Linux fails:
https://github.com/NuGet/Home/issues/3897

The workaround is to manually `chmod` the file or directory in question. In this particular case, I would:
```bash
$ cd to/package/directory
$ chmod +x tools/fsc.exe
$ ./tools/fsc.exe
```

**Comment by nosami** [comment]
This is equivalent to `chmod +x` on Mono 

(rwx user, r group, r other)

```
open Mono.Unix.Native
let perms = FilePermissions.S_IRWXU ||| FilePermissions.S_IRGRP ||| FilePermissions.S_IROTH // 0x744
Syscall.chmod(FILENAME, perms) |> ignore
```

**Comment by dsyme** [comment]
@joelverhagen The nuget issue you mentioned about is now closed and fixed.  So is it now possible to set the executable bit - or does it get done automatically/  What happens if you're building a nuget package on Windows - is it possible to set the executable bit for when the package is unzipped on linux?  thanks

**Comment by dsyme** [comment]
The fix [here](https://github.com/Microsoft/visualfsharp/pull/2950) has been integrated

**Comment by matthid** [comment]
@dsyme yeah packaging on windows is still a problem.
Best is probably if nuget would support settings an executable flag in the nuspec and than properly saving that in the zip (http://stackoverflow.com/a/13633772/1269722). Paket probably needs to support that as well.

As a workaround for now we can try to edit the zip to have the required info. Would be interesting to see if nuget/paket properly respect the flag in the zip while unzipping (if not that would be another bug)
