### ISSUE TITLE
Using FSharp.Core nuget package causes a bad transitive dependency incompatible with .NETCoreApp 1.0

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp#642]
Using the PCL version of the FsCheck 2.6.2 component gives a transitive dependency on FSharp.Core nuget package.

This causes a bad transitive dependency incompatible with .NETCoreApp 1.0

This may be driver error, e.g. perhaps we have to qualify the frameworks w.r.t. the package reference. Ugh.

#### Repro steps

Take this project.,json:

    {
      "version": "1.0.0-*",
      "name": "FSharp.Core.Unittests",
      "dependencies": {
        "FsCheck": "2.6.2"
      },
      "frameworks": {
        "netcoreapp1.0": {
          "dependencies": {
            "Microsoft.NETCore.App": {
              "type": "platform",
              "version": "1.0.1"
            }
          },
        }
      },
    }

Run 

 nuget.exe restore

#### Expected behavior

restores ok

#### Actual behavior

```
 Errors in C:\GitHub\dsyme\visualfsharp\src\fsharp\FSharp.Core.Unittests\project.json
      Package FsCheck 2.6.2 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package FsCheck 2.6.2 supp
  orts:
        - net45 (.NETFramework,Version=v4.5)
        - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
        - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
        - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
      Project FSharp.Core is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Project FSharp.Core supports
  : netstandard1.6 (.NETStandard,Version=v1.6)
      One or more projects are incompatible with .NETCoreApp,Version=v1.0.
      One or more packages are incompatible with .NETCoreApp,Version=v1.0.
      Package FsCheck 2.6.2 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0) / osx.10.11-x64. Package Fs
  Check 2.6.2 supports:
        - net45 (.NETFramework,Version=v4.5)
```

#### Known workarounds

None

**Comment by dsyme** [comment]
@ctaggart @enricosada @KevinRansom Any guidance on what we need to do here would be much appreciated.  There's something wrong with the metadata in the combined FSharp.Core package, produced using these lines to merge the package:  https://github.com/fsharp/fsharp/blob/master/appveyor.ps1#L31

**Comment by dsyme** [comment]
Hmmm... I get exactly the same problem when using "Polly" version 2.2.1, which is a perfectly harmless C# component that only supported profile 259 back then
```
 - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
```
I don't understand why these components aren't usable in .NET Core 1.0 apps.

**Comment by dsyme** [comment]
@enricosada suggested I try this

```
{
  "version": "1.0.0-*",
  "name": "FSharp.Core.Unittests",
  "dependencies": {
    "Polly": "2.2.1",
    "Microsoft.NETCore.App": "1.0.1",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.1"
  },
  "frameworks": {
    "netcoreapp1.0": {}
  }
} 

```

but I can't get that to work

**Comment by enricosada** [comment]
another possible is to try add also (portable.compatiblity package is required anyway) in the framework section

```json
      "imports": [ "dnxcore50", "portable-net45+win8+wp8+wpa81" ]
```

**Comment by dsyme** [comment]
@enricosada I can't get that to work - can you?

**Comment by enricosada** [comment]
yes, added a [gist with readme and example project](https://gist.github.com/enricosada/02558b8962511e33f56b9d3b31fe8a7b)

**Comment by dsyme** [comment]
OK, working for me now 
```
{
  "version": "1.0.0-*",
  "buildOPtions": { },
  "dependencies": { },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.1"
        },
        "Microsoft.NETCore.Portable.Compatibility": "1.0.1",
        "FsCheck": "2.6.2"
      },
      "imports": [ "portable-net45+win8+wp8+wpa81" ]
    }

  }
}```

**Comment by dsyme** [comment]
I found I needed this when referencing .NET Standard 1.6 components too:

```
      "imports": [ "netstandard1.6", "portable-net45+win8+wp8+wpa81" ]
```
