### ISSUE TITLE
Add support for SPARCv9 and RISC-V (32 and 64-bit)

### ISSUE THREAD

**Issue by sunnystormy** [fsharp/fsharp#644]
Please provide a succinct description of the issue.

I would like to learn how to add support for these two open-source instruction set architectures, if the compiler can't already compile to these targets.

Provide the steps required to reproduce the problem

1. Step A

2. Step B

#### Expected behavior

Provide a description of the expected behaviour.

#### Actual behavior

Provide a description of the actual behaviour observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Editing Tools (e.g. Visual Studio Version)
* Links to F# RFCs or entries on http://fslang.uservoice.com
* Links to performance testing scripts
* Indications of severity

**Comment by jack-pappas** [comment]
This isn't an F# issue -- support for new processor architectures (like SPARCv9, RISC-V, MIPS, POWER) would need to be added in [mono](https://github.com/mono/mono) or [coreclr](https://github.com/dotnet/coreclr). When either of those projects supports the architecture(s) you want, it shouldn't require much work (if any) to get F# running on them.

Consider opening an issue on those projects to ask about support for SPARCv9 or RISC-V. Mono still has codegen support for older SPARC architectures; it looks like the code hasn't been touched in a while though, and may need to be updated for SPARCv9.

**Comment by dsyme** [comment]
Closing as this is a Mono or CoreCLR issue
