### ISSUE TITLE
Outdated man page in 4.0.0.4 (default version that ships with Ubuntu Xenial)

### ISSUE THREAD

**Issue by lilred** [fsharp/fsharp#646]
In Ubuntu Xenial, the [default package](http://packages.ubuntu.com/xenial/fsharp) has F# 4.0, but `man fsharpc` says "Compiler for the F# language, version 3.0".

**Comment by dsyme** [comment]
No idea where to fix this.  @directhex @RAOF  Any ideas?

**Comment by directhex** [comment]
Hi Don

You're right, this is a packaging issue. @RAOF added man pages in early 2014 (commands without man pages trip the automated Debian packaging linter), but whilst missing pages trip the linter, grossly obsolete ones don't.

https://anonscm.debian.org/cgit/pkg-cli-apps/packages/fsharp.git/log/debian/fsharpc.1
