### ISSUE TITLE
Using FSharp.Compiler.Tools compiler in Visual Studio -- debuggin doesn't work

### ISSUE THREAD

**Issue by sideeffffect** [fsharp/fsharp#648]
I'm trying to use the compiler from the package [`FSharp.Compiler.Tools`](https://www.nuget.org/packages/FSharp.Compiler.Tools) 4.0.1.20 in Visual Studio 2015 instead of the one installed with VS.
Compilation works OK, but it seems to emit only optimized code, so that debugging is pretty bad (variables optimized out, not hitting breakpoints, etc) -- regardless of the commandline switches that are passed to the compiler.

#### Repro steps

1. set the variable `FSharpTargetsPath` to `..\packages\FSharp.Compiler.Tools\tools\Microsoft.FSharp.targets` (was `$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets`) in your `.fsproj`

2. build the project in VS in Debug mode (now the `FSharp.Compiler.Tools` compiler is used)

```
...\packages\solutiontools\FSharp.Compiler.Tools\tools\fsc.exe
-o:obj\Debug\....dll
-g
--debug:full
--noframework
--define:DEBUG
--define:TRACE
--doc:...XML
--optimize-
--tailcalls-
--platform:x86
-r:...dll
--target:library
--warn:3
--warnaserror
--warnaserror:76
--vserrors
--LCID:1033
--utf8output
--fullpaths
--flaterrors
--highentropyva-
...fs
```

3. try debugging the project in VS

#### Expected behavior

the F# code is normally debuggable as was before

#### Actual behavior

VS complains that the code is optimized, some variables are now shown and some breakpoints are not hit

#### Related information 

How can I make the `FSharp.Compiler.Tools` compiler to produce unoptimized code? `--optimize-` is passed to it. Or is something wrong with VS?

link to F# Reddit discussion https://www.reddit.com/r/fsharp/comments/5fif96/using_fsharpcompilertools_compiler_in_visual/

**Comment by dsyme** [comment]
@sideeffffect Strange. It could plausibly be a bug in the compiler in that tools version, which may in turn represent a bug in Visual Studio 2017.  But that seems to be producing debug symbols OK.

@KevinRansom Note that this FSharp.Compiler.Tools package includes all debug symbol changes in VS2017. AFAIK it should produce debug code OK.

**Comment by dsyme** [comment]
@sideeffffect Could you please link to a ZIP with the necessary packages.config, source files etc.

**Comment by sideeffffect** [comment]
hi, I just realized that things work as they should with `FSharp.Compiler.Tools` 4.0.1.20. It was broken with 4.0.1.**1**0.
would you still like the testcase for the older broken version?

**Comment by dsyme** [comment]
No its ok, thanks for updating
