### ISSUE TITLE
Move sigdata and optdata into FSharp.Core

### ISSUE THREAD

**Issue by praeclarum** [fsharp/fsharp#649]
Currently, `FSharp.Core`'s sigdata and optdata are not stored in `FSharp.Core`. Instead they are put in parallel files to core.

I would like to suggest moving those files into `FSharp.Core.dll`.

### Past Rationale

> DLL size on small profile devices was the only justification. But old compilers require them separate
> [@dsyme](https://twitter.com/dsyme/status/806229188818698240)

Current file sizes on iOS are:

    1526272 Dec  1 08:07 FSharp.Core.dll
     326778 Dec  1 08:07 FSharp.Core.dll.mdb
     429831 Dec  1 08:07 FSharp.Core.optdata
     556780 Dec  1 08:07 FSharp.Core.sigdata
     704019 Dec  1 08:07 FSharp.Core.xml

That puts this data around 1 MB in size.

### Reason for Change

To make using FSharp.Core more reliable.

Currently we have to

1. Remember to bring these two extra files along with the assembly
2. Work to make sure we don't use the wrong metadata

I don't believe the perceived benefit of smaller mobile apps outweighs the mistakes made when using FSharp.Core.

Thank you for considering this!

**Comment by dsyme** [comment]
@praeclarum please move to Microsoft/visualfsharp as change is need there

**Comment by praeclarum** [comment]
Reposted as https://github.com/Microsoft/visualfsharp/issues/1953
