### ISSUE TITLE
Reflection gives unexpectedly different results for single and multicase discriminated unions

### ISSUE THREAD

**Issue by mavnn** [fsharp/fsharp#650]
Calling ``.GetType().Name`` on an instance of a multicase discriminated union reports reports the case name, while calling it on an instance of a single case union reports the union name. This is confusing at best.

#### Repro steps

1. Create two union types, one with a single case and one with several

```
type SimpleUnion =
  | Number of int
  | Text of string

type SimpleSingleUnion =
  | SingleCase of string
```
2. Get the type name of an instance of each:

```
> (Number 10).GetType().Name;;
val it : string = "Number"
> (SingleCase "bob").GetType().Name;;
val it : string = "SimpleSingleUnion"

```

#### Expected behavior

That both would report either the case name or the union name.

#### Actual behavior

Single case unions report the union name, while multicase unions report the case name.

#### Known workarounds

Further nasty reflection on the instance

#### Related information 

Provide any related information 

* Mac OSX
* mono 4.6.2
* Indications of severity: minor

**Comment by mavnn** [comment]
Unfortunately while this feels like a bug, fixing it probably causes backwards compatibility issues :(

**Comment by 7sharp9** [comment]
Needs to go to Visualfsharp repo.

**Comment by dsyme** [comment]
We'd treat this as by-design in any case.  Use FSharp.Reflection.FSharpType.* to get consistent refelection for union types
