### ISSUE TITLE
Redefine some of the top-level operators to allow for custom functionality [suggestion]

### ISSUE THREAD

**Issue by royalstream** [fsharp/fsharp#658]
Most of the desirable unary operators have global definitions that make them unsuitable for operator overloading (for custom types). Redefining them is usually not an option because you lose the standard behavior which could break existing code.

But sometimes they can be redefined in such a way that the standard behavior remains unaffected while allowing for custom behavior.

For example, the ! operator could be redefined like this:

```fsharp
type ExclamationDefaults() = class end

let inline (!) x = 
    let inline aux (a: ^a, b: ^b) = ( (^a or ^b) : (static member op_Exclamation: ^b -> _) b)
    aux (ExclamationDefaults(), x)

type ExclamationDefaults with static member op_Exclamation(x:'a ref) = x.contents
```

This works as usual with references but allows the implementation of custom functionality for other types.

**Comment by dsyme** [comment]
@royalstream Please submit to http://github.com/fsharp/fslang-suggestions

**Comment by royalstream** [comment]
Will do. Thanks.
