### ISSUE TITLE
Add the signed FSharp.Core's for F# 4.1 (4.4.1.0 etc) to lib/bootstrap/signed

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp#659]
Now F# 4.1 is basically finalized we need to add the signed F# 4.1 FSharp.Core to https://github.com/fsharp/fsharp/tree/master/lib/bootstrap/signed and publish a new FSharp.Core nuget package 4.1.0.0

(We then have to work out how to align this with the Microsoft nuget for FSharp.Core on .NET Core https://www.nuget.org/packages/Microsoft.FSharp.Core.netcore/1.0.0-rc-170122, possible by just listing it as a dependency, even if the dependency is meaningless for .NET Framework development?)

**Comment by enricosada** [comment]
@dsyme is better to not use two packages (create issues with restore ihmo, because will not declare support for netstandard).
We should

- add netstandard assemblies in `netstandard1.6` folder
- specify deps (valuetuple) in nupkg under framework

and publish an -rc1

**Comment by enricosada** [comment]
added as ref for [new sdk roadmap](https://github.com/dotnet/netcorecli-fsc/wiki/Roadmap)

**Comment by dsyme** [comment]
@enricosada Great, thanks
