### ISSUE TITLE
Remove restriction on static linking

### ISSUE THREAD

**Issue by nosami** [fsharp/fsharp#665]
The restriction on static linking across different profiles was removed in the visualfsharp repo here :-
https://github.com/Microsoft/visualfsharp/pull/1741/commits/860256774df4b65b0e47eb8ece04b7e9a9bbf361#diff-0e57ebf050db850b5efdd7e2cb13e725

to fix https://github.com/Microsoft/visualfsharp/issues/99

Is there any reason that this hasn't been merged across? It fixes an issue with a Xaml type provider for Xamarin Forms that I'm working on.

**Comment by dsyme** [comment]
@nosami It has been merged recently, we just need to move Mono to tag 4.0.1.22.  I think we can proceed with that now?

**Comment by nosami** [comment]
@dsyme Thanks! 4.0.1.22 is working for me!
