### ISSUE TITLE
Target lower .NET Standard

### ISSUE THREAD

**Issue by dustinmoris** [fsharp/fsharp#669]
Hi, to [follow up on this](https://github.com/dustinmoris/AspNetCore.Lambda/issues/21) I would like to ask if there was a reason that FSharp.Core is targeting NETStandard 1.6 at the moment or if the target could be lowered perhaps?

Basically the lower you can set the target while the project still builds the better it is, because it will allow more projects to use it.

**Comment by dsyme** [comment]
Continuing discussion from https://github.com/fsharp/fsharp/issues/566#issuecomment-280942892

cc @cartermp @KevinRansom 

@dustinmoris   Please add a specific request for this to http://github.com/Microsoft/visualfsharp, as the choice of .NET Standard originates from there

> Right now there are barely any runtimes that support .NET Standard 1.6, and the official advice is to use 1.4 until 2.0 is ready. 

The FSharp.Core package includes Profile259, Profile78, Profile7 binaries if you want to use those instead as the basis for your libraries. It also includes .NET 4.5 of course 

> Additionally, many of the APIs that are available in .NET Standard 1.5 and 1.6 are going to be removed in 2.0

My impression was that this had been cancelled and that 2.0 would be compatible with 1.6.  Does anyone have a latest authoritative reference link?  thank you

**Comment by enricosada** [comment]
@dsyme they are right, we should lower but atm all deps/tarfgget version is the same of `Microsoft.FSharp.Core.netcore`.

target fw is not related to `NEtstandard.Library`.

**Comment by dsyme** [comment]
@enricosada OK thanks. Any chance you could lower the target in http://github.com/Microsoft/visualfsharp?  is it possible? thanks

**Comment by enricosada** [comment]
Yes, i'll open an issue in visuafsharp repo. 
I wanted to do that later (but before VS RTM), to cleanup deps a bit.

we need to:

- lower netstandard (ref [netstandard version matrix](https://github.com/dotnet/standard/blob/master/docs/versions.md)), probably netstandard1.1 or 1.0 is ok
- check deps (both fsharp.core and fsc), to remove duplicated because transitivive (maintanance) and check package versions to be the same used in `NETSTandard1.6` apckage (no strange resolution).

**Comment by enricosada** [comment]
we can lower version `netstandard` version there (just fixing nuspec). but better fix origin so doesnt diverge

**Comment by enricosada** [comment]
added https://github.com/Microsoft/visualfsharp/issues/2501 to discuss in visualfsharp repo, because here we just repackage the `Microsoft.Fsharp.Core.netcore` package into `FSharp.Core`
