### ISSUE TITLE
FSharp.Core.4.1.0.nupkg packaged incorrect

### ISSUE THREAD

**Issue by matthid** [fsharp/fsharp#672]
While the package contains the net40 folder, this folder contains binaries compiled against net45 (can be easily checked by downloading the package and verifying with dotpeek).

This leads to various problems like:
```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3274: The primary reference "FSharp.Core" could not be resolved because it was built against the ".NETFramework,Version=v4.5" fr
       amework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0". [C:\PROJ\FAKE\src\deploy.web\Fake.Deploy.Web.DataProviders\Fake.Deploy.Web.File\Fake.Deploy.Web.File.fsproj]
```

I think this even introduced a runtime error in the FAKE test suite after updating FSharp.Core.

While looking at this it seems like the net20 binary is wrong as well and was already wrong in https://www.nuget.org/packages/FSharp.Core/4.0.0.1

We should either provide a proper net40 binary or package it into the net45 folder... If we drop 40 support we should update the description of the package accordingly.

**Comment by smoothdeveloper** [comment]
somehow related: https://github.com/Microsoft/visualfsharp/issues/2513

**Comment by matthid** [comment]
@smoothdeveloper thanks, yes this seems very related indeed. So did they drop support for net40? Otherwise I'm not sure if closing the issue was correct (well at least I don't get it)... /cc @dsyme

**Comment by cdrnet** [comment]
I hope not - dropping net40 or net20 would mean downstream library packages would have to depend on different versions of the FSharp.Core package depending on the target, which is a nightmare (and not supported by Paket)

**Comment by smoothdeveloper** [comment]
@cdrnet AFAIU paket supports several platforms within single nuget, in the project file it has the conditionals around the selected target framework, switching selected framework will effectively switch the references.

**Comment by matthid** [comment]
@smoothdeveloper yes but not different package versions for different frameworks... as soon as a package drops a framework paket will still update it and msbuild will scream at you about missing or wrong references. You need paket groups for this.

Let's stay on topic (FSharp.Core packaging) because I need to know if this was a simple error or a decision to drop support (like @cdrnet said would hurt older projects)

**Comment by dsyme** [comment]
@matthid My understanding is that FSharp.Core for F# 4.0 (assembly version 4.4.0.0, nuget package version 4.0.0.1)  and beyond have assumed .NET 4.5, in the sense that they were built against that set of reference assemblies (they were likely tested against a slightly higher version at runtime).    In practice I assume the libraries worked for essentially all purposes against .NET 4.0

However the TargetFrameworkVersionAttribute for .NET 4.5 has only been included as of FSharp.Core for F# 4.1 (assembly version 4.4.1.0, nuget package version 4.1.0) which would explain why you're only seeing this now.    I believe this assembly version would have been added by the switch to use the "Microbuild" targets

I think this fits with the attributes and messages you are seeing.   **It seems we should definitely move the assembly to "net45" folder in the nuget package**

If you want to build F# components for .NET 4.0 you should continue to use FSharp.Core for F# 3.1 or 4.0 (assembly versions 4.3.1.0 or 4.4.0.0).  Is there anything specific that will go wrong with that?

**Comment by matthid** [comment]
> If you want to build F# components for .NET 4.0 you should continue to use FSharp.Core for F# 3.1 or 4.0 (assembly versions 4.3.1.0 or 4.4.0.0). Is there anything specific that will go wrong with that?

@dsyme Yes @cdrnet said it will be a pain for paket users as paket will happily update the package and you will get missing references (well you will probably get downgraded to default F#?)

I think we have two options:
 - Keep compiling for net40 here in this repository (and add the current build to the net45 folder)
 - distribute the old build/binary with the new package (and move the current one to the net45 folder).

@forki might have another idea....

**Comment by dsyme** [comment]
> distribute the old build/binary with the new package (and move the current one to the net45 folder).

I think this is the correct approach (it's what we do with net20 - though someone indicated there's a problem with that, is there?)

> Keep compiling for net40 here in this repository (and add the current build to the net45 folder)

Just to say that the nuget package bundles the fully signed DLL from Microsoft, so this doesn't help...

**Comment by dsyme** [comment]
@matthid Any chance you could you submit a PR to correct the paths in the nuget package? thanks

**Comment by matthid** [comment]
@dsyme where to take the the old binary (and which one). IE should I checkin the old binary or download it from nuget?

I can take a look at the net20 binary as well. Can you recall where there was a problem with them beeing the old ones (F#3.0? what was the last supported version for net20?).

**Comment by matthid** [comment]
Or remove net20 as I don't think it was usable in the current form...

**Comment by enricosada** [comment]
@matthid you can find old signed assemblies in https://github.com/fsharp/fsharp/tree/master/lib/bootstrap/signed/.NETFramework/v4.0

**Comment by matthid** [comment]
@enricosada So its already in the repository, didn't notice that, thanks :)

**Comment by matthid** [comment]
@dsyme done

**Comment by matthid** [comment]
I think this is kind of urgent to fix, so I'll reopen until a new package was released...

**Comment by dsyme** [comment]
4.1.0.2 pushed (though I don't think it will solve the linked problem - see my comment there)
