### ISSUE TITLE
Investigate if and how FSharp.Compiler.Tools can override FSharpTargetsPath

### ISSUE THREAD

**Issue by 0x53A** [fsharp/fsharp#676]
Currently the targets is always taken from the (assumed to be) installed visual studio. It should be possible to include ``Microsoft.FSharp.Targets`` in the nuget and use that.

Ref https://github.com/Microsoft/visualfsharp/pull/2575
Ref https://github.com/fsharp/fsharp/pull/675

If you want to use the targets file from the nuget package, you can replace 

```Xml
  <Choose>
    <When Condition="'$(VisualStudioVersion)' == '11.0'">
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </Otherwise>
  </Choose>
  <Import Project="$(FSharpTargetsPath)" />
```

with 

```Xml

  <PropertyGroup>
    <FSharpTargetsPath>$(FscToolPath)\Microsoft.FSharp.Targets</FSharpTargetsPath>
  </PropertyGroup>
  <Import Project="$(FSharpTargetsPath)" />
```

**Comment by 0x53A** [comment]
Note: C# / VB have an explicit ``Microsoft.CSharp.Core.targets``, which contains just the ``CoreCompile`` target. That allows them to override just that from ``Microsoft.Net.Compilers``, taking advantage of possible new compiler options (e.g. Deterministic) without touching the rest.

We have everything in one file, so we can only override everything or nothing.

This actually looks smart, would it be possible to emulate that?

**Comment by dsyme** [comment]
> This actually looks smart, would it be possible to emulate that?

This is a bit beyond me - and may be moot because of the new .NET SDK?  

(I'll close this issue but pease feel free to submit PRs to here and Microsoft/visualfsharp if you think they need it)

**Comment by divad4686** [comment]
This break my whole team solution because they don't have the package installed in their machine, making the project unable to load. Is there a better solution?

**Comment by divad4686** [comment]
I ended up putting it like this:
`<Choose>
    <When Condition="Exists('$(FscToolPath)\Microsoft.FSharp.Targets')">
      <PropertyGroup>
        <FSharpTargetsPath>$(FscToolPath)\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <When Condition="'$(VisualStudioVersion)' == '11.0'">
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </Otherwise>
  </Choose>  `

So my team can load the project on their local environment where they have visual studio installed and we can still use msbuild 15 in our C.I server.

**Comment by yodiz** [comment]
When replacing with:
```
  <PropertyGroup>
    <FSharpTargetsPath>$(FscToolPath)\Microsoft.FSharp.Targets</FSharpTargetsPath>
  </PropertyGroup>
  <Import Project="$(FSharpTargetsPath)" />
```
The intellisense works and compiling works. But if i close Visual Studio and open it again the intellisense stops working. 

It starts to work if i unload the project, and insert a blankspace somewhere, save and reload the propject again however.

Any other workarounds?
