### ISSUE TITLE
FSharp.org is HTTP (should be HTTPS)

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#678]
The link at the top of this repo is towards http://fsharp.org/

Nowadays we should be using HTTPS, at the very least to show that F# is a modern language, but also to ensure the authenticity of data sent from the server to the client and avoid behavioural tracking or interception is what may very well be an infrastructure-critical language/reference site.

**Comment by dsyme** [comment]
THis is an issue for http://github.com/fsharp/fsfoundation
