### ISSUE TITLE
use major.minor.patch for packages

### ISSUE THREAD

**Issue by enricosada** [fsharp/fsharp#682]
the `FSharp.Core` package use 4 digits (like `4.1.0.2`)

the nuget is going [to use semver 2.0](https://github.com/NuGet/Home/wiki/SemVer-2.0.0-support) and will already try to [normalize version numbers](https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions#normalized-version-numbers) at resolution phase.

I think is better to just embrace semver versioning, so three digits.
So instead of `FSharp.Core` `4.1.0.2` -> `4.1.2` 

Same for `FSharp.Compiler.Tools`

/cc @forki @dsyme

**Comment by dsyme** [comment]
Sure. Please submit a PR if you like to bump to 4.1.2?
