### ISSUE TITLE
FSharp.Build .net full is not aligned to netcore version in FSharp.Compiler.Tools nupkg

### ISSUE THREAD

**Issue by enricosada** [fsharp/fsharp#684]
in `FSharp.Compiler.Tools` 4.1.1

the `/tools/FSharp.Build.dll` is stale (for example the Fsc task doesnt support `SkipCompilation` property).
the `/build/netcoreapp1.0/FSharp.Build.dll` is up to date

/cc @mrward 

using new fsproj, the error will be

```
~/.nuget/packages/fsharp.net.sdk/1.0.2/build/FSharp.NET.Core.Sdk.targets(210,15): error MSB4064: The "SkipCompilerExecution" parameter is not supported by the "Fsc" task. Verify the parameter exists on the task, and it is a settable public instance property. [~/Projects/Tests/abc.fsproj]
~/.nuget/packages/fsharp.net.sdk/1.0.2/build/FSharp.NET.Core.Sdk.targets(170,9): error MSB4063: The "Fsc" task could not be initialized with its input parameters.  [~/Projects/Tests/abc.fsproj]
```

workaround for that is use `FSharp.NET.Sdk` 1.0.1 (not 1.0.2)

**Comment by dsyme** [comment]
We have to fix this one :)

**Comment by enricosada** [comment]
I'll merge my single commit from vf# repo, and do another package refresh.

**Comment by enricosada** [comment]
And add some smoke test, because now are easy:

- install .net core sdk 1.0
- `dotnet new console -lang f#`

and for both `dotnet`, `msbuild`, and `mono msbuild`
- `restore` with new packages
- `build`
- `run`

so like that will be ok a smoke test

**Comment by dsyme** [comment]
Fixed, thanks
