### ISSUE TITLE
Spelling typos (comments in .fs{i} files - 'src' directory)

### ISSUE THREAD

**Issue by Fourchaux** [fsharp/fsharp#705]
Reading all the comments of files (.fs .fsi) present in the 'src' directory only, 
I have noted down a certain number (264 - yep!) of very basic spelling typos 
(like appying, bootsrap, alwauys ....).

I could make a PR with corrections of these small typos,
but my questions are : is this kind of PR problematic for you? would you accept it?

**Comment by dsyme** [comment]
@Fourchaux Yes, we would accept a PR :) Please submit to http://github.com/Microsoft/visualfsharp and we will integrate it to here.  Don't bother running tests locally if you are just changing comments - the CI testing will be enough

**Comment by Fourchaux** [comment]
Thank you.

PR submitted !
