### ISSUE TITLE
Array.init malfunction: function to generate the elements executed only once

### ISSUE THREAD

**Issue by derdanielb** [fsharp/fsharp#708]
Hello everybody,

i observed a (possible?) malfunction when using `Array.init`. 
The function to generate the elements is executed only once in total for all fields of the array.

Given:

**generateRandomPermutation**: A function that generates a random permutation of indices (0 to someGlobalArray.Length-1)

`let permutationsArray = Array.init 10 (fun _ ->  generateRandomPermutation)`

This should set *permutationsArray* to an array with 10 different permutations. But it gives me an array with 10 times the same permutation. *generateRandomPermutation* is only executed once, i checked with a print statement.

If i change *generateRandomPermutation* to accept a dummy parameter (and just ignore the dummy) i am getting in return what i expected to get from the first code example, namely 10 different permutations:

`let permutationsArray = Array.init 10 (fun _ ->  (generateRandomPermutation 0))`

My guess is, this has something to do with the compiler erroneously interpreting the function to return the same value each call when there is no parameter involved. And so it might try to save resources calculating the value only once.

I am using the lastest Visual Studio Enterprise 2017, Version 15.1 (26403.0) Release
in a simple F# console application (currently working with only one .fs file):
F# 4.1 (FSharp.Core, 4.4.1.0)
.NET Framework 4.5.2 (though im not using any .net stuff activly)
Windows 10 Education Version 1607 (Buildd 14393.969)

**Comment by rojepp** [comment]
It looks like `generateRandomPermutation` is a value, and not a function. 

Functions that take no parameters take the unit `()` in F#. 

```fsharp
let rnd = System.Random()
let generateRandomPermutation () = 
    rnd.Next ()
```

Then you can do

```fsharp 
let permutationsArray = Array.init 10 (fun _ -> generateRandomPermutation ())
```

If you'd like to encapsulate `rnd` above, you could make `generateRandomPermutation` a value that returns a function:

```fsharp
let generateRandomPermutation = 
   let rnd = System.Random()
   (fun () -> rnd.Next ())
```

**Comment by derdanielb** [comment]
Oooh! Thanks for pointing out the function syntax. I was not aware of this (i just started with F# yesterday).
The double brackets make my function work.
Thank you!

I guess i will close this issue now
