### ISSUE TITLE
Installing FSharp.Core via NuGet adds unwanted files to project

### ISSUE THREAD

**Issue by brianberns** [fsharp/fsharp#728]
#### Repro steps

1. Create an F# project
2. Use NuGet to install FSharp.Core v4.1.12

#### Expected behavior

FSharp.Core files are added only under `packages` directory.

#### Actual behavior

The following FSharp.Core files are added to the project's source code directory and appear in the Solution Explorer.

- any/netstandard1.6/FSharp.Core.sigdata
- any/netstandard1.6/FSharp.Core.optdata

#### Related information 

Example: https://i.stack.imgur.com/tgkSr.png

**Comment by dsyme** [comment]
See https://github.com/fsharp/fsharp/pull/723 and discussion linked there

**Comment by dsyme** [comment]
This is fixed with latest FSharp.Core 4.1.17 package
