### ISSUE TITLE
FSharp.Compiler.Tools should choose bundled .net core runtime for fsc

### ISSUE THREAD

**Issue by enricosada** [fsharp/fsharp#737]
A .net core sdk can bundle different .net core runtimes, so fsc must run with the runtime bundled with sdk.
It doesnt matter for mono/.net (yet) because we expect `net40` to beenough to run fsc.exe.

With .net core sdk 1.0, both runtimes (1.0 and 1.1) are bundled, but in some os just 1.1 is bundled (because FCT package just embedd `netcoreapp1.0`, it doesnt work for some os, ref https://github.com/dotnet/netcorecli-fsc/issues/76 )

Atm with .net core sdk 2.0, only the 2.0 .net core runtime is bundled.

So we need to:

- get a fsc built for `netcoreapp2.0` and embeed it in `build/netcoreapp2.0` (ref https://github.com/dotnet/netcorecli-fsc/issues/92 )
- understand how to choose the right version (this issue)

Atm if msbuild runtime is `Core` -> use `build/netcoreapp1.0` (ref [FSharp.Compiler.Tools.props#L37-L44](https://github.com/fsharp/fsharp/blob/9e7fa298bc28eca475d7ba614ffc849fe5ff91ad/FSharp.Compiler.Tools.Nuget/build/FSharp.Compiler.Tools.props#L37-L44), but that's not enough because bundled runtime can be 1.0, 1,1 or 2.0.

With sdk 2.0, we can use some new msbuild property to discriminate bundled runtime.

```
BundledNETCoreAppPackageVersion = 2.0.0-preview1-002101-00
BundledNETCoreAppTargetFrameworkVersion = 2.0
BundledNETStandardPackageVersion = 2.0.0-preview1-25227-01
BundledNETStandardTargetFrameworkVersion = 2.0
```

So probably `BundledNETCoreAppTargetFrameworkVersion` is enough. 
@livarcocc @dsplaisted @eerhardt Any feedback on this ?

/cc @dsyme @cartermp 

As a note, also `DotnetCliToolTargetFramework = netcoreapp2.0` exists, but is maybe `MSBuildRuntimeType = Core` and `BundledNETCoreAppTargetFrameworkVersion` is better

**Comment by eerhardt** [comment]
How does `fsc` get invoked?  Is it through a CLI tool?  Or is it some other mechanism?

I think using `BundledNETCoreAppTargetFrameworkVersion` should be fine - this is pretty much what this property was designed to do - figure out the runtime that came with the SDK and is guaranteed to be there.

BTW - in 2.0, `DotnetCliToolTargetFramework` gets defaulted from `BundledNETCoreAppTargetFrameworkVersion`.

https://github.com/dotnet/sdk/blob/release/2.0.0/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.Common.targets#L31-L34

/cc @nguerrera to see if he has any dissenting opinions on using these properties.

**Comment by enricosada** [comment]
@eerhardt fsc is published as FDD console app, and bundled inside package, so in `build/netcoreapp1.0` for 1.0, in `tools` for net40 (backward compatibilkity otherwise was in `build/net40`).
And we use msbuild props to default the right fsc to use.

yes, i think too `BundledNETCoreAppTargetFrameworkVersion` is enough, i just want to know if here to stay for long term :D

**Comment by eerhardt** [comment]
But how is it invoked?

Where is the `dotnet` host retrieved from?
What are the arguments passed in?  Do you say `dotnet fsc` or do you say `dotnet /path/to/fsc.dll`?

**Comment by enricosada** [comment]
the `dotnet` (for `dotnet /path/to/fsc.dll` ) is resolved as relative from Sdks [here](https://github.com/dotnet/netcorecli-fsc/blob/master/src/FSharp.NET.Sdk/build/FSharp.NET.Core.Sdk.targets#L154) as

```xml
<_DotNetHostExecutableDirectory>$(MSBuildSDKsPath)/../../..</_DotNetHostExecutableDirectory>
```

for msbuild and mono, we just `/path/to/fsc.exe` and `mono /path/to/fsc.exe` so `dotnet` doesnt matter, we use fsc built for .net framework.

@eerhardt i already added https://github.com/Microsoft/msbuild/issues/1669 to ask about it, but no progress afaik.

**Comment by nguerrera** [comment]
I'm fine with using BundledNETCoreAppTargetFrameworkVersion. It is designed to be available to extenders.

**Comment by dsyme** [comment]
@enricosada I think we can close this now, correct, given that the F# support is directly in .NET SDK 2.0?  I think FSHarp.Compiler.Tools is now only being used for .NET Framework/Mono execution of the compiler?
