### ISSUE TITLE
Type Provider(s) cannot be used with Mono 5

### ISSUE THREAD

**Issue by sergey-tihon** [fsharp/fsharp#738]
Here is the issue of TP compilation - https://github.com/fsprojects/SwaggerProvider/issues/75#issuecomment-300400961

Reproduced on Mono:
- [beta](https://travis-ci.org/fsprojects/SwaggerProvider/jobs/230629593) = `(Stable 5.0.0.94/1d0445b Wed May  3 17:40:24 UTC 2017)`
- [nightly](https://travis-ci.org/fsprojects/SwaggerProvider/jobs/230629594) = `(Nightly 5.3.0.262/137e1e7 Tue May  2 14:47:25 UTC 2017)`

I see a lot of messages from the compiler 

> non-IL or abstract method with non-zero RVA

[there are couple](https://travis-ci.org/fsprojects/SwaggerProvider/jobs/230629593#L1905-L1908) directly before an error from TP compilation. So it may be related.

Here is a place in F# compiler that prints it - https://github.com/fsharp/fsharp/blob/master/src/absil/ilread.fs#L2358

#### Repro steps

Provide the steps required to reproduce the problem

**Option 1**:

1. Install `Mono 5`

1. Check out `https://github.com/sergey-tihon/SwaggerProvider/tree/mono5`

1. Execute `./build.sh`

1. This branch is compiled on Travis in this PR https://github.com/fsprojects/SwaggerProvider/pull/76

**Option 2**

1. Install `Mono 5`

1. Reference [SwaggerProvider](https://www.nuget.org/packages/SwaggerProvider)

1. Compile sample
```fsharp
#load @"packages/SwaggerProvider/SwaggerProvider.fsx"
open SwaggerProvider

let [<Literal>]schema = "http://petstore.swagger.io/v2/swagger.json"
type PetStore = SwaggerProvider<schema> // Provided Types
let petStore = PetStore() // Instance for communication
```

#### Expected behavior

Compile should compile the code without errors. Everything works correctly on `Stable 4.8.1.0/22a39d7 Wed Apr 12 12:00:40 UTC 2017`.

**Comment by knocte** [comment]
> Everything works correctly on Stable 4.8.1.0/22a39d7 Wed Apr 12 12:00:40 UTC 2017.

If this works in a previous version of Mono, it's a Mono regression. Please report it here: http://bugzilla.xamarin.com/

**Comment by nosami** [comment]
> If this works in a previous version of Mono, it's a Mono regression
Not necessarily but it could be. fsharp/fsharp has been updated to 4.1.8

**Comment by knocte** [comment]
So what needs to be tested here is the older version of F# with the new version of Mono?

**Comment by nosami** [comment]
Can't do that easily as the old version of F# has issues with the new mono :)

I'm going to start by debugging the TP.

**Comment by nosami** [comment]
<img width="923" alt="screen shot 2017-05-10 at 11 05 55 am" src="https://cloud.githubusercontent.com/assets/667194/25893695/b82b9ffc-3570-11e7-8ec9-47c7467bcad7.png">

**Comment by nosami** [comment]
I see the problem and it has an easy fix :)

**Comment by dsyme** [comment]
Yeah, had thought it was probably that

@nosami Maybe we need to search the internet for ``TypeBuilderInstantiation``...  Or at least duplicates of that mono-specific logic...

**Comment by nosami** [comment]
ProvidedTypes comes from paket in this case, so updating it in the one place will fix things for many.

**Comment by nosami** [comment]
I've changed it to this locally

```fsharp
    let TypeBuilderInstantiationType = 
        let runningOnMono = try System.Type.GetType("Mono.Runtime") <> null with e -> false 
        let ty = typeof<TypeBuilder>.Assembly.GetType("System.Reflection.Emit.TypeBuilderInstantiation")
        match ty, runningOnMono with
        | null, true -> typeof<TypeBuilder>.Assembly.GetType("System.Reflection.MonoGenericClass")
        | _ -> ty
```

**Comment by nosami** [comment]
<img width="754" alt="screen shot 2017-05-10 at 11 56 46 am" src="https://cloud.githubusercontent.com/assets/667194/25895440/c7f2d26e-3577-11e7-943e-2603544b5cc7.png">

**Comment by sergey-tihon** [comment]
What actually `non-IL or abstract method with non-zero RVA` means? There are a lot of them during compilation on Mono 5.

**Comment by dsyme** [comment]
The necessary update to the ProvidedTypes SDK is here: https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/pull/120.  Type providers that are not working with Mono 5.0 will need to be updated to use an updated version of ProvidedTypes.fs and republished.

**Comment by dsyme** [comment]
Let's track the need to update various type providers here: https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/121
