### ISSUE TITLE
fsharpi fails with error FS0193 on mono 5.0

### ISSUE THREAD

**Issue by Zinggi** [fsharp/fsharp#740]
Since I updated to mono 5.0 I've got this weird issue when using fsharpi:
`error FS0193: Specified method is not supported`
It only happens when I try to run stuff from fsharpi, not when I compile and run.

I managed to create an absurdly small example that triggers the error for me:

```fsharp
// in problem.fsx
let f a =
    match a with
    | [] ->
        true
    | _ ->
        true
```

then:
```
↪ fsharpi problem.fsx 


error FS0193: Specified method is not supported.
```

#### Related information 
F\# version:
`F# Interactive for F# 4.1`

My mono version:
```
↪ mono --version
Mono JIT compiler version 5.0.0 (Stable 5.0.0.100/9667aa6 Fri May 12 07:20:13 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

OS:
`Arch Linux`
Kernel:
`x86_64 Linux 4.10.13-1-ARCH`

**Comment by Zinggi** [comment]
I just managed a much smaller example:

```fsharp
F# Interactive for F# 4.1
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [1; 2];;
val it : int list = [1; 2]
> [1];;
val it : int list = [1]
> [];;


error FS0193: Specified method is not supported.
```

So to me it seems like the empty list is triggering this error.


Also, it might be related to #739, since it's the same error code.

**Comment by Zinggi** [comment]
Update:
Downgrading to mono 4.8.0 solved the issue for me, so only version 5.0.0 is causing problems with fsharpi.

**Comment by dsyme** [comment]
@nosami could you take a look?  

@Zinggi Have you tried compiling from master?

**Comment by Zinggi** [comment]
@dsyme no, I haven't tried with the master branch yet.

I'm using what's included in my distro, that is version `4.0.1.21-1` (https://www.archlinux.org/packages/extra/any/fsharp/)

If I find the time I can try compiling the master branch

**Comment by nosami** [comment]
```
13:00 $ fsharpi

F# Interactive for F# 4.1
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> let f a =
-   match a with
-   | [] ->
-     true
-   | _ ->
-     true;;
val f : a:'a list -> bool

> [];;
val it : 'a list

>
```
Working for me on OSX with Mono 5.0.0.100. I think the `fsharp` package needs to be upgraded in Archlinux

**Comment by Zinggi** [comment]
I can confirm that the error vanishes with `fsharp 4.1.18-1`.

The official arch package is still not updated, but this version can already be found in [testing](https://www.archlinux.org/packages/testing/any/fsharp/).

**Comment by knocte** [comment]
I can find this bug when using stock versions of mono(5.16.0.220+dfsg3-1ubuntu1) and fsharp(4.0.0.4+dfsg2-2) included by default in Ubuntu 19.04 previews.

@directhex do you mind confirming if you see the same thing in the version of Debian that already includes Mono 5.16.x please?

**Comment by knocte** [comment]
@RAOF hey Christopher, by any chance a F#4.1 version can still be uploaded in time for Ubuntu 19.04? otherwise fsx scripts will not be able to run in this version of Ubuntu.

**Comment by directhex** [comment]
@knocte confirmed.
