### ISSUE TITLE
Change history release notes

### ISSUE THREAD

**Issue by Thorium** [fsharp/fsharp#742]
Seems like the version numbers are not in sync, not between Microsoft/visualfsharp and fsharp/fsharp, neither inside one repository:

`CHANGELOG-fsharp.md` (4.1.15 is the latest), 
the Nuget package `https://www.nuget.org/packages/FSharp.Core/` (4.2.0 is the latest)
commit messages at Microsoft/visualfsharp@ae8ff773152620beb9dbb2c134a1e1b3d579e333 (4.2.1 taken into use??)
and release tags `https://github.com/fsharp/fsharp/tags` (4.1.18 is the latest)
are not in sync.

As there aren't release notes included in the Nuget package, it is very hard to track what has been changed, and know should I update, e.g. FSharp.Core from 4.1.17 to 4.2.0.

**Comment by cartermp** [comment]
@Thorium apologies for the confusion.  We're getting everything updated.  I've tagged the relevant commit in VisualFSharp and given it release notes: https://github.com/Microsoft/visualfsharp/releases/tag/FSharp.Core-4.2.1

These release notes will also be in the NuGet package.
