### ISSUE TITLE
Intellisence popups should be closed on click outside them.

### ISSUE THREAD

**Issue by hodzanassredin** [fsharp/fsharp#743]
After showing IntelliSense help popup it is possible to click on the next cell and scroll screen and popup will be floating over the page.

#### Repro steps

1. Type some code and press ctrl+space
![default](https://cloud.githubusercontent.com/assets/40375/26789969/baf9f5d0-4a1a-11e7-8605-dfcc2f18fcf6.png)

2. Click on the next cell and scroll page

![default](https://cloud.githubusercontent.com/assets/40375/26789996/d0b43b24-4a1a-11e7-9e77-da28addb5844.png)

#### Expected behavior

IntelliSense popup should be closed when someone is clicking outside of it.

#### Actual behavior

IntelliSense popup is still showing when someone is clicking outside of it.

* Operating system
windows 10
* Editing Tools (e.g. Visual Studio Version)
Firefox

**Comment by dsyme** [comment]
This is an issue for the Visual F# IDE Tools, please submit to http://github.com/Microsoft/visualfsahrp
