### ISSUE TITLE
Error running script on Mono latest, but not Mono 4.8.0

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp#744]
This is a placeholder for a problem I've just seen.

For the ``build.fsx`` in this PR https://github.com/mbraceproject/MBrace.Core/pull/177

On ``Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Thu May 25 09:16:53 UTC 2017)`` we are getting a failure:

```
FsiEvaluationException:
Error: 
	
	error FS0193: Specified method is not supported.
	
Output: [Loading /home/travis/build/mbraceproject/MBrace.Core/packages/build/SourceLink.Fake/tools/SourceLink.fsx
	 Loading /home/travis/build/mbraceproject/MBrace.Core/paket-files/build/fsharp/FAKE/modules/Octokit/Octokit.fsx
	 Loading /home/travis/build/mbraceproject/MBrace.Core/build.fsx]
```

On 4.8.0 we are not getting a failure, see the difference in the CI matrix here:  https://travis-ci.org/mbraceproject/MBrace.Core/builds/240756756?utm_source=github_status&utm_medium=notification

**Comment by dsyme** [comment]
@nosami This may indicate another problem in Mono 5.x (or F# 4.1, though that seems less likely)/  Are all known F# fixes already integrated into Mono 5.1 "latest"?

**Comment by nosami** [comment]
I think FAKE needs updating here. I seem to remember the FCS upgrade fix going into 4.59 or 4.60

**Comment by matthid** [comment]
yes some internal/private  mono api changed to be more like ms one. They do this to unify the code base but break reflection uses in the process (like f# compiler code base)...

**Comment by dsyme** [comment]
OK, trying upgraded FAKE (I thought I'd done that but not yet)

**Comment by dsyme** [comment]
Yes, that worked, thanks. I remember the issue now
