### ISSUE TITLE
FSharpType.IsUnion broken

### ISSUE THREAD

**Issue by Qubitus** [fsharp/fsharp#746]
I have the following code which is broken through upgrading:

F#:
```
type Side = 
  | Left
  | Right
```

C#:
`FSharpType.IsUnion(typeof(Side), FSharpOption<BindingFlags>.None)`

FSharp.Core 4.0.0: returns **true**
FSharp.Core 4.2.1: returns **false**

**Comment by dsyme** [comment]
Closing in favour of https://github.com/Microsoft/visualfsharp/issues/3225
