### ISSUE TITLE
Failure on master

### ISSUE THREAD

**Issue by dsyme** [fsharp/fsharp#773]
There is a CI build failure on Linux/Mono + master

https://travis-ci.org/fsharp/fsharp/builds/265474451?utm_source=github_status&utm_medium=notification

It says ``msbuild`` is not found?

@nosami @directhex Could you take a look?  Has there been a recent change in Mono here?

**Comment by directhex** [comment]
`msbuild` is a separate package. I don't know where the manifest of required packages is specified for Travis.

**Comment by dsyme** [comment]
We can install the package if needed - is it just ``apt-get install msbuild``?

**Comment by directhex** [comment]
Yeah.

IIRC Travis uses whatever's on Docker. @akoeplinger?

**Comment by akoeplinger** [comment]
@directhex no, it installs the normal packages from our Ubuntu repos. msbuild should be available by default since we install mono-devel there.

**Comment by akoeplinger** [comment]
https://github.com/travis-ci/travis-build/blob/2643297a318c9b62aaad4ff07aed60647beaf351/lib/travis/build/script/csharp.rb#L74 if you're curious

**Comment by akoeplinger** [comment]
@directhex uh, hold on I think I see the issue. It's not using the new repo structure yet... My bad.

**Comment by dsyme** [comment]
We install ``mono-devel``, see https://github.com/fsharp/fsharp/blob/master/mono/prepare-mono.sh#L26
