### ISSUE TITLE
non-IL or abstract method with non-zero RVA

### ISSUE THREAD

**Issue by haf** [fsharp/fsharp#774]
I'm having trouble with the F# compiler/mono and I can't get my environment back in a working state, which causes all kinds of trouble, like potentially releasing broken nugets.

Whenever I compile with the F# compiler I get output like this from `xbuild`:

```
elided
	                        Logging.fs
				SQLite.fs
				obj/Debug/.NETFramework,Version=v4.6.1.AssemblyAttribute.fs
				F# Compiler for F# 4.1
				Freely distributed under the Apache 2.0 Open Source License
				non-IL or abstract method with non-zero RVA
x30 of the above line
FSC:  warning FS2003: An System.Reflection.AssemblyInformationalVersionAttribute specified version '0.147.0.a8dd30', but this value is invalid and has been ignored
			Target _CopyAppConfigFile:
etc
```

And then the build finishes.

```
✗ mono --version
Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Wed May 31 14:47:04 BST 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

I would not expect output like this.

#### Related information 

Provide any related information 

* Operating system: macOS 10.12
* Branch: `brew install mono`
* .NET Runtime, CoreCLR or Mono Version 5.0.1.1 – latest from homebrew
* Editing Tools (e.g. Visual Studio Version) – none
* Indications of severity – major for me, but I seem to be pretty alone in experiencing it.

**Comment by 7sharp9** [comment]
Mono 5.0.x is known it be fubar with F#

**Comment by haf** [comment]
None the less, it's latest on homebrew, so it's the default install for people who want to start using F#.

**Comment by 7sharp9** [comment]
Then home brew needs to update.  Broken

**Comment by haf** [comment]
Then so is the default experience of the F# language for programmers world-wide. Hence the bug report.

**Comment by 7sharp9** [comment]
/shrug I never use brew mono, it caused me nothing but issues, I use the Xamarin distribution or manual installation of a tagged fsharp compiler.

**Comment by 7sharp9** [comment]
Using mono 5.2 resolves this as the bug was fixed during 5.0 -> 5.2 mono cycle.

**Comment by baronfel** [comment]
I'm looking at updating the homebrew formula for mono to the latest stable 5.2.0.215, but running into a few issues. in the meantime there's a Caskroom formula for `mono-mdk` that can be installed to use the mono OSX package, which should help.

**Comment by dsyme** [comment]
This has been fixed some time ago.  The issue does _not_  cause any concrete problems - it was simply an inadvertent diagnostic output. See also https://github.com/fsharp/FSharp.Compiler.Service/issues/780

@baronfel Please post new issues for anything F#-specific you find when updating the brew formula

@7sharp9  Please be more specific when answering - e.g. please link to known issues. The use of homebrew is an important scenario as @haf indicates

**Comment by dsyme** [comment]
> In the meantime there's a Caskroom formula for mono-mdk that can be installed to use the mono OSX package, which should help.

@baronfel If you get the chance, could you update the README.md in this repo to indicate that Caskroom is (yet another) know delivery mechanism for F# please? I'd like that to be a fairly up-to-date list of known ways that F# gets delivered to users, so we have links to follow when people report issues. Thanks!

**Comment by nosami** [comment]
Here's a build of Mono containing the fix to remove the `non-IL` message https://dl.xamarin.com/uploads/cx2x4qs22hs/MonoFramework-MDK-5.2.1.5.macos10.xamarin.universal.pkg
