### ISSUE TITLE
Troubleshooting upgrade of mono/fsharp homebrew package

### ISSUE THREAD

**Issue by baronfel** [fsharp/fsharp#776]
I'm attempting to upgrade the mono [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mono.rb) to 5.2 from 5.0 and fsharp 4.1.18 to 4.1.25.

It seems that we now require msbuild instead of just xbuild, and so I'm also having to resource-include msbuild in the same way that the formula previously included fsharp, so I've taken the appropriate tags/build steps from the packaging scripts in the mono repository for the 5.2.0.215 release [here](https://github.com/mono/mono/blob/mono-5.2.0.215/packaging/MacSDK/msbuild.py).

What I'm struggling with is how to then ensure that the newly-build msbuild is put on the PATH correctly so that it's available when the fsharp build occurs.  I've verified using the `--interactive` flag on `brew install` that once the `install-mono-prefix.sh` script runs the binaries end up in the prefix I've specified in the build, but fsharp's configure step still can't find msbuild.

#### Repro steps

Provide the steps required to reproduce the problem

* clone down my fork of homebrew at https://github.com/baronfel/homebrew-core
* switch to the mono5_msbuild branch
* run `brew install --build-from-source mono` to execute my build script.
* verify that mono is compiled correctly
* verify that msbuild is compiled and installed successfully
* verify that fsharp's configure script cannot find msbuild

#### Expected behavior

msbuild is installed in the PATH and detected by `pkg-config`

#### Actual behavior

msbuild is not detected by `pkg-config`, though it seems to be on the PATH

**Comment by dsyme** [comment]
@baronfel Note we also have a problem where msbuild was not being found in the Travis CI for master.  I tried to resolve that in this https://travis-ci.org/fsharp/fsharp/jobs/269567013#L1320 but failed

CI is saying:
```
mono-devel is already the newest version (5.2.0.215-0xamarin10+debian7b1).
mono-devel set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 msbuild : Depends: msbuild-libhostfxr but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
I don't really understand yet

**Comment by manchoz** [comment]
Hi @baronfel,
take a look at https://github.com/manchoz/homebrew-core/blob/manchoz_mono_5.2.0.215_fsharp_4.1.25/Formula/mono.rb.

This formula should fix some building errors related to old dotnet releases needed to build msbuild itself.

**Comment by haf** [comment]
(An aside: this stops http://forge.run/ from working properly, since it requires the package from homebrew /cc @Krzysztof-Cieslak) (Found I had no forge available when trying to contribute a F# sample for gRPC)

**Comment by manchoz** [comment]
@dsyme I think you just need to use mono packages for the same distro as Travis environment.

In upstream [mono/prepare-mono.sh](https://github.com/fsharp/fsharp/blob/master/mono/prepare-mono.sh) you are adding package repository configuration for Debian Wheezy while actual Travis environment is Ubuntu Precise.

I'm currently testing upgrading scripts and configurations to Trusty-based Travis, please take a look at https://github.com/fsharp/fsharp/compare/master...manchoz:master and https://travis-ci.org/manchoz/fsharp.

**Comment by dsyme** [comment]
@manchoz Super, please send a PR

**Comment by dsyme** [comment]
@baronfel Any progress on updating the homebrew? Thanks

**Comment by baronfel** [comment]
There are two PRs out to homebrew that are more fully-featured and correct than my WIP one, 

- https://github.com/Homebrew/homebrew-core/pull/17435
- https://github.com/Homebrew/homebrew-core/pull/17378

both seem to work, I'll ping the owners again to see if we can get down to a single one and get it merged into homebrew.

**Comment by manchoz** [comment]
Hi,
author of https://github.com/Homebrew/homebrew-core/pull/17435, here... hoping one of them would be merged as soon as possible!

**Comment by dsyme** [comment]
@manchoz Both are still open - anything we can do to help get them in?

**Comment by manchoz** [comment]
@dsyme let me ping @ilovezfs to check the status. Latest checks were failing but that was related to some CI environment setting or issue... I will keep you updated.

**Comment by ilovezfs** [comment]
@manchoz the overcomplicated msbuild resource block is still a bit of a blocker.

**Comment by manchoz** [comment]
@dsyme, yes, it's pretty ugly.
Building msbuild from (mono's repository) sources currently requires an old `dotnet` version (downloaded by `init-tools.sh`) that relies both on old `libssl` and `libcurl` versions.

I'm struggling to build it on Arch Linux, too, because not every GNU/Linux distro is supported by current `mono/msbuild` build system and not every GNU/Linux has support for older libraries. In Arch Linux, currently, the only working package relies on pre-built Ubuntu packages (simply extracting and installing the filesystem tree as-is from data .tar in .deb file). (TODO: Should investigate if we can adopt same approach on MacOS too).

We could get a little less ugly `brew` formula separating `mono`, `msbuild` (with a proper patch attacch) and `fsharp` formulas, but that would bring to a different UX from official Mono for Mac package which ships with built-in msbuild and fsharp.
