### ISSUE TITLE
Drop support for .mdb files in Mono

### ISSUE THREAD

**Issue by nosami** [fsharp/fsharp#778]
Debugging F# applications in Visual Studio for Mac works better now with `portable pdb` files than it does with `.mdb` files (even for purely Mono apps, not just dotnet core). 

The mono runtime and mono debugger supports ppdb really well. All that is needed currently is a targets file tweak.

Development on .mdb has ceased completely now and C# switched over to using portable pdb files only a few months back.

I propose that I patch the Mono MSBuild targets to switch `<DebugType>full</DebugType>` over to `<DebugType>portable</DebugType>` now (this is what C# on Mono currently does as Roslyn has no awareness of `.mdb` files)

Maybe we should remove `.mdb` support from the F# compiler completely at some point in the future?

**Comment by dsyme** [comment]
@nosami So the Mono C# compiler took a breaking change where MDB files are no longer produced?

Yes, if so then we can do the same thing, and people just have to take the pain I suppose, or use a previous version of F#

Please submit a PR?

**Comment by dsyme** [comment]
@nosami PR can go to here (for full CI testing) or to Microsoft/visualfsharp (for root integration in to targets etc.)

**Comment by nosami** [comment]
The Mono C# compiler hasn't been used for some time now, it's all Roslyn.

I'll create a PR. I just want to spend a bit of time dogfooding first :)

**Comment by dsyme** [comment]
@nosami OK, thanks

What I mean is that after this change, a build that expects a "mdb" file to be produced (e.g. for a nuget package) will fail, right?  

Anyway, I'll wait for the PR(s) and we can discuss

**Comment by nosami** [comment]
> What I mean is that after this change, a build that expects a "mdb" file to be produced (e.g. for a nuget package) will fail, right?

Yes, that would fail. Not sure how common that is though, I only ever see Windows old-style pdb files.

Mono will use whatever it finds in the output folder, either ppdb or mdb.

**Comment by dsyme** [comment]
OK.  You can also put the portable debug information in the DLL itself, right?

**Comment by nosami** [comment]
I believe that works ok, but haven't tried it.

**Comment by nosami** [comment]
Portable pdb debugging will likely be the default in Mono 5.4 but there will be a switch to change it back to .mdb if for some reason it doesn't work. Will wait and see what the reaction is like.
