### ISSUE TITLE
mapFoldBack incomming list is not last parameter

### ISSUE THREAD

**Issue by vslynko** [fsharp/fsharp#780]
In contrast to many other list, seq, array iteration functions, that always have the incoming collection as last parameter, allowing to pipe, List.mapFoldBack has acc as last parameter.

```
        let mapFold<'T,'State,'Result> (f:'State -> 'T -> 'Result * 'State) acc list =

        let mapFoldBack<'T,'State,'Result> (f:'T -> 'State -> 'Result * 'State) list acc =
```
I'd suggest to change mapFoldBack to 
```
        let mapFoldBack<'T,'State,'Result> (f:'T -> 'State -> 'Result * 'State) acc list =
```

That would be a breaking change.

**Comment by dsyme** [comment]
@vslynko Yes, this can't be changed. And it's the same as foldBack for example
