### ISSUE TITLE
Cannot build xunit template in F#, in .NET Core 

### ISSUE THREAD

**Issue by luminescent** [fsharp/fsharp#781]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. dotnet new xunit -lang F# 

2. dotnet build 

#### Expected behavior

I expect the project to build and it used to until a couple of hours ago. 

#### Actual behavior

It now stopped building with the error below, suddenly. It used to work couple of hours ago and I haven't done any updates. 

```
c:\work\src\testNetCore>dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\2.0.0\FSharp\Microsoft.FSharp.Targets(224,9): error MSB4062: The "Fsc" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\2.0.0\FSharp\FSharp.Build.dll. Could not load file or assembly 'C:\Program Files\dotnet\sdk\2.0.0\FSharp\FSharp.Build.dll'. Format of the executable (.exe) or library (.dll) is invalid. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [c:\work\src\testNetCore\testNetCore.fsproj]

Build FAILED.

C:\Program Files\dotnet\sdk\2.0.0\FSharp\Microsoft.FSharp.Targets(224,9): error MSB4062: The "Fsc" task could not be loaded from the assembly C:\Program Files\dotnet\sdk\2.0.0\FSharp\FSharp.Build.dll. Could not load file or assembly 'C:\Program Files\dotnet\sdk\2.0.0\FSharp\FSharp.Build.dll'. Format of the executable (.exe) or library (.dll) is invalid. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [c:\work\src\testNetCore\testNetCore.fsproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.52
```

#### Known workarounds

I rerun the installer for .NET Core 2.0 and choose Repair. This fixed it.

#### Related information 

* Operating system: Windows 10 Professional
* Branch: not sure? Installed from installer.
* .NET Runtime, CoreCLR or Mono Version: `dotnet --version` returns `2.0.0` . `fsc` has version `4.1`.
* Editing Tools (e.g. Visual Studio Version): Visual Studio Code latest version, but haven't actually used it on this new template
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions: n/a?
* Links to performance testing scripts n/a
* Indications of severity: I'd say critical. Out of the box templates should compile.

Also apologies if I submitted this to the wrong project, maybe it should be the https://github.com/dotnet/corefx ?

**Comment by dsyme** [comment]
Per CONTRIBUTING.md please reopen at http://github.com/Microsoft/visualfsharp

**Comment by luminescent** [comment]
Thank you, opened https://github.com/Microsoft/visualfsharp/issues/3567

**Comment by dsyme** [comment]
Thanks!
