### ISSUE TITLE
F# compiler option --nowarn does not accept alphanumeric warning codes

### ISSUE THREAD

**Issue by mishra14** [fsharp/fsharp#785]
Stemming from: https://github.com/NuGet/Home/issues/5913

It seems that F# compiler option [--nowarn](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-options) only accepts integers. Which seems fine based on the description on the docs page. 

But the docs also state that the option is equivalent to C# compiler option [/nowarn](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/nowarn-compiler-option). But the C# compiler option accepts alpha-numeric codes like /nowarn:CS0219

```
F:\validation\test\addpkg>csc Program.cs /nowarn:NU1603;CS0219
Microsoft (R) Visual C# Compiler version 2.4.0.62025 (a0507c1e)
Copyright (C) Microsoft Corporation. All rights reserved.


F:\validation\test\addpkg>
```

IMO, either the two should be equivalent or maybe the docs should not state them as equivalent.

Please let me know, if this is not the right place for it or it needs to be in [fslang-suggestions](https://github.com/fsharp/fslang-suggestions).

**Comment by forki** [comment]
I tink it should be posted in https://github.com/Microsoft/visualfsharp
/cc @cartermp

**Comment by cartermp** [comment]
Yep, @mishra14 can you repost this on visualfsharp?  Thanks!

**Comment by mishra14** [comment]
This issue was moved to Microsoft/visualfsharp#3626
