### ISSUE TITLE
Cannot build "dotnet  new" templates using Mono MSBuild

### ISSUE THREAD

**Issue by auduchinok** [fsharp/fsharp#788]
It looks like Mono didn't get targets needed for the new fsproj/SDK projects support.
I'm using Mono 5.2 and dotnet SDK 2.0 on macOS 10.13.
When creating a template for C# classlib, it can be built using msbuild, but it doesn't work for F# templates. On Windows it can be built when VS2017.3 with F# tools is installed.
A simple repro solution: [MSBuildCoreProjects.zip](https://github.com/fsharp/fsharp/files/1337397/MSBuildCoreProjects.zip).

I need to target `net451` in projects I currently work on and when I try using `dotnet build` I get error about missing reference assemblies for `net451`.
Using `netstandard2.0` with `dotnet build` is an almost-working workaround except there're a few places where some types from `WindowsBase` and other .NET Framework assemblies aren't resolved.

**Comment by dsyme** [comment]
cc @nosami - do you know what's going on here?

**Comment by dsyme** [comment]
@auduchinok May have been fixed by https://github.com/fsharp/fsharp/pull/783

**Comment by auduchinok** [comment]
@dsyme Thanks, the problem is indeed fixed there. Is it known whether the fix may be included in the upcoming Mono 5.4 release?
The `dotnet build` case for `net451` is discussed in https://github.com/dotnet/sdk/issues/335.

**Comment by nosami** [comment]
This fix is rolled into Mono 5.4.0.199 and later

**Comment by auduchinok** [comment]
@nosami, great! Can confirm it works.
I've tested it on 5.4.0.135 before.

**Comment by nosami** [comment]
Oh... and Mono 5.6.0.76 and above :)
