### ISSUE TITLE
Working with list of list of triple bytes + BMP/PNG on Linux (Ubuntu) + Emacs + Fsharpi (Any CPU)

### ISSUE THREAD

**Issue by gentauro** [fsharp/fsharp#798]
**Please provide a succinct description of the issue.**

I have this non-deterministic behaviour when I try to convert pixels from an image to a list of list of triple bytes (R,G,B) on my Linux box in combination with Emacs + Fsharpi and Mono

#### Repro steps

Download the following [PNG file](https://upload.wikimedia.org/wikipedia/en/thumb/0/00/Razer_Snake_Logo.svg/1013px-Razer_Snake_Logo.svg.png) and use the code from the following [GIST](https://gist.github.com/gentauro/a5df0f93cf3a706d1490e9c618fb57f7)

1. Evaluate code in Emacs by marking it (CTRL+SPC) and (CTRL+C CTRL+R). You will see some non-deterministic errors (related to memory of Object references, see GIST for more info)

#### Expected behavior

I would expect to create a list of list of triple bytes (R,G,B)

#### Actual behavior

As mentioned before, it provides some non-deterministic errors

#### Known workarounds

In order to make this work I store all pixels in a single list and then store the width and height of the picture.

#### Related information 

**Provide any related information** 

* Operating system: Ubuntu 17.10
* Branch: Microsoft (R) F# Interactive version 4.1 | /usr/lib/mono/fsharp/fsiAnyCpu.exe
* .NET Runtime, CoreCLR or Mono Version: Mono JIT compiler version 5.4.0.201
* Editing Tools (e.g. Visual Studio Version): GNU Emacs 25.2.2
* Indications of severity: I guess low-priority as everything related to Linux right?

**Comment by dsyme** [comment]
There must be a repro for this without using Emacs?

**Comment by gentauro** [comment]
I can't recreate it from the terminal by just executing `./SpiseMisu.Minecraft.Picture.fsx`

That seems to work.

**Comment by dsyme** [comment]
I'm going to close this since I think we need a repro based on the command line tools, not FSI in emacs.  Strange problem though
