### ISSUE TITLE
Anonymous interface implementation accessibility when tuple deconstruction is used.

### ISSUE THREAD

**Issue by FrankBro** [fsharp/fsharp#802]
Anonymous interface implementation accessibility when tuple deconstruction is used

#### Repro steps

```fsharp
module private PM = 
    type PT = 
        abstract A : int
    let a = { new PT with member __.A = 1 } // ok
    let b, c = // PT is less accessible than PT * PT
        { new PT with member __.A = 1 }
        , { new PT with member __.A = 1 }
```

```
/home/runner/main.fs(5,9): error FS0410: The type 'PT' is less accessible than the value, member or type 'val patternInput : PM.PT * PM.PT' it is used in

/home/runner/main.fs(5,9): error FS0410: The type 'PT' is less accessible than the value, member or type 'val patternInput : PM.PT * PM.PT' it is used in
```

#### Expected behavior

Should work just like `a` does.

#### Actual behavior

Compile error

#### Known workarounds

Construct the tuple after implementing the anonymous interfaces

#### Related information 

Repro'd here: https://repl.it/repls/FavorableDarkturquoiseGordonsetter

**Comment by enricosada** [comment]
hi @FrankBro, this repo is for cross platform packaging of fsharp ( see http://fsharp.github.io/2014/06/18/fsharp-contributions.html for a guide).

i moved your issue to https://github.com/Microsoft/visualfsharp/issues/4161

more info in the [README](https://github.com/fsharp/fsharp/blob/master/README.md)
