### ISSUE TITLE
fpchat invite link broken on resources page

### ISSUE THREAD

**Issue by sjwarner-bp** [fsharp/fsharp#803]
[exercism.io/languages/fsharp/resources](http://www.exercism.io/languages/fsharp/resources) talks about the functional programming chat on slack:

> The [F# channel](https://functionalprogramming.slack.com/messages/fsharp/) of the [functionalprogramming slack account](https://functionalprogramming.slack.com/). To join, go to [fpchat.com](http://fpchat.com/).

But the link in [fpchat.com](http://fpchat.com) results in a timeout.

I assume that the link should be corrected to [this](https://fpchat-invite.herokuapp.com/)?

**Comment by ReedCopsey** [comment]
Reported there: https://github.com/exercism/docs/issues/111

**Comment by enricosada** [comment]
Closing, linked issue is fixed and website already updated
