### ISSUE TITLE
FSharp.Compiler.Tools nuget not working with new project structure

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsharp/fsharp#807]
It seems like adding the FSharp.Compiler.Tools package to an F# project using the new structure causes that project to fail to load in Visual Studio (version 15.5.3).

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a netstandard2.0 F# library.
2. Add the latest FSharp.Compiler.Tools (version 4.1.29) via the nuget UI.

#### Expected behavior

Should add the nuget package without incident.

#### Actual behavior

Project will fail to load with the following error:
```
Repro.fsproj : error  : Project file is incomplete. Expected imports are missing.
```

#### Known workarounds

None

#### Related information 

Visual Studio 15.5.3 running on Windows.

NB this issue also occurs if using any `net4x` target framework.

**Comment by eiriktsarpalis** [comment]
This issue in conjunction with https://github.com/Microsoft/visualfsharp/pull/3729 is blocking the porting of FsPickler to netstandard. Currently the project depends on an older version of FSharp.Compiler.Tools that does not have the regression.

**Comment by dsyme** [comment]
@eiriktsarpalis We should find out what's causing it, but why is this blocking? You don't have to add the package using the UI do you?   And what does Repro.fsproj contain after it's been butchered?

**Comment by eiriktsarpalis** [comment]
Nothing really, here's what it looks like:
```xml
﻿<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Compiler.Tools" Version="4.1.29" />
  </ItemGroup>
</Project>
```
> You don't have to add the package using the UI do you? 
Same issue appears in paket

**Comment by eiriktsarpalis** [comment]
@dsyme as a temporary workaround I added this https://github.com/mbraceproject/FsPickler/pull/100/commits/f875fb30be20b6465db40f7f1fcf9aa15cf1d8d2#diff-13f25f5240116cff5e674543eaa0057fR351

**Comment by dsyme** [comment]
@eiriktsarpalis That looks like a temporary workaround to the tuple problem not this issue?

**Comment by eiriktsarpalis** [comment]
Correct

**Comment by enricosada** [comment]
using

```xml
    <PackageReference Include="FSharp.Compiler.Tools" Version="4.1.29" />
```

import also the target files, but these works for old sdk, not new one.
so it doesnt work for new .net core sdk based fsproj.

a workaround is just set `FscToolPath`/`FscToollExe` properties

**Comment by dsyme** [comment]
@enricosada Is there something we can do to fix this?

**Comment by enricosada** [comment]
ihmo we shouldnt import that target file and task with new sdk. we cannot be sure it's backward compatibile, because tied a bit to the rest of sdk. older sdk changed slowly, so want not an issue.

With new sdk i think is better to just override the `FscToolPath`/`FscToolExe`, because fsc args are more backward compatibile i think

Maybe make the include conditional, just for old sdk, but need to check a valid condition.

using just `msbuild` vs `dontet msbuild` (the msbuild host property) as condition is not enough, because new sdk fsproj can be built by `msbuild` too (both .net and mono).

I'll try find a way and send a PR next week

**Comment by dsyme** [comment]
This doesn't seem to be an active problem, will close
