### ISSUE TITLE
Building with Output type "Exe" puts AutoMagically Generated files after the existing files list.   Building with Output type "Library" puts them before

### ISSUE THREAD

**Issue by dsplaisted** [fsharp/fsharp#813]
_From @KevinRansom on June 17, 2017 23:9_

When Building an F# library the sdk adds automagically generated files before the specified source files when building as Exe.  And after when building as "Library.

Note the order of Program.fs and .NETCoreApp,Version=v2.0.AssemblyAttributes.fs.

OutputType  = Library
````
         --target:library
         --warn:3
         --warnaserror:76
         --fullpaths
         --flaterrors
         --highentropyva-
         --targetprofile:netcore
         --simpleresolution
         --nocopyfsharpcore
         Program.fs
         C:\Users\kevinr.REDMOND\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.fs
````

OutputType  = Exe
````
         --target:exe
         --warn:3
         --warnaserror:76
         --fullpaths
         --flaterrors
         --highentropyva-
         --targetprofile:netcore
         --simpleresolution
         --nocopyfsharpcore
         C:\Users\kevinr.REDMOND\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.fs
         Program.fs
````

_Copied from original issue: dotnet/sdk#1355_

**Comment by dsplaisted** [comment]
That is weird, but does it have any affect?

Sent from my Windows 10 phone

From: Kevin Ransom (msft)
Sent: Sunday, June 18, 2017 12:09 AM
To: dotnet/sdk
Cc: Subscribed
Subject: [dotnet/sdk] Building with Output type "Exe" puts AutoMagicallyGenerated files before the existing files list. Building with Output type"Library" puts them after (#1355)

When Building an F# library the sdk adds automagically generated files before the specified source files when building as Exe. And after when building as "Library.
Note the order of Program.fs and .NETCoreApp,Version=v2.0.AssemblyAttributes.fs.
OutputType = Library
         --target:library
         --warn:3
         --warnaserror:76
         --fullpaths
         --flaterrors
         --highentropyva-
         --targetprofile:netcore
         --simpleresolution
         --nocopyfsharpcore
         Program.fs
         C:\Users\kevinr.REDMOND\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.fs
OutputType = Exe
         --target:exe
         --warn:3
         --warnaserror:76
         --fullpaths
         --flaterrors
         --highentropyva-
         --targetprofile:netcore
         --simpleresolution
         --nocopyfsharpcore
         C:\Users\kevinr.REDMOND\AppData\Local\Temp\.NETCoreApp,Version=v2.0.AssemblyAttributes.fs
         Program.fs

**Comment by dsplaisted** [comment]
_From @livarcocc on January 24, 2018 18:24_

@dsplaisted is this us or is this globbing in MSBuild?

**Comment by dsplaisted** [comment]
It turns out that this is the FSharp targets: https://github.com/fsharp/fsharp/blob/fb2f8aa2a7c01d00f703d1ab050bbf3a852f02a9/src/fsharp/FSharp.Build/Microsoft.FSharp.Targets#L395-L396

```xml
<ItemGroup>
    <CompileBefore Include="$(TargetFrameworkMonikerAssemblyAttributesPath)" Condition="'$(AdditionalSourcesText)' != '' AND ('$(OutputType)' == 'Exe' OR '$(OutputType)' == 'WinExe')"/>
    <CompileAfter Include="$(TargetFrameworkMonikerAssemblyAttributesPath)" Condition="'$(AdditionalSourcesText)' != '' AND '$(OutputType)' != 'Exe' AND '$(OutputType)' != 'WinExe'"/>
</ItemGroup>
```

@KevinRansom

**Comment by dsplaisted** [comment]
I'm not sure if this is actually a bug or not, because presumably the targets were written like that intentionally.

**Comment by KevinRansom** [comment]
We got things working the way we need them to work months ago, but thanks for looking at this.
