### ISSUE TITLE
Structural comparison for user-defined struct seems to fail on Mono 64 bit

### ISSUE THREAD

**Issue by anticrisis** [fsharp/fsharp#823]
Using a `[<Struct>]` record type with various collection functions seems to produce incorrect results when equality and comparison are needed. This example shows `List.distinct` failing, but I've run into problems with Set, Map and others in this same environment.

I originally experienced this running an FSharp DLL on Unity3D on Windows, but was able to eliminate Unity from the steps required to reproduce the problem.

#### Repro steps

Provide the steps required to reproduce the problem

1. Install Mono for Windows 64 bit from [here](http://www.mono-project.com/download/stable/)

2. Build this project with Visual Studio 2017 Community: [github repo](https://github.com/anticrisis/fsharp-struct-mono-64). The test code is in `Program.fs` and simplified here:

```
[<Struct>] type V3 = { a: int; b: int; c: int; } 
let v1 = { a=1; b=2; c=3 }
let v2 = { a=4; b=5; c=6 }
let v3 = { a=1; b=2; c=3 }
let vs = [ v1; v2; v3 ]
printfn "vs = %A\n" vs

// mono 64-bit: returns a list of three items, including the duplicate
printfn "distinct vs = %A" (List.distinct vs)

// mono 64-bit: returns 3 
printfn "length of distinct vs = %i" (List.distinct vs |> List.length)
```

#### Expected behavior

The output of `List.distinct` should be a list with `2` elements.

#### Actual behavior

The actual output of `List.distinct` is a list with `3` elements. 

#### Known workarounds

In other testing, I've seen that implementing `[<CustomEquality; CustomComparison>]` and providing `Equals`, `GetHashCode` and `CompareTo` avoids this problem.

Running the test code from a Windows console works fine, avoiding the Mono runtime.

#### Output of test
```
C:\Program Files\Mono>mono --version
Mono JIT compiler version 5.8.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

C:\Program Files\Mono>mono c:\users\anticrisis\source\repos\fsharp-struct-mono-64\fsharp-struct-mono-64\bin\Debug\fsharp_struct_mono_64.exe
[||]
System.IntPtr.Size = 8
vs = [{a = 1;
  b = 2;
  c = 3;}; {a = 4;
            b = 5;
            c = 6;}; {a = 1;
                      b = 2;
                      c = 3;}]

distinct vs = [{a = 1;
  b = 2;
  c = 3;}; {a = 4;
            b = 5;
            c = 6;}; {a = 1;
                      b = 2;
                      c = 3;}]
length of distinct vs = 3
```

#### Related information 

Because of this behavior, I have to provide Equals, GetHashCode and CompareTo implementations for every struct type I define for a Unity game I am working on. This is a valid workaround, however I lost many hours trying to understand why simple collection functions seemed to be misbehaving, and this also makes me concerned that either I am using FSharp language features incorrectly, or there are other silent bugs at very basic levels of the language.

Provide any related information 

* Windows 10 Pro

**Comment by dsyme** [comment]
OK, it's a mono bug - could you open a bug on http://github.com/mono/mono or Xamarin bugzilla please?

Thanks

**Comment by anticrisis** [comment]
Thank you, I've filed this issue at mono: https://github.com/mono/mono/issues/7177

**Comment by dsyme** [comment]
External problem resolved
