### ISSUE TITLE
Unexpected SRTP breaks 

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/fsharp#824]
SRTPs tend to break sometimes at totally unexpected places with very weird compiler error.

#### Repro steps

I had some code like this not long ago:

```
x
|>> doSomething a b
|> doSomethingElse c d
>>= againSomethingDifferent
>>= SomeOtherCall d
|>> preFinalCall e f
|>> finalCall g
```

which broke with some strange error
Only when I split up that piping into

```
let y =
  x
  |>> doSomething a b
  |> doSomethingElse c d
  >>= againSomethingDifferent

y
>>= SomeOtherCall d
|>> preFinalCall e f
|>> finalCall g
```

2 sub expressions it compiled.

#### Expected behavior

Compiles fine

#### Actual behavior

Provide a description of the actual behaviour observed. 

#### Related information 

Provide any related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Editing Tools (e.g. Visual Studio Version)
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
* Links to performance testing scripts
* Indications of severity

**Comment by dsyme** [comment]
@ShalokShalom we need exact repro steps for this please.  Also please submit to http://github.com/Microsoft/visualfsharp

**Comment by dsyme** [comment]
Closing per comment above - please resubmit to http://github.com/Microsoft/visualfsharp with exact repro steps

**Comment by ShalokShalom** [comment]
This is copied by someone in the Slack channel
I linked this person to this issue here and asked for exakt details
Not arrived until

**Comment by dsyme** [comment]
@ShalokShalom OK, thanks, looking forward to the details

**Comment by ShalokShalom** [comment]
>This seems to be a function of the overall code size. Now I cant open our code >base to be used as it is not OSS.
>And I simply have no time atm to try to extract it (assuming that the error does not >disappear when I try) into a shareable code package.
>Sorry for that.
>PS: the only thing that I can say is that when using SRTPs quite a bit and with >increasing code size the compiler starts to act pretty strange

Gusty says, he already experienced this 'hundrets of times' and its currently tricky to reproduce.

Rob also said, its the weirdest issue he ever experienced in F-Sharp yet.

Thanks
