### ISSUE TITLE
Equivalent of python's __name__ == '__main__' in FSI

### ISSUE THREAD

**Issue by onionhammer** [fsharp/fsharp#825]
It would be lovely if this was a thing. I often times want to re-use utility scripts in other scripts, but dont necessarily want the default action to run

**Comment by voronoipotato** [comment]
what is __name__ == '__main__'

**Comment by onionhammer** [comment]
@voronoipotato as the description implies, it's a condition that let's scripts run certain code only if they're the main script being invoked, but not run if the script is just being included in another script

**Comment by voronoipotato** [comment]
Does that even happen?

**Comment by onionhammer** [comment]
I think you misunderstand,

Im not proposing any syntax, just referencing Python's syntax. The syntax of the check is not as important as the concept. '__main__' is just the name python makes whatever module is being run

**Comment by voronoipotato** [comment]
You can import a script in F# without running main by using load. ```#load "Program.fs"``` I'm able to reuse utility scripts in other scripts without the default action being run. Let me know if you run into any problems but I think you'll be pleasantly surprised with this.

**Comment by matthid** [comment]
I think the main problem here is that it is a bit non-obvious how and when exactly initialization code is run as there are quite a lot of subtle differences depending on how the script is executed/loaded...

**Comment by voronoipotato** [comment]
when you ```#load ``` main doesn't get run at all. I'll be honest i've been using F# for like maybe a year? I'm not exactly a seasoned user. If anything it speaks to a lack of documentation around script execution/loading, or at least if it does exist I've never seen it.

**Comment by voronoipotato** [comment]
The best I could find in short notice is this blog post from 2009. https://blogs.msdn.microsoft.com/chrsmith/2008/09/12/scripting-in-f/

**Comment by matthid** [comment]
I think the best documentation is this github thread: https://github.com/Microsoft/visualfsharp/issues/1392#issuecomment-237859375

**Comment by onionhammer** [comment]
@voronoipotato Please don't confuse the sample python I used - to convey an idea - with the actual concept I'm trying to describe.

Forget everything said up until this moment about "main" etc. I'm **not** talking about `int  main(string[] args)` as in the standard entry point for programs.

I'm talking about composing F# *scripts*.

For example:

MyDevices.fsx
```F#
let LoadTestDevices () =
    ()

if **ThisIsTheScriptBeingRun()** then
    LoadTestDevices().DoWork()
```

SomeOtherTest.fsx
```F#
#load "MyDevices.fsx"

if **ThisIsTheScriptBeingRun()** then
    MyDevices.LoadTestDevices().DoSomeOtherTestWork()
```

Where `ThisIsTheScriptBeingRun()` is a placeholder which returns **true** IIF FSI is run with *that* script as the entry point.

**Comment by BillHally** [comment]
You should be able to do this by comparing the value of the arguments with which `fsi` was invoked with the name of the current script i.e. the value of `fsi.CommandLineArgs = [| __SOURCE_FILE__ |])` will be `true` if invoked directly, and `false` otherwise.

**Comment by voronoipotato** [comment]
Sorry for the confusion @onionhammer. It didn't help that the last time I wrote any python was college. Not trying to be a source of frustration, but if you wrap your mydevices.fsx with a module, add a main with an entrypoint when you load you won't have any code run, and when you run it in the fsi it will go through main. I'll admit that BillHally's solution will also work. We should create a wiki.

**Comment by onionhammer** [comment]
Moved to F# suggestions
