### ISSUE TITLE
How can I contribute a Sawtooth Function?

### ISSUE THREAD

**Issue by nathvi** [fsharp/fsharp#828]
I have a Sawtooth function written in F# and was wondering if it would be good to add it to the core? If not where would it go?

**Comment by baronfel** [comment]
Generally the process is to first write a suggestion for the enhancement over at https://github.com/fsharp/fslang-suggestions. Then there will usually be some discussion on your issue. If it gets marked as 'approved', then you'll generally be asked to write a short RFC to track the changes in https://github.com/fsharp/fslang-design before implementing the work in https://github.com/Microsoft/visualfsharp

**Comment by voronoipotato** [comment]
It could simply be a library with other waveform functions. https://github.com/fsprojects/awesome-fsharp is a good list of libraries that are available to all but aren't a part of Core.

**Comment by dsyme** [comment]
@nathvi Yes, I agree that this should first go in a non-core library, the above list is a great place to start

I'll close this for now

thanks
