### ISSUE TITLE
Build Fails on Mono

### ISSUE THREAD

**Issue by xenocons** [fsharp/fsharp#829]
It appears that build (using `make`) fails on mono:

Mono JIT compiler version 5.10.0.160.

The first issue is due to `src/fsharp/FSharp.Core/list.fs`:413, it appears inference cannot determine the correct type for the HashSet, (perhaps this API was changed recently in framework).

The below allows `make` to succeed on my system. 
```
diff --git a/src/fsharp/FSharp.Core/list.fs b/src/fsharp/FSharp.Core/list.fs
index 45eccc3f3..a080eef23 100755
--- a/src/fsharp/FSharp.Core/list.fs
+++ b/src/fsharp/FSharp.Core/list.fs
@@ -410,7 +410,7 @@ namespace Microsoft.FSharp.Collections
         let filter predicate list = Microsoft.FSharp.Primitives.Basics.List.filter predicate list
 
         [<CompiledName("Except")>]
-        let except itemsToExclude list =
+        let except (itemsToExclude:IEnumerable<'a>) list =
             match box itemsToExclude with
             | null -> nullArg "itemsToExclude"
             | _ -> ()
```

**Comment by dsyme** [comment]
cc @nosami 
Thanks for this, I'll apply the change in Microsoft/visualfsharp

**Comment by dsyme** [comment]
Actually I updated here, will make sure the patch is also applied to Mono 5.10
