### ISSUE TITLE
[Build Ergonomics] Debug Build Option

### ISSUE THREAD

**Issue by xenocons** [fsharp/fsharp#830]
In the documentation, it specifies that it is possible to build a debug build of this repo using `make CONFIG=debug`, however, on line 1 of the Makefile, it includes mono/config.make, which seems to hardcode the Configuration to Release (lines 25). Changing this line to `Configuration = Debug` allows a debug build to occur.

**Comment by dsyme** [comment]
@xenocons Did you try

    make Configuration=Debug

My understanding from my rusty `make` knowledge is that should work, I've adjusted the docs to that but haven't yet double checked.

**Comment by xenocons** [comment]
Confirmed that this does work, thank you for updating the doco :+1:
