### ISSUE TITLE
"Unexpected symbol reader error" in a simple F# console application

### ISSUE THREAD

**Issue by parthopdas** [fsharp/fsharp#831]
"Unexpected symbol reader error" message on an unbound breakpoint in a simple F# console application.

#### Repro steps
1. VS 15.6.4, F#, "Microsoft Visual F# Tools 10.1 for F# 4.1", .NET Fx 4.6.1 console application, FSharp.Core 4.4.3.0
2. Create a new console application with the above configuration/toolset
3. Add the following line before the main function
> let func = sprintf "%d"
4. Set a break point on first line of main
5. F10

#### Expected behavior

Program execution to break at first line of main, the breakpoint should be bound.

#### Actual behavior

Disassembly window shows up, hovering on the breakpoint says "The breakpoint will not currently be hit. Unexpected symbol reader error"

#### Known workarounds

If you instead change func to non-point-free style, the expected behavior occurs. viz.
> let func n = sprintf "%d" n

As you will agree, I am sure, this is not really an acceptable workaround, but noting it here in case it provides a hit regarding where the problem could be.

#### Related information 

VS 15.6.4, F#, "Microsoft Visual F# Tools 10.1 for F# 4.1", .NET Fx 4.6.1 console application, FSharp.Core 4.4.3.0

**Comment by dsyme** [comment]
@parthopdas Could you please reopen in https://github.com/Microsoft/visualfsharp, thanks

**Comment by dsyme** [comment]
cc @cartermp @KevinRansom

**Comment by KevinRansom** [comment]
@parthopdas another work around is to use portable pdbs.

Set the debugtype to portable as follows:
````
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <Tailcalls>false</Tailcalls>
````
![image](https://user-images.githubusercontent.com/5175830/38000689-a5ad6684-31dd-11e8-8b6e-ec0e2ae5cebb.png)

**Comment by parthopdas** [comment]
@dsyme Done: Microsoft/visualfsharp#4643

@KevinRansom That's a reasonable workaround for me.

**Comment by KevinRansom** [comment]
@parthopdas it's still a bug, so I would like to keep this open for a while.


Thanks

**Comment by KevinRansom** [comment]
Oh this is fsharp/fsharp all of these repos still confuse me.  we shall keep the visualfsharp one open to track the issue.

Thanks
