### ISSUE TITLE
Build error in RHEL7

### ISSUE THREAD

**Issue by psurentax** [fsharp/fsharp#835]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A
Down load fsharp from git into RHEL7, then unzip the folder and then run make command.

Saying msbuild command not found. but there is no configure script and autogen script in code

from asnc1scc repo mentioned steps for compiling fsharp

git clone https://github.com/fsharp/fsharp && \
    cd fsharp && \
    ./configure && \
    make && sudo make install 

Same is not executed because, no configure script in source code.

2. Step B

dependencies output
Mono JIT compiler version 5.10.1.20 (tarball Thu Mar 29 14:44:43 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

I am trying in RHEL7

Linux hometest 3.10.0-693.21.1.el7.x86_64 #1 SMP Fri Feb 23 18:54:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dsyme** [comment]
Please remove the use of "./configure". That script has been removed.
