### ISSUE TITLE
Compilation not working on linux

### ISSUE THREAD

**Issue by Chais** [fsharp/fsharp#836]
Compilation of 10.0.1 as well as 4.1.34 fails on Linux with mono 5.10

```
$ mono --version
Mono JIT compiler version 5.10.0 (makepkg/dac60775616 Thu Mar 22 02:05:14 CET 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

##### 4.1.34
1. `$ ./autogen.sh --prefix="/usr"`
2. `$ make`
##### 10.0.1
1. `$ make prefix="/usr"`

#### Expected behavior

Should successfully compile the respective version.

#### Actual behavior

```
Build FAILED.

"/build/fsharp/src/fsharp/src/fsharp/Fsc-proto/Fsc-proto.fsproj" (default target) (1) ->
"/build/fsharp/src/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj" (default target) (2) ->
(CreateManifestResourceNames target) ->
  /build/fsharp/src/fsharp/packages/FSharp.Compiler.Tools.4.1.27/tools/Microsoft.FSharp.Targets(135,13): error MSB4131: The "ResourceFilesWithManifestResourceNames" parameter is not supported by the "CreateFSharpManifestResourceName" task. Verify the parameter exists on the task, and it is a gettable public instance property. [/build/fsharp/src/fsharp/src/fsharp/FSharp.Core/FSharp.Core.fsproj]
```

#### Related information 
* Arch Linux 4.15.13
* Tag 4.1.34/10.0.1
* mono 5.10

**Comment by dsyme** [comment]
@Chais I submitted https://github.com/fsharp/fsharp/pull/837 to try to work out what's going on.  CI is green for latest Mono, so there may have been a glitch along the way.

Possibly we might also need to update the FSharp.Compiler.Tools but I'm not specifically sure why

**Comment by Chais** [comment]
It may well be an issue with how stuff is packaged on Arch. The `dotnet-sdk` package for example doesn't contain an MSBuild executable, only a dll. From the respective repo I gather that it should.  
Can you give me a complete list of dependencies for building FSharp on Linux? The README only mentions mono, which only comes with MSBuild related xsd files, but no executable.

**Comment by dsyme** [comment]
@Chais The only dependency should be mono

If you want to compile F# using dotnet-sdk then I think the best way is currently to follow the buildfromsource recipe in http://github.com/Microsoft/visualfsharp.  It's mentioned in the README and/or DEVGUIDE

**Comment by dsyme** [comment]
@puffybsd OK, thanks
