### ISSUE TITLE
An implementation of the file or module '' has already been given

### ISSUE THREAD

**Issue by noelmcgrath** [fsharp/fsharp#838]
Occurs when using folders and file/module with same name

#### Repro steps
1. Create a project

2. Create a folder "Workflow1"

3. Create a file Workflow.fs and a module in it
 `  module Workflow =`

4. Create another folder "Workflow2"

6. Create a file Workflow.fs and a module in it
 `  module Workflow =`

7. Open 2 files in ide

8. Make changes and compile.

#### Expected behavior

No issues should occur, should compile

#### Actual behavior
See error:
![image](https://user-images.githubusercontent.com/671790/38458882-f3c79f40-3a9a-11e8-89e5-9ee5d3462e88.png)

#### Known workarounds

Dont have files with same name, but I want to have this and folder support in 15.6 should allow this.

#### Related information 
Very annoying when trying to do work. Need to close all files and do clean to get rid of red lines in files and errors
Attached project to reproduce

[TestFileModuleWithSameName.zip](https://github.com/fsharp/fsharp/files/1886637/TestFileModuleWithSameName.zip)

**Comment by whitebear-gh** [comment]
I have the same issue in VS Code and Rider. 
Is this F# or FS Compiler Services issue? Maybe it's better to create an issue there?

**Comment by dsyme** [comment]
Please move this issue to Microsoft/visualfsharp, though I suspect it has been resolved

**Comment by dsyme** [comment]
Closing per CONTRIBUTING.md
