### ISSUE TITLE
Discriminated union doesn't work with non English type constructor names

### ISSUE THREAD

**Issue by hmnjeon** [fsharp/fsharp#839]
I opened an [issue](https://github.com/Microsoft/visualfsharp/issues/4697) in visualfsharp repository but apparently I should've opened it here since it concerns the parser. so here it is. 
------
Discriminated union doesn't work with non alphabet string (e.g., Korean string 개수).

#### Repro steps

Provide the steps required to reproduce the problem

1. Type in the following
type some-type =
    | 개수

#### Expected behavior

Should compile. Korean language doesn't have uppercase/lowercase distinction so it should just work with any Korean string.

#### Actual behavior

Error code FS0053 (Discriminated union cases and exception labels must be uppercase identifiers) emitted on VS 2017

#### Known workarounds

Prefixing the string with uppercase English letter works. e.g. U개수

#### Related information 

Provide any related information 

* Windows 10
* 4.1
* VS 2017 Community
-------

From what I've gathered in that thread, adding a set membership test to see if a script is a character in the languages that have lowercase/uppercase distinction would solve the issue IMHO.

**Comment by voronoipotato** [comment]
This seems to fail for most? languages. 
Windows 8
Visual Studio Enterprise 2017 
Visual F# 4.1

 type WuWei = 无为;; //Fails (Chinese) with  error FS0053: Discriminated union cases and exception labels must be uppercase identifiers

 type WuWei = 無爲;; //Fails (Chinese) with error FS0053: Discriminated union cases and exception labels must be uppercase identifiers

type WuWei = むい;; //Works (Japanese)

type WuWei = 無為;; //Fails  (Japanese) with  error FS0053: Discriminated union cases and exception labels must be uppercase identifiers

type WuWei = 무위;; //Fails (Korean) with  error FS0053: Discriminated union cases and exception labels must be uppercase identifiers

type WuWei = 無爲;; //Fails (Korean) with  error FS0053: Discriminated union cases and exception labels must be uppercase identifiers

type Luck = بالتوفيق;; //Fails (Arabic) with  error FS0053: Discriminated union cases and exception labels must be uppercase identifiers

 Type Sorry = ཀོང་དགས་།;; //Fails (Tibetan) with Unexpected Character '་' in interaction. Expected incomplete structured construct at or before this point, ';', ';;' or other token.

A work around for everything but tibetan is the extremely dumb prepending of any capital english letter.
type AWuWei = A无为;; //Works (Chinese) 

Joke option.
type ``💩`` = string;; //Works (???)

**Comment by voronoipotato** [comment]
U+0F0B should probably be excluded since it separates syllables instead of words. 
[tibetan mark intersyllabic tsheg (U+0F0B)](http://graphemica.com/%E0%BC%8B)

**Comment by dsyme** [comment]
@hmnjeon You opened it in the right place originally. closing this one
