### ISSUE TITLE
F# compiler generates methods with `get_` prefix unexpectedly

### ISSUE THREAD

**Issue by A-Manning** [fsharp/fsharp#840]
#### Repro steps
```fsharp
let c = 7
let get_c () = 7
```
```
error FS0037: Duplicate definition of value 'c'
```

This is caused by F# generating a method `get_c` when `c` is defined, which then conflicts with the user-defined `get_c`.

Stranger still, the following still fails
```fsharp
let c = 7
let get_c = 7
```
Despite the intuition that the methods generated would be `get_c` and `get_get_c`, which shouldn't conflict. 

#### Expected behavior

It is expected that F# would generate only a property or field `c`, and not also a method `get_c`.

#### Actual behavior

F# generates a property `c`, as well as `get_c`. I'm not sure why there is a conflict when neither `c` or `get_c` are methods.

#### Known workarounds

Don't  use identifiers that start with `get_`.

#### Related information 

Provide any related information 

* Operating system
Ubuntu 16.04
* Branch
Master
* .NET Runtime, CoreCLR or Mono Version
mono 5.10.1.20
* Editing Tools (e.g. Visual Studio Version)
Not relevant
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
None
* Links to performance testing scripts
Not relevant
* Indications of severity
Unintuitive, particularly for those relying on OCaml compatibility, since this would be accepted in OCaml.
Fixing this could have implications for those using reflection to access properties as methods called `get_property`, but they should be accessing them as properties.
Not sure what the implications of fixing this would be for C# compatibility.

**Comment by dsyme** [comment]
This is by design - a value `let c = ...` gets a property `c` with getter `get_c`.  That's just how things are.

**Comment by matthid** [comment]
@dsyme can you answer about ‘let get_c’ as well? That’s why we moved this from slack...

**Comment by dsyme** [comment]
@matthid When defining `let c = ...` both `c` and `get_c` are reserved as names in the source.

So when defining 
```
let c = 7
let get_c = 7
````
the conflict is between `get_c` (target) and `get_c` (source)
