### ISSUE TITLE
AccessDenied build failures in 'prodcon/fsharp/master/' - '20180411.03'

### ISSUE THREAD

**Issue by jcagme** [fsharp/fsharp#841]
There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1580441
  - **Agent:** DDMBLDW179
  - **Error log:** 1>Warning: System.TypeLoadException: Access is denied: 'Microsoft.FSharp.Compiler.Server.Shared.FSharpInteractiveServer'. while resolving 0x200000e - server@139....

* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1580933
  - **Agent:** DDMBLDW129
  - **Error log:** 1>Warning: System.TypeLoadException: Access is denied: 'Microsoft.FSharp.Compiler.Server.Shared.FSharpInteractiveServer'. while resolving 0x200000e - server@139....

**Comment by dsyme** [comment]
@jcagme This is the wrong repo, try http://github.com/Microsoft/visualfsharp
