### ISSUE TITLE
ReadMe file within root directory is deprecated

### ISSUE THREAD

**Issue by LmTinyToon** [fsharp/fsharp#849]
I have tried to compile fsharp on windows, but it seems like root ReadMe file is deprecated. Here is piece of build instruction on windows:

>### Building on Windows
>
>Install [.NET 4.5.1](http://www.microsoft.com/en-us/download/details.aspx?id=40779).
>
>Build using:
>
>   mono\build.bat
>
>This builds the proto compiler, then the library, then the final compiler.

But link is dead (In my case I have installed .net before). mono folder does not contain build.bat.

How can I compile fsharp? Compiling project via sln file throws errors like  

![image](https://user-images.githubusercontent.com/20486820/40657171-80e76fea-634f-11e8-9c15-4485b22651bf.png)

P.S. At the next step i will try to compile it via visualfsharp repo

**Comment by knocte** [comment]
This issue should be renamed to "mono/build.bat doesn't exist, as per Readme instructions", its current title is confusing.

**Comment by smoothdeveloper** [comment]
@LmTinyToon, if you are building on windows, your best luck is to use Microsoft/visualfsharp repository.

Please also check https://github.com/Microsoft/visualfsharp/blob/master/DEVGUIDE.md

**Comment by LmTinyToon** [comment]
@smoothdeveloper , after this failed attempt I tryed to use VisualSharp and it's ok. At the moment I am using visual sharp repo
