### ISSUE TITLE
F# inheritance with optional constructor parameters

### ISSUE THREAD

**Issue by francotiveron** [fsharp/fsharp#855]
I have this class hierarchy

```
type Base(?maybei : int) =
    let i = defaultArg maybei 0

type Derived(?maybei : int) =
    inherit Base(maybei)
```

#### Expected behavior

No errors

#### Actual behavior

Error in the inherit line (expected int but given int option)

#### Known workarounds

```
type Derived(?maybei : int) =
    inherit Base(defaultArg maybei 0)
```

this works but 
- it forces to defaultArg twice even when the Base default value doesn't need to change in Derived
- the Derived developer needs to know the Base default value and can't simply delegate to it

**Comment by BillHally** [comment]
You need to use a named parameter, and add a `?` character at the start of the parameter name:

```fsharp
type Derived(?maybei : int) =
    inherit Base(?maybei=maybei)
```
