### ISSUE TITLE
NuGet package for Linux fsharpc 

### ISSUE THREAD

**Issue by theimowski** [fsharp/fsharp#859]
I'm wondering whether there's a NuGet package available that ships latest `fsharpc` for linux, similar to how one can reference `FSharp.Compiler.Tools` and use `fsc.exe` on Windows?

My use case is I want to use latest fsharpc on Linux build server, but for the moment can't upgrade F# on that build server.

Feel free to close the issue, if there's currently no option for referencing `fsharpc` via NuGet

**Comment by theimowski** [comment]
As a reference, the issue I'm having with currently installed F# version on the build server is related to https://github.com/fsprojects/SQLProvider/issues/460 

I'm getting: 
```
FSC : error FS0226: The file extension of '$BUILD_DIR/@/tmp/tmp14572c567e394e8abf44c996d383ff04.rsp' is not recognized. 
Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli. [$BUILD_DIR/$PROJECT_NAME.fsproj]
```

**Comment by dsyme** [comment]
>I'm wondering whether there's a NuGet package available that ships latest fsharpc for linux, similar to how one can reference FSharp.Compiler.Tools and use fsc.exe on Windows?

You should be able to use FSharp.Compiler.Tools and invoke using `mono fsc.exe`
