### ISSUE TITLE
Linux: unable to install from source

### ISSUE THREAD

**Issue by bsdooby** [fsharp/fsharp#865]
#### Preamble

* Issue: Unable to compile F# on Linux when following the instructions
given on the homepage https://fsharp.org/use/linux/ (Option 2: Install from source).

* OS: Slackware64-current

* Mono:
Mono JIT compiler version 5.15.0 (master/89ecd02722d Mon Apr 30 11:09:49 CEST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)

* F# version (branch): master

#### Steps to reproduce the problem

0. export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/mono
    export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

1. git clone https://github.com/fsharp/fsharp

2. make

#### Expected behavior

Build F# without any issues

#### Actual behavior

```
$> make
-----------
prefix=/usr/local
topdir=/mnt/data/repositories/git/fsharp/mono/../
monodir=/usr/local/lib/mono
monolibdir=/usr/local/lib/
monobindir=/usr/local/bin/
-----------
make restore
make[1]: Entering directory '/mnt/data/repositories/git/fsharp'
MONO_ENV_OPTIONS= mono .nuget/NuGet.exe restore packages.config -PackagesDirectory packages -ConfigFile .nuget/NuGet.Config
All packages listed in packages.config are already installed.
chmod u+x packages/FSharp.Compiler.Tools.4.1.27/tools/fsi.exe
chmod u+x packages/FsLexYacc.7.0.6/build/fslex.exe
chmod u+x packages/FsLexYacc.7.0.6/build/fsyacc.exe
make[1]: Leaving directory '/mnt/data/repositories/git/fsharp'
make build-proto
make[1]: Entering directory '/mnt/data/repositories/git/fsharp'
MONO_ENV_OPTIONS= msbuild /p:Configuration=Proto /p:TargetDotnetProfile=net40 src/fsharp/FSharp.Build-proto/FSharp.Build-proto.fsproj
/bin/sh: msbuild: command not found
make[1]: *** [Makefile:28: build-proto] Error 127
make[1]: Leaving directory '/mnt/data/repositories/git/fsharp'
make: *** [Makefile:24: all] Error 2
```

#### Known workarounds

None so far.

Apparently there is a dependency on MSBuild (not mentioned). But building MSBuild
does not "help", as then other issues arise. See #836  for a possible workaround, 
but I cannot rely on binary packages as they are not suited to my setup. I want to
have all installed from source.

#### Related information 

None

#### Others (rants)

As the documentation is wrong, this is clearly a bug (of the documentation itself)

**Comment by DragonSA** [comment]
Do you also have msbuild installed?  I think the preferred repo is https://github.com/mono/linux-packaging-msbuild, however FreeBSD uses https://github.com/mono/msbuild

**Comment by bsdooby** [comment]
MSBuild
---

I managed to build msbuild using the repo https://github.com/mono/msbuild. However, I had to choose a specific branch (I just guessed):  **mono-2018-04**. Is this the/a branch that is OK?

One problem I have is that **I do not know how to properly deploy the executable msbuild**, together with its DLLs, such that it can be invoked by the fsharp compilation environment. For now I just point the PATH  env var to the build directory where msbuild resides (../artifacts/mono-msbuild/).

FSharp
---

Unfortuanetly I'm still unable to compile fsharp. **Which is the branch/tag** that is the most up-to-date and is actually "buildable"?

I execute autogen.sh, followed by configure and make. The error I get when using version (tag) **4.1.34**:  ../fsharp/src/scripts/scriptlib.fsx(40,39): error FS0041: A unique overload for method 'StartsWith' could not be determined based on type information prior to this program point.

**Comment by nosami** [comment]
> ../fsharp/src/scripts/scriptlib.fsx(40,39): error FS0041: A unique overload for method 'StartsWith' could not be determined based on type information prior to this program point.

This sounds familiar. Try this patch https://github.com/mono/mono/blob/master/packaging/MacSDK/patches/fsharp-path-overloads.patch

**Comment by nosami** [comment]
Or maybe this one https://github.com/fsharp/fsharp/pull/832/files

**Comment by bsdooby** [comment]
I finally managed to build F# from source :)

What I did:
- cloned mono from https://github.com/mono/mono.git, and built [master] acc. to the instructions given (no problem)
- cloned msbuild from https://github.com/mono/msbuild.git, and just called `make` (initially I had to use branch [mono-2018-04], but yesterday it compiled just fine on [xplat-master] (the default?)?)
- cloned fsharp from https://github.com/fsharp/fsharp.git [master] and set my `PATH` env var to include `.../msbuild/artifacts/mono-msbuild` and proceeded according to the instructions given on  https://fsharp.org/use/linux/, Option 2: Install from source:

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/.../mono/lib/`
`export PKG_CONFIG_PATH=/.../mono/lib/pkgconfig/`
followed by the holy trinity `./configure && make && make install`

Please comment if you're solution to install F# from source differs...

**Comment by iNecas** [comment]
FYI I have not hit this issue on Fedora 29

**Comment by dsyme** [comment]
This has been solved per comments above.

Note the preferred build-from-source option (with no binary package dependencies) is to build the .NET SDK from source with F# support, see "src/buildfromsource.cmd/sh"

**Comment by embix** [comment]
@bsdooby are there any known to be working tags or commit-shas for msbuild? (currently trying to build fsharp-10.2.3 with mono-6.4.0.198 here)
