### ISSUE TITLE
Running msbuild copies also FSharp.Core.resources.dll files into output directory

### ISSUE THREAD

**Issue by mclang** [fsharp/fsharp#868]
I have a F# project that uses paket and FAKE.

Previously when I used Mono's `xbuild` I got only `FSharp.Core.dll` file into the output directory, but after I started to use `msbuild`, I also get these directories that each contain file `FSharp.Core.resources.dll`:
- cs
- de
- en
- fr
- it
- ja
- ko
- pl
- pt-BR
- ru
- tr
- zh-Hans
- zh-Hant

In addition, `msbuild` copies many unnecessary xml files, but I got rid of those using `AllowedReferenceRelatedFileExtensions` directive.

Is those extra directories and files really needed - and if no, why msbuild copies them over when xbuild didn't?

And most importantly, how can I prevent this foolishness?

System information:
* CentOS Linux release 7.5.1804 (Core)
* Mono JIT compiler version 5.12.0.301
* FSharp.Core (4.5.2) 
* FAKE 5.3

**Comment by abelbraaksma** [comment]
Bugs like these more likely get traction in the VisualFSharp GitHub project (see project pages). I encountered this too, plus some other oddities, and logged them as https://github.com/Microsoft/visualfsharp/issues/6007 (that is, in the Visual F# GitHub project).

**Comment by mclang** [comment]
Should I thus close this?

**Comment by dsyme** [comment]
Closing out issues in this repo, if necessary please reopen at https://github.com/dotnet/fsharp, which is now the unified repository for F# work
