### ISSUE TITLE
type alias for "struct(int * int)" must be expressed as System.ValueTuple<int, int> or surrounded by parentheses

### ISSUE THREAD

**Issue by michaelsg** [fsharp/fsharp#874]
#### Repro steps

Define a type alias for a value tuple:
`type Ttt = struct(int * int) // syntax error`
```
error FS0010: Unexpected symbol '(' in member definition
```
Define alias using `System.ValueTuple`.
`> type Ttt = System.ValueTuple<int, int>;;`
FSI reports type as
`type Ttt = struct (int * int)`

Define alias using extra parentheses. 
`> type Ttt = (struct(int * int));;`
FSI reports type as
`type Ttt = struct (int * int)`

#### Expected behavior

The `struct(...)` notation should work in type aliases without requiring extra parentheses. 

The notation works in record fields, function parameters, return types and union cases.

#### Actual behavior

Compiler reports a syntax error.

#### Known workarounds

Use `System.ValueTuple` directly or add parentheses around the entire struct expression.

#### Related information 

F# 4.5. FSI Tools version 10.2.3

**Comment by dsyme** [comment]
This is by design, for various reasons the parentheses are needed to prevent grammar conflicts

**Comment by voronoipotato** [comment]
Do you think it's possible to create a more direct error message than "Unexpected symbol '(' ? Polishing error messages and adding documentation is a good way that newer contributors can get involved that help other newer developers.  Does this only happen for structs or are there other things that would cause this kind of grammar conflict that can be resolved by wrapping the whole thing with parens.  Sorry to pry open a closed ticket, I just thought maybe I saw an opportunity for disambiguation.

**Comment by dsyme** [comment]
@voronoipotato Yes, it would be possible to do that, it would be a great contribution!
