### ISSUE TITLE
System.TypeLoadException in mono when running fsharp compiled code linked to a library with same name

### ISSUE THREAD

**Issue by sporring** [fsharp/fsharp#877]
This problem has been posted and close on https://github.com/mono/mono/issues/10872, and I've been asked to repost it here.

## Steps to Reproduce

1. Make a library and an application with filenames app.fs and app.fsx, e.g.,

E.g., app.fs:
```
module test
let trunc v =
  if v < 0 then 0
  elif v > 255 then 255
  else v
```
app.fsx:
`printfn "%d" (test.trunc 260)`

2. Compile the library and link with the application:

`fsharpc --nologo -a app.fs && fsharpc --nologo -r app.dll app.fsx && mono app.exe`

### Current Behavior

The above procedure causes mono to halt with an 

```
$  fsharpc --nologo -a app.fs && fsharpc --nologo -r app.dll app.fsx && mono app.exe

Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000010 from typeref (expected class 'test' in assembly 'app, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000010 from typeref (expected class 'test' in assembly 'app, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
```

Note, that this neither the case, if the two files are compiled simultaneously

```
$ fsharpc --nologo app.fs app.fsx && mono app.exe
255
```

nor if run through fsharpi

```
$ fsharpi app.fs app.fsx
255
```

There seems to be a name clash in the exe-file, since if app.fs is changed to a name, whose prefix does not coincide with app.fsx, then everything works fine:

```
$ mv app.fs lib.fs
$ fsharpc --nologo -a lib.fs && fsharpc --nologo -r lib.dll app.fsx && mono app.exe
255
```

### Expected Behavior

It is expected not to cast an exception at runtime or to give a compile error.

## On which platforms did you notice this

[X] macOS
[X] Linux
[X] Windows

**Version Used**:

I have tried on various versions of operating systems and Mono versions 5.10.1 and 5.14.0. Presently, I'm using macOS and:

mono --version
Mono JIT compiler version 5.14.0.177 (2018-04/f3a2216b65a Fri Aug  3 09:28:16 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)

**Comment by dsyme** [comment]
Closing out issues in this repo, if necessary please reopen at https://github.com/dotnet/fsharp, which is now the unified repository for F# work
