### ISSUE TITLE
fsi should support checking syntax w/o running

### ISSUE THREAD

**Issue by lzybkr** [fsharp/fsharp#879]
It would be handy if we could run `fsi` with an option to report compiler errors but not run the script.

We would use this in our build environment to check our maintenance scripts which aren't always updated when some related compiled code changes.

**Comment by dsyme** [comment]
@lzybkr You can normally just compile the scripts using `fsc script.fsx`

The main limitation is that this won't work if the scripts are phased/multi-stage (e.g. using `;;` where the side-effects of one phase affects the type checking of the next)
