### ISSUE TITLE
Implementation of an interface is not visible

### ISSUE THREAD

**Issue by MNie** [fsharp/fsharp#881]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

Repository to reproduce a problem:
https://github.com/MNie/F-InterfaceIssue

Steps to reproduce it manually
1. Create an interface in F# with some method(s)
2. Create a type which implements this interface
3. Create c# project and reference project with previously added logic written in F#
4. Create an instance of a type (from point 2)
5. Try to invoke a method which should be implemented via type and intellisense says it was implemented.
6. Compile -> compilation error: "Returns CS1061 The element "SomeClass" does not contain a definition of Some, and an extension "Some" which accepts the first argument SomeClass was not found."

#### Expected behavior

Project compiles.

#### Actual behavior

The project does not compile with an error:
"CS1061 The element "SomeClass" does not contain a definition of Some, and an extension "Some" which accepts first argument SomeClass was not found."

#### Known workarounds

instead of writing:
```csharp
var s = new SomeClass();
```

I write:

```csharp
IInterface s = new SomeClass()
```

#### Related information 

Provide any related information 

* Operating system: Windows 10
* Branch
* .NET Runtime, CoreCLR or Mono Version: .net core 2.1.301
* Editing Tools (e.g. Visual Studio Version): JetBrains Rider 2018.2.3

**Comment by matthid** [comment]
This is by design, F# uses explicit interface implementation. The same behavior is shown with only c# and explicit interface implementation (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation)

**Comment by MNie** [comment]
@matthid Thanks for an answer :) Closing this one.
