### ISSUE TITLE
.Net Core FSI causes security exception when attempting to executing a PInvoke call

### ISSUE THREAD

**Issue by patrickallensimpson** [fsharp/fsharp#886]
When running the .Net Core version of the F# Interactive Service we get a security exception on any invocation of a PInvoke call that was generated in the script itself.

1. Start .Net Core version of fsi.exe
```
dotnet 'C:\Program Files\dotnet\sdk\3.0.100-preview-009812\FSharp\fsi.exe'
```

2. Enter the following script:

```
open System.Runtime.InteropServices
[<DllImport("kernel32")>]
extern int GetLastError()

GetLastError()

```
3. You'll see the following exception:

```
System.Security.SecurityException: ECall methods must be packaged into a system module.
   at <StartupCode$FSI_0012>.$FSI_0012.main@()
Stopped due to error

```
On .Net Framework fsi this will execute and return the last error this is just the simplest test case I could think of.

I investigated and this is due to a check in ecall.cpp:346 inside the coreclr project.

```

    if (!pMD->GetModule()->IsSystem())
        COMPlusThrow(kSecurityException, BFA_ECALLS_MUST_BE_IN_SYS_MOD);


```
They perform a check on the incoming module to see if it is a system module (My guess is this means it's loaded from disk?) In any case if it is not then they throw this error. This means any scripts that were using PInvoke to call win32 services or other C api's CAN NOT work on the CoreCLR fsi version.

I've confirmed this is the case with .Net Core 2.0, 2.1, 2.2 and 3.0 preview at the exact same line number.

It there something that can be done to let the CoreCLR system know that the dynamically generated FSI assemblies are ok as far as this check is concerned?

Thanks,
-Patrick Simpson

[DotNetFSISecurityFailureTest.zip](https://github.com/fsharp/fsharp/files/2662468/DotNetFSISecurityFailureTest.zip)

**Comment by dsyme** [comment]
@patrickallensimpson We should ask the .NET Core team I think, can you open a .NET Core bug on this?

**Comment by KevinRansom** [comment]
@jkotas, Thanks mate.

**Comment by KevinRansom** [comment]
@jkotas 

It looks like it will not be reintroduced until Dotnet Core 3.0

https://apisof.net/catalog/System.Reflection.Emit.TypeBuilder.DefinePInvokeMethod(String,String,String,MethodAttributes,CallingConventions,Type,Type(),Type(),Type(),Type()(),Type()(),CallingConvention,CharSet)

**Comment by patrickallensimpson** [comment]
I've been going over the usage of the FX_RESHAPED_REFEMIT define in the ilreflect.fs and it looks like we might need a different set of defines or re-think API usage here. Are there specifications on what the absil is expecting as far as behavior regarding method usage from the Emit? I'm looking at some other cases related to the #defines that might be served by moving to other API's that both Core and Framework 4.5+ have in common. This is an area I'm particularly interested in and wouldn't mind helping to fix since I've got a significant amount of PInvoke scripts that I use with the Framework but want to start using Core going forward.

What are the framework expectations regarding F# moving forward do we need to keep supporting 2.0 and such?

To give you some background for why I want to get this fixed:

This whole issue came up when I started up a new Web project that I decided to target to CoreCLR. In the processes I wanted to use the SQLGeography implementation from Microsoft.SqlServer.Types but that doesn't work with CoreCLR. So I just re-implemented the Geography type using PInvoke direct to the underlying native DLL included in that project and in the process simplified the API for using with F#.

Everything was fine until I wanted to execute some code in in the REPL F# Interactive and I noticed that I get the security exception, unless I loaded the PInvoke calls from a DLL. (I hacked Visual Studio 2017 to use the CoreCLR fsi instead of the normal FSI, of course the debug feature doesn't work right since I'm spawning the CoreCLR fsi from another app). 

I use the FSI all the time to test my code while writing it, it's better than unit tests honestly. I can write some code execute it right there and check that the results make sense. And if your doing things "Right" were the only dependencies in your function come from arguments its makes this strategy work really well. This is why I'm highly motivated to get this working for CoreCLR 3.0 at least. I'd move all my projects forward a version just for this feature.

Thanks,
-Patrick

**Comment by patrickallensimpson** [comment]
Considering that we now have F# 4.6 FSI as a preview dotnet command `dotnet fsi` inside the .Net Core 3.0 preview 3 shouldn't we fix that #define now? This is still an issue under 3.0.100-preview3-010431 running Microsoft (R) F# Interactive version 10.4.0 for F# 4.6

Thanks!

**Comment by dsyme** [comment]
@patrickallensimpson This should be a bug in Microsoft/visualfsharp I think - can you move this bug there and ask for @KevinRansom's input? thanks

**Comment by patrickallensimpson** [comment]
I've created a new issue over in [Microsoft/visualfsharp](https://github.com/Microsoft/visualfsharp/issues/6544#issue-433234009) as you requested. I'll contact @KevinRansom next.

**Comment by patrickallensimpson** [comment]
Thanks to the great work by @KevinRansom I'm closing this issue. Kevin, thanks again. This means I can move fully over to .NET Core now for all my scripts thanks again!

-Patrick
