### ISSUE TITLE
Why is Map.filter 10x slower than using a query to select the keys and remove those individually?

### ISSUE THREAD

**Issue by weebs** [fsharp/fsharp#888]
I noticed something odd when removing a group of elements from a Map. It is 10x slower to use Map.filter with a predicate, compared to using a query expression to gather the keys of elements which satisfy the predicate and removing those individually with Map.Remove.

```
let removeKeys (keys : Key list) (items : Map<Key, Value>) =
    keys |> List.fold (fun (m : Map<Key, Value>) k -> m.Remove(k)) items

let deleteContractA (items : Map<Key, Value>) (contract : string) =
   items |> Map.filter (fun k v -> not(k.Contract.Equals(contract)))

let deleteContractB (items : Map<Key, Value>) (contract : string) =
    let keysToRemove =
        query {
            for kv in items do
            where (kv.Key.Contract.Equals(contract))
            select kv.Key
        } |> List.ofSeq
    items |> removeKeys keysToRemove
```

#### Expected behavior

deleteContractA and deleteContractB take similar amounts of time to evaluate

#### Actual behavior

deleteContractB is 10x faster to evaluate than deleteContractA 

#### Related information 

Contract is a string field in the Key record type, and I'm working with about 10,000 elements. The Key does have a custom compare implemented because of a decimal field which are considered equal when within a 1e-9 range, but I would imagine that doesn't effect this scenario.

* Windows 7
* .NET Core 2.1
* VS2017

**Comment by 7sharp9** [comment]
You might geta  better response if you create an issue in the visualfsharp repo:  https://github.com/Microsoft/visualfsharp

**Comment by dsyme** [comment]
Yes, wrong repo.
