### ISSUE TITLE
FSI evaluates expressions incorrectly

### ISSUE THREAD

**Issue by mosquitobite82** [fsharp/fsharp#891]
![fsievaluates](https://user-images.githubusercontent.com/10011614/51897542-44153400-23af-11e9-882a-cfba2baad7c8.jpg)
#### Repro steps
How to reproduce the error:
1. Start fsi in a console
2. Write a statement that you will have to change, like "let manhatanDistence (pixel1, pixel2) = and before you hit enter to start next line of code you backspace to correct the misspellings and write the line again.
3. Press enter.

#### Expected behavior
No error and to be able to write the next line of code.

#### Actual behavior
An error that shows that fsi has evaluated the statement incorrectly. Mixing up characters and having more characters than the actual expression.

#### Known workarounds
The issue does not seem to come up if I don't have to go back to delete and retype some characters.

#### Related information 
I've tried fsi within the terminal of Visual Studio Code and in a stand alone terminal and the issue is the same.

I'm not sure about the following to be related (so with a strong disclaimer on the validity of this statement but I should mention it since it might help you), but I've had some seriously strange behavior on unit testing with f sharp as well since I observed the issue described above.

OS: Ubuntu 18.04.1 LTS
FSI Version: 10.2.3
dotnet sdk version: 2.1.503
.NETRuntime: CoreCLR
Editing Tools: VS Code 1.30.2, FSI in a standalone console.

**Comment by dsyme** [comment]
Closing out issues in this repo, if necessary please reopen at https://github.com/dotnet/fsharp, which is now the unified repository for F# work
