### ISSUE TITLE
F#: [<StructuredFormatDisplay>] in composed records just print dots. (...)

### ISSUE THREAD

**Issue by srlopez** [fsharp/fsharp#901]
Context: 
Running F# in a containerized environment with **`dotnet 2.2.203`**
F# Version:  $ fsharpc
               Microsoft (R) F# Compiler version 10.2.3 for **F# 4.5**

**Question: The `StructuredFormatDisplay` in a Composed Record doesn't work.**

#### Repro steps
These is the code

```
[<StructuredFormatDisplay("{SizeGb}GB")>]
type Disk = 
    { SizeGb : int }
    override __.ToString() = sprintf "<%dGB>" __.SizeGb

[<StructuredFormatDisplay("Computer #{Id}: {Manufacturer}/{DiskCount}:{Disks}")>]
type Computer =
    { Id: int
      mutable Manufacturer: string
      mutable Disks: Disk list }
      override __.ToString() = sprintf "#%d<%s>%O" __.Id __.Manufacturer __.Disks

   
[<EntryPoint>]
let main argv =

    let myPc =
        { Id = 0
          Manufacturer = "Computers Inc."
          Disks =
            [ { SizeGb = 100 }
              { SizeGb = 250 }
              { SizeGb = 500 } ] }

    printfn "%%O = %O" myPc 
    printfn "%%A = %A" myPc   
    0
```
#### Expected behavior
The expected behavior just print the Diks size correctly on both lines %O and %A
```
%O = #0<Computers Inc.>[<100GB>; <250GB>; <500GB>]
%A = Computer #0: Computers Inc./3:[100GB; 250GB; 500GB]
```
#### Actual behavior
On the %A line apears some dots (...) insted of the real value
```
%O = #0<Computers Inc.>[<100GB>; <250GB>; <500GB>]
%A = Computer #0: Computers Inc./3:[...GB; ...GB; ...GB]
```
#### Known workarounds

One workaround could be adding a new string property holding the formatted string of the disk list, and use that property instead: ([stackoverflow](https://stackoverflow.com/questions/55985835/f-structuredformatdisplay-vs-override-tostring-what-its-wrong))
```
[<StructuredFormatDisplay("Computer #{Id}: {Manufacturer}/{DiskCount}:{DisksStr}")>]
type Computer =
{ Id: int
  mutable Manufacturer: string
  mutable Disks: Disk list }
  member this.DisksStr = sprintf "%A" this.Disks
```
#### Related information 
Running F# in a containerized environment with **`dotnet 2.2.203`**
F# Version:  $ fsharpc
                    Microsoft (R) F# Compiler version 10.2.3 for **F# 4.5**

**Comment by srlopez** [comment]
There's definitely something wrong with the Id.
Using as you indicate, for example:
    `computers.delete(fun c -> c.Manufacturer.Contains "m")`
or 
    `computers.findMany (fun c -> c.Manufacturer.Contains "m") |> Seq.iter (printfn "%A")`
everything is fine, except if the expression includes Id. 
   `computers.delete(fun c -> c.Id <57)`
or 
    `computers.findMany (fun c -> c.Id>3) |> Seq.iter (printfn "%A")`
in theses cases doesn't run delete or findMany.

**Comment by dsyme** [comment]
Please reopen this issue at https://github.com/dotnet/fsharp, which is now the unified repository for F# work.
