### ISSUE TITLE
can't run fsi 

### ISSUE THREAD

**Issue by baio** [fsharp/fsharp#904]
Machine windows 10 pro developer mode 
go to `C:\Program Files\dotnet\sdk\3.0.100\FSharp`

`fsi`

BOOOM

This app can't run on your PC. And then in console Access Denied.

Tried in PS, command and admin mode, the same issue for all installed dotnet version (

Whats could be wrong here ?

**Comment by baronfel** [comment]
FSI in dotnet core is an app that has to be run via 'dotnet FSI', not standalone as I think you're showing here.

**Comment by baio** [comment]
thats was fast, thanks!

**Comment by knocte** [comment]
It would be nice to have a better error message.

**Comment by baronfel** [comment]
For that I would suggest looking into issues on dotnet/coreclr or another of the dotnet runtime repos, as that's the domain of the binary launcher and not related to fsharp at all.
