### ISSUE TITLE
Proposal: Make it more obvious how to quit fsharpi

### ISSUE THREAD

**Issue by mcandre** [fsharp/fsharp#92]
In _most_ interpreters, typing `exit` or pressing `Control+C` is sufficient. At the very least, the interpreter should explicitly state how to quit itself.

Update: I hear that `Control+C` works for some users, but on Mac, the interpreter just says `- Interrupt` and keeps running.

**Comment by stmax82** [comment]
this is fine.. i just google for it. every. single. time.

**Comment by denivic** [comment]
Just FYI they still haven't done anything about it and in 2 years it's been a decade. What was the reasoning behind `#quit;;` anyway? As @mcandre pointed out it's not intuitive at all. If you're so adamant about keeping `#quit;;` at least add Ctrl + C support (I'm using Windows 10 and it simply says "Interrupt" when I use Ctrl+C) or `quit`/`quit()`/`exit`/`exit()` etc.

**Comment by voronoipotato** [comment]
`exit 0;;` `#quit;;` `Ctrl-C` and `Ctrl-D` currently work as of FSI v12. `#quit;;` is listed in the `#help;;` which is listed when you open FSI. Even still, might not be a terrible idea to prompt it when you type quit or exit from the console.
